# Generated by Django 4.2.7 on 2024-05-24 19:56

from django.db import migrations, models
import payments.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.IntegerField(choices=[(1, 'BASIC'), (2, 'PREMIUM'), (3, 'STARTER'), (4, 'CREATOR'), (5, 'BUSINESS'), (6, 'ENTERPRISE')])),
                ('payment_provider', models.IntegerField(choices=[(1, 'Stripe'), (2, 'PayPal')])),
                ('external_id', models.CharField(help_text='Subscription ID from the payment provider', max_length=255)),
                ('auto_recharge_enabled', models.BooleanField(default=False)),
                ('auto_recharge_balance_threshold', models.IntegerField(default=300, validators=[payments.models.validate_auto_recharge_balance_threshold])),
                ('auto_recharge_topup_amount', models.IntegerField(default=10, validators=[payments.models.validate_addon_amount])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['plan'], name='payments_su_plan_23b2f6_idx')],
                'unique_together': {('payment_provider', 'external_id')},
            },
        ),
    ]
