# Generated by Django 4.2.7 on 2024-05-14 14:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AutoRechargeSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_provider', models.IntegerField(blank=True, choices=[(1, 'Stripe'), (2, 'Paypal')], null=True)),
                ('external_id', models.CharField(blank=True, help_text='Subscription ID for PayPal and payment_method_id for Stripe', max_length=255, null=True)),
                ('topup_amount', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('topup_threshold', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
