# Generated by Django 4.2.7 on 2024-05-14 12:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autorechargesubscription',
            name='external_id',
            field=models.CharField(blank=True, help_text='Subscription ID for PayPal and payment_method_id for Stripe', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='autorechargesubscription',
            name='payment_provider',
            field=models.IntegerField(blank=True, choices=[(1, 'Stripe'), (2, 'Paypal')], null=True),
        ),
        migrations.AlterField(
            model_name='autorechargesubscription',
            name='topup_amount',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
