# Generated by Django 4.2.7 on 2024-05-14 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.IntegerField(choices=[(1, 'BASIC'), (2, 'PREMIUM')])),
                ('payment_provider', models.IntegerField(choices=[(1, 'Stripe'), (2, 'Paypal')])),
                ('external_id', models.CharField(help_text='Resource ID from the payment provider', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['plan'], name='payments_su_plan_23b2f6_idx')],
                'unique_together': {('payment_provider', 'external_id')},
            },
        ),
    ]
