# Generated by Django 4.2.7 on 2024-06-04 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='monthly_budget_email_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
