# Generated by Django 4.2.7 on 2024-05-22 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='plan',
            field=models.IntegerField(choices=[(1, 'BASIC'), (2, 'PREMIUM'), (3, 'STARTER'), (4, 'CREATOR'), (5, 'BUSINESS'), (6, 'ENTERPRISE')]),
        ),
    ]
