# Generated by Django 4.2.7 on 2024-06-04 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_subscription_monthly_budget_email_sent_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='external_id',
            field=models.CharField(blank=True, help_text='Subscription ID from the payment provider', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='payment_provider',
            field=models.IntegerField(blank=True, choices=[(1, 'Stripe'), (2, 'PayPal')], default=None, null=True),
        ),
    ]
