# Generated by Django 4.2.7 on 2024-06-10 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_alter_subscription_external_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='auto_recharge_balance_threshold',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
