# Generated by Django 4.2.7 on 2024-05-23 12:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_autorechargesubscription_auto_recharge_balance_threshold_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AutoRechargeSubscription',
        ),
        migrations.AddField(
            model_name='subscription',
            name='auto_recharge_balance_threshold',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='subscription',
            name='auto_recharge_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscription',
            name='auto_recharge_topup_amount',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
