# Generated by Django 5.1.3 on 2025-03-25 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_alter_subscription_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='plan',
            field=models.IntegerField(choices=[(1, 'Basic Plan'), (2, 'Premium Plan'), (4, 'Creator'), (5, 'Business (2024)'), (3, 'Pay as you go'), (7, 'Business'), (6, 'Enterprise')]),
        ),
    ]
