# Generated by Django 5.2.10 on 2026-03-10 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0006_alter_subscription_plan"),
        ("workspaces", "0015_workspacemembership_balance"),
    ]

    operations = [
        migrations.CreateModel(
            name="SeatType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("monthly_charge", models.PositiveIntegerField(default=0)),
                ("monthly_credit_limit", models.PositiveIntegerField(default=0)),
                (
                    "key",
                    models.CharField(
                        editable=False,
                        help_text='\n            A unique identifier for this seat type. Should not be changed once set.\n\n            This is not displayed anywhere but used in the backend to calculate\n            and store billing with third-party APIs e.g. Stripe.\n            Recommended to use versioned strings (e.g. "2026/learner").\n        ',
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        default=False,
                        help_text="\n            Whether this seat type is available for purchase by any workspace.\n            If True, this seat type will be shown in the billing page.\n        ",
                    ),
                ),
                (
                    "plan",
                    models.IntegerField(
                        choices=[
                            (1, "Basic Plan"),
                            (2, "Premium Plan"),
                            (4, "Creator"),
                            (5, "Business (2024)"),
                            (7, "Business"),
                            (3, "Free"),
                            (8, "Standard"),
                            (9, "Team"),
                            (6, "Enterprise"),
                        ],
                        help_text="\n            The pricing plan this seat type is associated with.\n            The seat type will only be available for selection under this plan.\n        ",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name="subscription",
            name="amount",
            field=models.IntegerField(
                default=0,
                help_text="The amount (Gooey credits) added/deducted in this transaction.<br>Positive for credits added, negative for credits deducted.",
            ),
        ),
        migrations.AddField(
            model_name="subscription",
            name="charged_amount",
            field=models.PositiveIntegerField(
                default=0,
                help_text="The charged dollar amount in the currency’s smallest unit.<br>E.g. for 10 USD, this would be of 1000 (that is, 1000 cents).<br><a href='https://stripe.com/docs/currencies'>Learn More</a>",
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="plan",
            field=models.IntegerField(
                choices=[
                    (1, "Basic Plan"),
                    (2, "Premium Plan"),
                    (4, "Creator"),
                    (5, "Business (2024)"),
                    (7, "Business"),
                    (3, "Free"),
                    (8, "Standard"),
                    (9, "Team"),
                    (6, "Enterprise"),
                ]
            ),
        ),
        migrations.CreateModel(
            name="SubscriptionSeat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_to",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="seat",
                        to="workspaces.workspacemembership",
                    ),
                ),
                (
                    "seat_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="seats",
                        to="payments.seattype",
                    ),
                ),
                (
                    "subscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seats",
                        to="payments.subscription",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("subscription", "assigned_to"),
                        name="unique_subscription_seat_assignment",
                    )
                ],
            },
        ),
    ]
