# Generated by Django 5.1.3 on 2025-11-26 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0006_alter_subscription_plan"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="amount",
            field=models.IntegerField(
                default=0,
                help_text="The amount (Gooey credits) added/deducted in this transaction.<br>Positive for credits added, negative for credits deducted.",
            ),
        ),
        migrations.AddField(
            model_name="subscription",
            name="charged_amount",
            field=models.PositiveIntegerField(
                default=0,
                help_text="The charged dollar amount in the currency’s smallest unit.<br>E.g. for 10 USD, this would be of 1000 (that is, 1000 cents).<br><a href='https://stripe.com/docs/currencies'>Learn More</a>",
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="auto_recharge_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="plan",
            field=models.IntegerField(
                choices=[
                    (1, "Basic Plan"),
                    (2, "Premium Plan"),
                    (4, "Creator"),
                    (5, "Business (2024)"),
                    (3, "Free"),
                    (8, "Standard"),
                    (7, "Business"),
                    (6, "Enterprise"),
                ]
            ),
        ),
    ]
