# Generated by Django 5.1.3 on 2025-10-29 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0007_alter_subscription_auto_recharge_enabled"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="plan_tier_key",
            field=models.CharField(
                blank=True,
                help_text="Tier key for plans with multiple pricing tiers (e.g., 'standard_25')",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="plan",
            field=models.IntegerField(
                choices=[
                    (1, "Basic Plan"),
                    (2, "Premium Plan"),
                    (4, "Creator"),
                    (5, "Business (2024)"),
                    (3, "Pay as you go"),
                    (8, "Standard"),
                    (7, "Business"),
                    (6, "Enterprise"),
                ]
            ),
        ),
    ]
