# Generated by Django 5.1.3 on 2026-04-01 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0007_seattype_subscription_amount_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="seattype",
            name="plan",
            field=models.IntegerField(
                choices=[
                    (1, "Basic Plan"),
                    (2, "Premium Plan"),
                    (4, "Creator"),
                    (5, "Business (2024)"),
                    (7, "Business"),
                    (3, "Free"),
                    (8, "Pro"),
                    (9, "Team"),
                    (6, "Enterprise"),
                ],
                help_text="\n            The pricing plan this seat type is associated with.\n            The seat type will only be available for selection under this plan.\n        ",
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="amount",
            field=models.IntegerField(
                default=0,
                help_text="\n            For non-Team plans, this is the number of credits added for each cycle in\n            this subscription.<br/>\n            For Team plan, this is the number of seats bought in this subscription.<br>\n            ",
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="auto_recharge_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="charged_amount",
            field=models.PositiveIntegerField(
                default=0,
                help_text="The charged dollar amount in the currency's smallest unit.<br>E.g. for 10 USD, this would be of 1000 (that is, 1000 cents).<br><a href='https://stripe.com/docs/currencies'>Learn More</a>",
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="plan",
            field=models.IntegerField(
                choices=[
                    (1, "Basic Plan"),
                    (2, "Premium Plan"),
                    (4, "Creator"),
                    (5, "Business (2024)"),
                    (7, "Business"),
                    (3, "Free"),
                    (8, "Pro"),
                    (9, "Team"),
                    (6, "Enterprise"),
                ]
            ),
        ),
    ]
