# Generated by Django 5.1.3 on 2025-12-30 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0007_subscription_amount_subscription_charged_amount_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="seats",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="auto_recharge_enabled",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="plan",
            field=models.IntegerField(
                choices=[
                    (1, "Basic Plan"),
                    (2, "Premium Plan"),
                    (4, "Creator"),
                    (5, "Business (2024)"),
                    (7, "Business"),
                    (3, "Free"),
                    (8, "Standard"),
                    (9, "Team"),
                    (6, "Enterprise"),
                ]
            ),
        ),
    ]
