# Generated by Django 5.2.10 on 2026-03-05 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0008_subscription_seats_and_more"),
        ("workspaces", "0014_workspaceseattype_and_membership_seat_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subscription",
            name="seats",
        ),
        migrations.CreateModel(
            name="SeatType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("monthly_charge", models.PositiveIntegerField(default=0)),
                ("monthly_credit_limit", models.PositiveIntegerField(default=0)),
                (
                    "is_public",
                    models.BooleanField(
                        default=False,
                        help_text="\n            Whether this seat type is available for purchase by any workspace.\n            If True, this seat type will be shown in the billing page.\n        ",
                    ),
                ),
                (
                    "plan",
                    models.IntegerField(
                        choices=[
                            (1, "Basic Plan"),
                            (2, "Premium Plan"),
                            (4, "Creator"),
                            (5, "Business (2024)"),
                            (7, "Business"),
                            (3, "Free"),
                            (8, "Standard"),
                            (9, "Team"),
                            (6, "Enterprise"),
                        ],
                        help_text="\n            The pricing plan this seat type is associated with.\n            The seat type will only be available for selection under this plan.\n        ",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "indexes": [models.Index(fields=["name"], name="seat_type_name_idx")],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("name",), name="unique_payment_seat_type_name"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="SubscriptionSeat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_to",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="seat",
                        to="workspaces.workspacemembership",
                    ),
                ),
                (
                    "seat_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="seats",
                        to="payments.seattype",
                    ),
                ),
                (
                    "subscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seats",
                        to="payments.subscription",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("subscription", "assigned_to"),
                        name="unique_subscription_seat_assignment",
                    )
                ],
            },
        ),
    ]
