# Generated by Django 5.1.3 on 2025-10-31 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0008_add_plan_tier_key"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscription",
            name="plan",
            field=models.IntegerField(
                choices=[
                    (1, "Basic Plan"),
                    (2, "Premium Plan"),
                    (4, "Creator"),
                    (5, "Business (2024)"),
                    (3, "Free"),
                    (8, "Standard"),
                    (7, "Business"),
                    (6, "Enterprise"),
                ]
            ),
        ),
    ]
