# Generated by Django 5.0.9 on 2024-09-15 18:36

import bots.custom_fields
import django.db.models.deletion
import workspaces.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_users', '0021_remove_appusertransaction_app_users_a_user_id_9b2e8d_idx_and_more'),
        ('payments', '0005_alter_subscription_plan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('logo', bots.custom_fields.CustomURLField(blank=True, max_length=2048, null=True)),
                ('domain_name', models.CharField(blank=True, db_index=True, max_length=30, null=True, validators=[workspaces.models.validate_workspace_domain_name])),
                ('balance', models.IntegerField(default=0, verbose_name='bal')),
                ('is_paying', models.BooleanField(default=False, verbose_name='paid')),
                ('stripe_customer_id', models.CharField(blank=True, default='', max_length=255)),
                ('low_balance_email_sent_at', models.DateTimeField(blank=True, null=True)),
                ('is_personal', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_workspaces', to='app_users.appuser')),
                ('subscription', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workspace', to='payments.subscription')),
            ],
        ),
        migrations.CreateModel(
            name='WorkspaceInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('role', models.IntegerField(choices=[(1, '🏆 Owner'), (2, '🔧 Admin'), (3, '👥 Member')], default=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.IntegerField(choices=[(1, 'Pending'), (2, 'Accepted'), (3, 'Rejected'), (4, 'Canceled')], default=1)),
                ('auto_accepted', models.BooleanField(default=False)),
                ('last_email_sent_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_invites', to='app_users.appuser')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='app_users.appuser')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='workspaces.workspace')),
            ],
        ),
        migrations.CreateModel(
            name='WorkspaceMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('role', models.IntegerField(choices=[(1, '🏆 Owner'), (2, '🔧 Admin'), (3, '👥 Member')], default=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invite', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='membership', to='workspaces.workspaceinvite')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_memberships', to='app_users.appuser')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='workspaces.workspace')),
            ],
        ),
        migrations.AddConstraint(
            model_name='workspace',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted__isnull', True)), fields=('domain_name',), name='unique_domain_name_when_not_deleted', violation_error_message='This domain name is already in use by another team. Contact Gooey.AI Support <support@gooey.ai> if you think this is a mistake.'),
        ),
        migrations.AddConstraint(
            model_name='workspace',
            constraint=models.UniqueConstraint(models.F('created_by'), condition=models.Q(('deleted__isnull', True), ('is_personal', True)), name='unique_personal_workspace_per_user'),
        ),
        migrations.AlterUniqueTogether(
            name='workspaceinvite',
            unique_together={('workspace', 'email')},
        ),
        migrations.AddIndex(
            model_name='workspacemembership',
            index=models.Index(fields=['workspace', 'role', 'deleted'], name='workspaces__workspa_c30f6a_idx'),
        ),
        migrations.AddConstraint(
            model_name='workspacemembership',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted__isnull', True)), fields=('workspace', 'user'), name='unique_workspace_user'),
        ),
    ]
