# Generated by Django 4.2.7 on 2024-09-03 12:59

import bots.custom_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workspace',
            name='logo',
            field=bots.custom_fields.CustomURLField(blank=True, max_length=2048, null=True),
        ),
    ]
