# Generated by Django 5.1.1 on 2024-09-16 00:13

import django.core.validators
import workspaces.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workspace',
            name='domain_name',
            field=models.CharField(blank=True, db_index=True, max_length=30, null=True, validators=[django.core.validators.DomainNameValidator(), workspaces.models.validate_workspace_domain_name]),
        ),
    ]
