# Generated by Django 5.1.1 on 2024-09-30 07:00

from django.db import migrations, models


def migrate_canceled_and_rejected_workspace_invitations(apps, schema_editor):
    # Migrate canceled and rejected workspace invitations to canceled status
    WorkspaceInvite = apps.get_model('workspaces', 'WorkspaceInvite')
    WorkspaceInvite.objects.filter(status=4).update(status=3)


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0002_alter_workspace_domain_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workspaceinvite',
            name='status',
            field=models.IntegerField(choices=[(1, 'Pending'), (2, 'Accepted'), (3, 'Canceled')], default=1),
        ),
        migrations.RunPython(migrate_canceled_and_rejected_workspace_invitations),
    ]
