# Generated by Django 5.1.1 on 2024-09-18 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0002_alter_workspace_domain_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workspace',
            old_name='logo',
            new_name='photo_url',
        ),
    ]
