# Generated by Django 5.1.2 on 2024-11-20 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0003_rename_logo_workspace_photo_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workspaceinvite',
            name='status',
            field=models.IntegerField(choices=[(1, 'Pending'), (2, 'Accepted'), (3, 'Canceled')], default=1),
        ),
    ]
