# Generated by Django 5.1.3 on 2024-12-23 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0006_workspace_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspaceinvite',
            name='clicks',
            field=models.IntegerField(default=0),
        ),
    ]
