# Generated by Django 5.1.3 on 2025-01-19 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0007_workspaceinvite_clicks'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='onedrive_access_token',
            field=models.TextField(blank=True, default='', editable=False, help_text='Onedrive OAuth2 access token (mandatory)'),
        ),
        migrations.AddField(
            model_name='workspace',
            name='onedrive_refresh_token',
            field=models.TextField(blank=True, default='', editable=False, help_text='OneDrive OAuth2 refresh token'),
        ),
    ]
