# Generated by Django 5.1.3 on 2025-01-29 15:36

import bots.custom_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0008_workspace_handle'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='banner_url',
            field=bots.custom_fields.CustomURLField(blank=True, max_length=2048, null=True),
        ),
    ]
