# Generated by Django 5.1.3 on 2025-01-23 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0008_workspace_handle'),
        ('workspaces', '0008_workspace_onedrive_access_token_and_more'),
    ]

    operations = [
    ]
