# Generated by Django 5.1.3 on 2025-02-17 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0008_workspace_handle'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='onedrive_access_token',
            field=models.TextField(blank=True, default='', help_text='Onedrive OAuth2 access token'),
        ),
        migrations.AddField(
            model_name='workspace',
            name='onedrive_refresh_token',
            field=models.TextField(blank=True, default='', help_text='OneDrive OAuth2 refresh token'),
        ),
        migrations.AddField(
            model_name='workspace',
            name='onedrive_user_name',
            field=models.CharField(blank=True, default='', help_text='Onedrive Registered Account Name', max_length=100),
        ),
    ]
