# Generated by Django 5.1.3 on 2025-02-24 08:55

import bots.custom_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0009_workspace_onedrive_access_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='banner_url',
            field=bots.custom_fields.CustomURLField(blank=True, max_length=2048, null=True),
        ),
    ]
