# Generated by Django 5.1.5 on 2025-02-03 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0009_workspace_onedrive_access_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='onedrive_user_name',
            field=models.CharField(blank=True, default='', help_text='Onedrive OAuth2 access token (mandatory)', max_length=100),
        ),
    ]
