# Generated by Django 5.1.3 on 2025-04-21 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0011_workspace_workspace_search_vector_idx'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='workspace',
            name='workspace_search_vector_idx',
        ),
    ]
