# Generated by Django 5.1.3 on 2025-12-04 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workspaces", "0012_remove_workspace_workspace_search_vector_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="workspace",
            name="enable_bot_builder",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="workspace",
            name="restrict_function_scope",
            field=models.BooleanField(default=False),
        ),
    ]
