# Generated by Django 5.2.10 on 2026-03-10 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workspaces", "0013_workspace_enable_bot_builder_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="workspacemembership",
            name="balance",
            field=models.IntegerField(default=0),
        ),
    ]
