# Generated by Django 5.2.10 on 2026-03-02 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("workspaces", "0013_workspace_enable_bot_builder_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkspaceSeatType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("monthly_charge", models.PositiveIntegerField(default=0)),
                (
                    "monthly_credit_limit",
                    models.PositiveIntegerField(blank=True, default=None, null=True),
                ),
                (
                    "daily_credit_limit",
                    models.PositiveIntegerField(blank=True, default=None, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "indexes": [
                    models.Index(fields=["name"], name="wsst_name_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("name",),
                        name="unique_workspace_seat_type_name",
                    ),
                ],
            },
        ),
        migrations.AddField(
            model_name="workspacemembership",
            name="balance",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="workspacemembership",
            name="seat_type",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="memberships",
                to="workspaces.workspaceseattype",
            ),
        ),
        migrations.AddIndex(
            model_name="workspacemembership",
            index=models.Index(
                fields=["workspace", "seat_type", "deleted"],
                name="wsm_ws_seat_deleted_idx",
            ),
        ),
    ]
