# Generated by Django 5.1.3 on 2026-04-08 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0013_workspace_enable_bot_builder_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='public_by_default',
            field=models.BooleanField(default=False, help_text='[Only for paid team workspaces] Make run links and newly saved workflows publicly viewable by default.'),
        ),
    ]
