# Generated by Django 5.1.3 on 2026-03-05 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workspaces", "0013_workspace_enable_bot_builder_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="workspace",
            name="out_of_credits_email_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
