# Generated by Django 5.2.10 on 2026-03-10 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0014_workspace_public_by_default'),
    ]

    operations = [
        migrations.AddField(
            model_name="workspacemembership",
            name="balance",
            field=models.IntegerField(default=0),
        ),
    ]
