# Generated by Django 5.2.10 on 2026-03-05 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0009_remove_subscription_seats_seattype_subscriptionseat"),
        ("workspaces", "0014_workspaceseattype_and_membership_seat_type"),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                INSERT INTO payments_seattype (
                    id,
                    name,
                    monthly_charge,
                    monthly_credit_limit,
                    is_public,
                    plan,
                    created_at,
                    updated_at
                )
                SELECT
                    id,
                    name,
                    monthly_charge,
                    COALESCE(monthly_credit_limit, 0),
                    TRUE,
                    9,
                    created_at,
                    updated_at
                FROM workspaces_workspaceseattype
                ON CONFLICT (id) DO UPDATE
                SET
                    name = EXCLUDED.name,
                    monthly_charge = EXCLUDED.monthly_charge,
                    monthly_credit_limit = EXCLUDED.monthly_credit_limit,
                    is_public = EXCLUDED.is_public,
                    plan = EXCLUDED.plan,
                    updated_at = EXCLUDED.updated_at;
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AlterField(
            model_name="workspacemembership",
            name="seat_type",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="memberships",
                to="payments.seattype",
            ),
        ),
        migrations.RunSQL(
            sql="""
                SELECT setval(
                    pg_get_serial_sequence('payments_seattype', 'id'),
                    COALESCE((SELECT MAX(id) FROM payments_seattype), 1),
                    TRUE
                );
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.DeleteModel(
            name="WorkspaceSeatType",
        ),
    ]
