# Generated by Django 5.1.3 on 2026-06-05 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workspaces", "0015_workspacemembership_balance"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workspacemembership",
            name="balance",
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
