# Generated by Django 4.2.6 on 2023-10-19 08:43

import bots.custom_fields
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GlossaryResource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "f_url",
                    bots.custom_fields.CustomURLField(max_length=2048, unique=True),
                ),
                ("usage_count", models.IntegerField(default=0)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "glossary_name",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("project_id", models.CharField(default="dara-c1b52", max_length=100)),
                ("location", models.CharField(default="us-central1", max_length=100)),
            ],
            options={
                "ordering": ["usage_count", "last_updated"],
                "indexes": [
                    models.Index(
                        fields=["usage_count", "last_updated"],
                        name="glossary_re_usage_c_d82f17_idx",
                    )
                ],
            },
        ),
    ]
