# Generated by Django 4.2.5 on 2023-09-20 00:54

import bots.custom_fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GlossaryResources",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "f_url",
                    bots.custom_fields.CustomURLField(max_length=2048, unique=True),
                ),
                ("uses", models.IntegerField(default=0)),
                ("last_used", models.DateTimeField(auto_now=True)),
                ("times_locked_for_read", models.IntegerField(default=0)),
            ],
            options={
                "ordering": ["uses", "last_used"],
            },
        ),
    ]
