# Generated by Django 4.2.5 on 2023-09-20 01:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("glossary_resources", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="glossaryresources",
            name="glossary_name",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
