# Generated by Django 4.2.5 on 2023-09-20 03:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("glossary_resources", "0002_glossaryresources_glossary_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="glossaryresources",
            name="times_locked_for_read",
        ),
    ]
