# Generated by Django 4.2 on 2023-05-05 18:02

from django.db import migrations, models
import django.db.models.deletion
import gooeysite.custom_fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BotIntegration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="The name of the bot (for display purposes)",
                        max_length=1024,
                    ),
                ),
                (
                    "app_url",
                    gooeysite.custom_fields.CustomURLField(
                        help_text="The gooey run url / example url / recipe url of the bot",
                        max_length=2048,
                    ),
                ),
                (
                    "billing_account_uid",
                    models.TextField(
                        help_text="The gooey account uid where the credits will be deducted from"
                    ),
                ),
                (
                    "user_language",
                    models.TextField(
                        default="en",
                        help_text="The response language (same as user language in video bots)",
                    ),
                ),
                (
                    "show_feedback_buttons",
                    models.BooleanField(
                        default=False, help_text="Show 👍/👎 buttons with every response"
                    ),
                ),
                (
                    "platform",
                    models.IntegerField(
                        choices=[
                            (1, "Facebook"),
                            (2, "Instagram & FB"),
                            (3, "Whatsapp"),
                        ],
                        db_index=True,
                        help_text="The platform that the bot is integrated with",
                    ),
                ),
                (
                    "fb_page_id",
                    models.TextField(
                        blank=True,
                        default=None,
                        help_text="Bot's Facebook page id (required if platform is Facebook/Instagram)",
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "fb_page_name",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Bot's Facebook page name (only for display)",
                    ),
                ),
                (
                    "fb_page_access_token",
                    models.TextField(
                        blank=True,
                        default="",
                        editable=False,
                        help_text="Bot's Facebook page access token (required if platform is Facebook/Instagram)",
                    ),
                ),
                (
                    "ig_account_id",
                    models.TextField(
                        blank=True,
                        default=None,
                        help_text="Bot's Instagram account id (required if platform is Instagram)",
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "ig_username",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Bot's Instagram username (only for display)",
                    ),
                ),
                (
                    "wa_phone_number",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True,
                        default="",
                        help_text="Bot's WhatsApp phone number (only for display)",
                        max_length=128,
                        region=None,
                    ),
                ),
                (
                    "wa_phone_number_id",
                    models.TextField(
                        blank=True,
                        default=None,
                        help_text="Bot's WhatsApp phone number id (required if platform is WhatsApp)",
                        null=True,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Conversation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fb_page_id",
                    models.TextField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="User's Facebook page id (required if platform is Facebook/Instagram)",
                    ),
                ),
                (
                    "fb_page_name",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="User's Facebook page name (only for display)",
                    ),
                ),
                (
                    "fb_page_access_token",
                    models.TextField(
                        blank=True,
                        default="",
                        editable=False,
                        help_text="User's Facebook page access token (required if platform is Facebook/Instagram)",
                    ),
                ),
                (
                    "ig_account_id",
                    models.TextField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="User's Instagram account id (required if platform is Instagram)",
                    ),
                ),
                (
                    "ig_username",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="User's Instagram username (only for display)",
                    ),
                ),
                (
                    "wa_phone_number",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True,
                        default="",
                        help_text="User's WhatsApp phone number (only for display)",
                        max_length=128,
                        region=None,
                    ),
                ),
                (
                    "wa_phone_number_id",
                    models.TextField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="User's WhatsApp phone number id (required if platform is WhatsApp)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "bot_integration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conversations",
                        to="bots.botintegration",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("user", "User"), ("asisstant", "Asisstant")],
                        max_length=10,
                    ),
                ),
                ("content", models.TextField()),
                (
                    "app_url",
                    gooeysite.custom_fields.CustomURLField(
                        blank=True, default="", editable=False, max_length=2048
                    ),
                ),
                (
                    "wa_msg_id",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="WhatsApp message id (required if platform is WhatsApp)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="bots.conversation",
                    ),
                ),
            ],
            options={
                "ordering": ("created_at",),
            },
        ),
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rating", models.IntegerField(choices=[(1, "👍🏾"), (2, "👎🏾")])),
                ("text", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedbacks",
                        to="bots.message",
                    ),
                ),
            ],
            options={
                "ordering": ("created_at",),
            },
        ),
    ]
