# Generated by Django 4.2 on 2023-04-26 15:52

from django.db import migrations, models
import django.db.models.deletion
import gooeysite.custom_fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Bot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "connected_url",
                    gooeysite.custom_fields.CustomURLField(max_length=2048),
                ),
                ("name", models.CharField(max_length=128)),
                (
                    "ig_account_id",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                (
                    "id_username",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                (
                    "page_access_token",
                    models.CharField(blank=True, default="", max_length=4096),
                ),
                ("page_id", models.CharField(blank=True, default="", max_length=128)),
                (
                    "phone_number",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True, default="", max_length=128, region=None
                    ),
                ),
                ("user_language", models.CharField(max_length=128)),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("fb", "Facebook"),
                            ("wa", "WhatsApp"),
                            ("ig", "Instagram"),
                        ],
                        max_length=4,
                    ),
                ),
                ("show_feedback_buttons", models.BooleanField(default=False)),
                ("billing_uid", models.CharField(max_length=128)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Conversation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.CharField(max_length=128)),
                (
                    "user_phone_number",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True, default="", max_length=128, region=None
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("fb", "Facebook"),
                            ("wa", "WhatsApp"),
                            ("ig", "Instagram"),
                        ],
                        max_length=4,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "bot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conversations",
                        to="bots.bot",
                    ),
                ),
            ],
            options={
                "unique_together": {("bot_id", "user_id")},
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("system", "System"),
                            ("user", "User"),
                            ("asisstant", "Asisstant"),
                        ],
                        max_length=10,
                    ),
                ),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="bots.conversation",
                    ),
                ),
            ],
            options={
                "ordering": ("created_at",),
            },
        ),
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating",
                    models.IntegerField(
                        choices=[(1, "Thumbs Up 👍🏾"), (2, "Thumbs Down 👎🏾")]
                    ),
                ),
                ("text", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedbacks",
                        to="bots.message",
                    ),
                ),
            ],
            options={
                "ordering": ("created_at",),
            },
        ),
    ]
