# Generated by Django 4.2 on 2023-05-05 20:23

from django.db import migrations, models
import django.db.models.deletion
import gooeysite.custom_fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BotIntegration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="The name of the bot (for display purposes)",
                        max_length=1024,
                    ),
                ),
                (
                    "billing_account_uid",
                    models.TextField(
                        db_index=True,
                        help_text="The gooey account uid where the credits will be deducted from",
                    ),
                ),
                (
                    "user_language",
                    models.TextField(
                        default="en",
                        help_text="The response language (same as user language in video bots)",
                    ),
                ),
                (
                    "show_feedback_buttons",
                    models.BooleanField(
                        default=False, help_text="Show 👍/👎 buttons with every response"
                    ),
                ),
                (
                    "platform",
                    models.IntegerField(
                        choices=[
                            (1, "Facebook"),
                            (2, "Instagram & FB"),
                            (3, "Whatsapp"),
                        ],
                        help_text="The platform that the bot is integrated with",
                    ),
                ),
                (
                    "fb_page_id",
                    models.TextField(
                        blank=True,
                        default=None,
                        help_text="Bot's Facebook page id (required if platform is Facebook/Instagram)",
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "fb_page_name",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Bot's Facebook page name (only for display)",
                    ),
                ),
                (
                    "fb_page_access_token",
                    models.TextField(
                        blank=True,
                        default="",
                        editable=False,
                        help_text="Bot's Facebook page access token (required if platform is Facebook/Instagram)",
                    ),
                ),
                (
                    "ig_account_id",
                    models.TextField(
                        blank=True,
                        default=None,
                        help_text="Bot's Instagram account id (required if platform is Instagram)",
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "ig_username",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Bot's Instagram username (only for display)",
                    ),
                ),
                (
                    "wa_phone_number",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True,
                        default="",
                        help_text="Bot's WhatsApp phone number (only for display)",
                        max_length=128,
                        region=None,
                    ),
                ),
                (
                    "wa_phone_number_id",
                    models.TextField(
                        blank=True,
                        default=None,
                        help_text="Bot's WhatsApp phone number id (required if platform is WhatsApp)",
                        null=True,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Conversation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fb_page_id",
                    models.TextField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="User's Facebook page id (required if platform is Facebook/Instagram)",
                    ),
                ),
                (
                    "fb_page_name",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="User's Facebook page name (only for display)",
                    ),
                ),
                (
                    "fb_page_access_token",
                    models.TextField(
                        blank=True,
                        default="",
                        editable=False,
                        help_text="User's Facebook page access token (required if platform is Facebook/Instagram)",
                    ),
                ),
                (
                    "ig_account_id",
                    models.TextField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="User's Instagram account id (required if platform is Instagram)",
                    ),
                ),
                (
                    "ig_username",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="User's Instagram username (only for display)",
                    ),
                ),
                (
                    "wa_phone_number",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True,
                        default="",
                        help_text="User's WhatsApp phone number (only for display)",
                        max_length=128,
                        region=None,
                    ),
                ),
                (
                    "wa_phone_number_id",
                    models.TextField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="User's WhatsApp phone number id (required if platform is WhatsApp)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rating", models.IntegerField(choices=[(1, "👍🏾"), (2, "👎🏾")])),
                ("text", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ("created_at",),
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("user", "User"), ("assistant", "Asisstant")],
                        max_length=10,
                    ),
                ),
                ("content", models.TextField()),
                (
                    "app_url",
                    gooeysite.custom_fields.CustomURLField(
                        blank=True, default="", editable=False, max_length=2048
                    ),
                ),
                (
                    "wa_msg_id",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="WhatsApp message id (required if platform is WhatsApp)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ("created_at",),
                "get_latest_by": "created_at",
            },
        ),
        migrations.CreateModel(
            name="SavedRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "workflow",
                    models.IntegerField(
                        choices=[
                            (1, "DocSearchPage"),
                            (2, "DocSummaryPage"),
                            (3, "GoogleGPTPage"),
                            (4, "VideoBotsPage"),
                            (5, "LipsyncTTSPage"),
                            (6, "TextToSpeechPage"),
                            (7, "AsrPage"),
                            (8, "LipsyncPage"),
                            (9, "DeforumSDPage"),
                            (10, "CompareText2ImgPage"),
                            (11, "Text2AudioPage"),
                            (12, "Img2ImgPage"),
                            (13, "FaceInpaintingPage"),
                            (14, "GoogleImageGenPage"),
                            (15, "CompareUpscalerPage"),
                            (16, "SEOSummaryPage"),
                            (17, "EmailFaceInpaintingPage"),
                            (18, "SocialLookupEmailPage"),
                            (19, "ObjectInpaintingPage"),
                            (20, "ImageSegmentationPage"),
                            (21, "CompareLLMPage"),
                            (22, "ChyronPlantPage"),
                            (23, "LetterWriterPage"),
                        ]
                    ),
                ),
                ("example_id", models.TextField()),
                ("run_id", models.TextField()),
                ("uid", models.TextField()),
            ],
        ),
        migrations.AddIndex(
            model_name="savedrun",
            index=models.Index(
                fields=["workflow", "example_id", "run_id", "uid"],
                name="bots_savedr_workflo_47a100_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="savedrun",
            index=models.Index(
                fields=["workflow"], name="bots_savedr_workflo_87256a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="savedrun",
            index=models.Index(
                fields=["run_id", "uid"], name="bots_savedr_run_id_7b0b34_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="savedrun",
            index=models.Index(
                fields=["example_id"], name="bots_savedr_example_930528_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="savedrun",
            unique_together={("workflow", "example_id", "run_id", "uid")},
        ),
        migrations.AddField(
            model_name="message",
            name="conversation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages",
                to="bots.conversation",
            ),
        ),
        migrations.AddField(
            model_name="feedback",
            name="message",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="feedbacks",
                to="bots.message",
            ),
        ),
        migrations.AddField(
            model_name="conversation",
            name="bot_integration",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="conversations",
                to="bots.botintegration",
            ),
        ),
        migrations.AddField(
            model_name="botintegration",
            name="saved_run",
            field=models.ForeignKey(
                help_text="The saved run that the bot is based on",
                on_delete=django.db.models.deletion.CASCADE,
                to="bots.savedrun",
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["conversation", "-created_at"],
                name="bots_messag_convers_482dd3_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="conversation",
            index=models.Index(
                fields=[
                    "bot_integration",
                    "fb_page_id",
                    "ig_account_id",
                    "wa_phone_number_id",
                ],
                name="bots_conver_bot_int_086ef9_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="botintegration",
            index=models.Index(
                fields=["billing_account_uid", "platform"],
                name="bots_botint_billing_466a86_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="botintegration",
            index=models.Index(
                fields=["fb_page_id", "ig_account_id", "wa_phone_number_id"],
                name="bots_botint_fb_page_7a2a7f_idx",
            ),
        ),
    ]
