# Generated by Django 4.2 on 2023-05-05 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("bots", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="message",
            name="app_url",
        ),
        migrations.AddField(
            model_name="message",
            name="saved_run",
            field=models.ForeignKey(
                blank=True,
                default=None,
                help_text="The saved run that generated this message",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="messages",
                to="bots.savedrun",
            ),
        ),
        migrations.AlterField(
            model_name="botintegration",
            name="saved_run",
            field=models.ForeignKey(
                blank=True,
                default=None,
                help_text="The saved run that the bot is based on",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="botintegrations",
                to="bots.savedrun",
            ),
        ),
        migrations.AlterField(
            model_name="savedrun",
            name="example_id",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="savedrun",
            name="run_id",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="savedrun",
            name="uid",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="savedrun",
            name="workflow",
            field=models.IntegerField(
                choices=[
                    (1, "DocSearchPage"),
                    (2, "DocSummaryPage"),
                    (3, "GoogleGPTPage"),
                    (4, "VideoBotsPage"),
                    (5, "LipsyncTTSPage"),
                    (6, "TextToSpeechPage"),
                    (7, "AsrPage"),
                    (8, "LipsyncPage"),
                    (9, "DeforumSDPage"),
                    (10, "CompareText2ImgPage"),
                    (11, "Text2AudioPage"),
                    (12, "Img2ImgPage"),
                    (13, "FaceInpaintingPage"),
                    (14, "GoogleImageGenPage"),
                    (15, "CompareUpscalerPage"),
                    (16, "SEOSummaryPage"),
                    (17, "EmailFaceInpaintingPage"),
                    (18, "SocialLookupEmailPage"),
                    (19, "ObjectInpaintingPage"),
                    (20, "ImageSegmentationPage"),
                    (21, "CompareLLMPage"),
                    (22, "ChyronPlantPage"),
                    (23, "LetterWriterPage"),
                ],
                default=4,
            ),
        ),
    ]
