# Generated by Django 4.2 on 2023-05-05 18:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bots", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="message",
            options={"get_latest_by": "created_at", "ordering": ("created_at",)},
        ),
        migrations.AlterField(
            model_name="botintegration",
            name="billing_account_uid",
            field=models.TextField(
                db_index=True,
                help_text="The gooey account uid where the credits will be deducted from",
            ),
        ),
        migrations.AlterField(
            model_name="botintegration",
            name="platform",
            field=models.IntegerField(
                choices=[(1, "Facebook"), (2, "Instagram & FB"), (3, "Whatsapp")],
                help_text="The platform that the bot is integrated with",
            ),
        ),
        migrations.AddIndex(
            model_name="botintegration",
            index=models.Index(
                fields=["billing_account_uid", "platform"],
                name="bots_botint_billing_466a86_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="botintegration",
            index=models.Index(
                fields=["fb_page_id", "ig_account_id", "wa_phone_number_id"],
                name="bots_botint_fb_page_7a2a7f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="conversation",
            index=models.Index(
                fields=[
                    "bot_integration",
                    "fb_page_id",
                    "ig_account_id",
                    "wa_phone_number_id",
                ],
                name="bots_conver_bot_int_086ef9_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["conversation", "-created_at"],
                name="bots_messag_convers_482dd3_idx",
            ),
        ),
    ]
