# Generated by Django 4.2 on 2023-04-26 16:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bots", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bot",
            old_name="page_access_token",
            new_name="fb_page_access_token",
        ),
        migrations.RenameField(
            model_name="bot",
            old_name="id_username",
            new_name="fb_page_id",
        ),
        migrations.RenameField(
            model_name="bot",
            old_name="page_id",
            new_name="ig_username",
        ),
        migrations.AlterField(
            model_name="feedback",
            name="rating",
            field=models.IntegerField(choices=[(1, "👍🏾"), (2, "👎🏽")]),
        ),
    ]
