# Generated by Django 4.2 on 2023-04-27 11:16

from django.db import migrations
import gooeysite.custom_fields


class Migration(migrations.Migration):
    dependencies = [
        ("bots", "0003_message_gooey_url_alter_bot_user_language_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="message",
            name="gooey_url",
        ),
        migrations.AddField(
            model_name="message",
            name="run_url",
            field=gooeysite.custom_fields.CustomURLField(
                default=None, editable=False, max_length=2048
            ),
            preserve_default=False,
        ),
    ]
