# Generated by Django 4.2 on 2023-04-27 11:18

from django.db import migrations
import gooeysite.custom_fields


class Migration(migrations.Migration):
    dependencies = [
        ("bots", "0004_remove_message_gooey_url_message_run_url"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bot",
            old_name="connected_url",
            new_name="app_url",
        ),
        migrations.RenameField(
            model_name="bot",
            old_name="phone_number",
            new_name="wa_phone_number",
        ),
        migrations.RemoveField(
            model_name="message",
            name="run_url",
        ),
        migrations.AddField(
            model_name="message",
            name="app_url",
            field=gooeysite.custom_fields.CustomURLField(
                blank=True, default="", editable=False, max_length=2048
            ),
        ),
    ]
