# Generated by Django 4.2 on 2023-05-05 22:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bots", "0004_botintegration_bots_botint_fb_page_7a2a7f_idx"),
    ]

    operations = [
        migrations.AlterField(
            model_name="botintegration",
            name="fb_page_id",
            field=models.CharField(
                blank=True,
                default=None,
                help_text="Bot's Facebook page id (required if platform is Facebook/Instagram)",
                max_length=256,
                null=True,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="botintegration",
            name="ig_account_id",
            field=models.CharField(
                blank=True,
                default=None,
                help_text="Bot's Instagram account id (required if platform is Instagram)",
                max_length=256,
                null=True,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="botintegration",
            name="wa_phone_number_id",
            field=models.CharField(
                blank=True,
                default=None,
                help_text="Bot's WhatsApp phone number id (required if platform is WhatsApp)",
                max_length=256,
                null=True,
                unique=True,
            ),
        ),
    ]
