# Generated by Django 4.2 on 2023-05-06 00:12

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):
    dependencies = [
        ("bots", "0005_alter_botintegration_fb_page_id_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="conversation",
            name="bots_conver_bot_int_086ef9_idx",
        ),
        migrations.RemoveField(
            model_name="conversation",
            name="wa_phone_number_id",
        ),
        migrations.AlterField(
            model_name="conversation",
            name="wa_phone_number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True,
                db_index=True,
                default="",
                help_text="User's WhatsApp phone number (required if platform is WhatsApp)",
                max_length=128,
                region=None,
            ),
        ),
        migrations.AddIndex(
            model_name="conversation",
            index=models.Index(
                fields=[
                    "bot_integration",
                    "fb_page_id",
                    "ig_account_id",
                    "wa_phone_number",
                ],
                name="bots_conver_bot_int_361054_idx",
            ),
        ),
    ]
