# Generated by Django 4.2 on 2023-04-27 11:31

from django.db import migrations, models
import django.db.models.deletion
import gooeysite.custom_fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):
    dependencies = [
        ("bots", "0005_rename_connected_url_bot_app_url_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BotIntegration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("app_url", gooeysite.custom_fields.CustomURLField(max_length=2048)),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("fb", "Facebook"),
                            ("wa", "WhatsApp"),
                            ("ig", "Instagram"),
                        ],
                        max_length=4,
                    ),
                ),
                ("billing_uid", models.CharField(max_length=128)),
                ("user_language", models.CharField(default="en", max_length=128)),
                ("show_feedback_buttons", models.BooleanField(default=False)),
                (
                    "wa_phone_number",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True, default="", max_length=128, region=None
                    ),
                ),
                (
                    "fb_page_access_token",
                    models.CharField(blank=True, default="", max_length=4096),
                ),
                (
                    "fb_page_id",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                (
                    "ig_account_id",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                (
                    "ig_username",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name="conversation",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="conversation",
            name="bot",
        ),
        migrations.AddField(
            model_name="conversation",
            name="bot_integration",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="conversations",
                to="bots.botintegration",
            ),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="Bot",
        ),
    ]
