# Generated by Django 4.2 on 2023-05-17 16:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bots", "0006_remove_conversation_bots_conver_bot_int_086ef9_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="display_content",
            field=models.TextField(
                blank=True,
                help_text="The content that's actually displayed to the user",
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="content",
            field=models.TextField(help_text="The content that the AI sees"),
        ),
        migrations.AlterField(
            model_name="savedrun",
            name="workflow",
            field=models.IntegerField(
                choices=[
                    (1, "doc-search"),
                    (2, "doc-summary"),
                    (3, "google-gpt"),
                    (4, "video-bots"),
                    (5, "LipsyncTTS"),
                    (6, "TextToSpeech"),
                    (7, "asr"),
                    (8, "Lipsync"),
                    (9, "DeforumSD"),
                    (10, "CompareText2Img"),
                    (11, "text2audio"),
                    (12, "Img2Img"),
                    (13, "FaceInpainting"),
                    (14, "GoogleImageGen"),
                    (15, "compare-ai-upscalers"),
                    (16, "SEOSummary"),
                    (17, "EmailFaceInpainting"),
                    (18, "SocialLookupEmail"),
                    (19, "ObjectInpainting"),
                    (20, "ImageSegmentation"),
                    (21, "CompareLLM"),
                    (22, "ChyronPlant"),
                    (23, "LetterWriter"),
                    (24, "SmartGPT"),
                ],
                default=4,
            ),
        ),
    ]
