# Generated by Django 4.2 on 2023-04-27 11:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bots", "0006_botintegration_alter_conversation_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="conversation",
            unique_together={("bot_integration", "user_id")},
        ),
    ]
