# Generated by Django 4.2 on 2023-05-17 16:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bots", "0007_message_display_content_alter_message_content_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="message",
            options={"get_latest_by": "created_at", "ordering": ("-created_at",)},
        ),
    ]
