# Generated by Django 4.2 on 2023-04-27 12:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bots", "0007_alter_conversation_unique_together"),
    ]

    operations = [
        migrations.RenameField(
            model_name="botintegration",
            old_name="billing_uid",
            new_name="billing_account_uid",
        ),
        migrations.AlterField(
            model_name="botintegration",
            name="platform",
            field=models.IntegerField(
                choices=[(1, "Facebook"), (2, "Instagram"), (3, "Whatsapp")]
            ),
        ),
        migrations.AlterField(
            model_name="conversation",
            name="platform",
            field=models.IntegerField(
                choices=[(1, "Facebook"), (2, "Instagram"), (3, "Whatsapp")]
            ),
        ),
    ]
