# Generated by Django 4.2 on 2023-04-27 16:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bots", "0008_rename_billing_uid_botintegration_billing_account_uid_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="botintegration",
            name="fb_page_name",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="botintegration",
            name="billing_account_uid",
            field=models.CharField(db_index=True, max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name="botintegration",
            name="fb_page_id",
            field=models.CharField(
                blank=True, db_index=True, default=None, max_length=128, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="botintegration",
            name="ig_account_id",
            field=models.CharField(
                blank=True, db_index=True, default=None, max_length=128, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="botintegration",
            name="platform",
            field=models.IntegerField(
                choices=[(1, "Facebook"), (2, "Instagram"), (3, "Whatsapp")],
                db_index=True,
            ),
        ),
    ]
