# Generated by Django 4.2 on 2023-05-18 23:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bots", "0008_alter_message_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="feedback",
            options={"get_latest_by": "created_at", "ordering": ("-created_at",)},
        ),
        migrations.AddField(
            model_name="conversation",
            name="state",
            field=models.IntegerField(
                choices=[
                    (0, "Initial"),
                    (1, "Ask for feedback (👍)"),
                    (2, "Ask for feedback (👎)"),
                ],
                default=0,
            ),
        ),
    ]
