# Generated by Django 4.2 on 2023-04-27 18:57

from django.db import migrations, models
import gooeysite.custom_fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):
    dependencies = [
        ("bots", "0009_botintegration_fb_page_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="botintegration",
            name="wa_phone_number_id",
            field=models.TextField(
                blank=True,
                default=None,
                help_text="Connected WhatsApp phone number id (required if platform is WhatsApp)",
                null=True,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="botintegration",
            name="app_url",
            field=gooeysite.custom_fields.CustomURLField(
                help_text="The gooey run url / example url / recipe url for the bot",
                max_length=2048,
            ),
        ),
        migrations.AlterField(
            model_name="botintegration",
            name="billing_account_uid",
            field=models.TextField(
                help_text="The gooey account uid where the credits will be deducted from",
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="botintegration",
            name="fb_page_access_token",
            field=models.TextField(
                blank=True,
                default="",
                editable=False,
                help_text="Connected Facebook page access token (required if platform is Facebook/Instagram)",
            ),
        ),
        migrations.AlterField(
            model_name="botintegration",
            name="fb_page_id",
            field=models.TextField(
                blank=True,
                db_index=True,
                default=None,
                help_text="Connected Facebook page id (required if platform is Facebook/Instagram)",
            ),
        ),
        migrations.AlterField(
            model_name="botintegration",
            name="fb_page_name",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Connected Facebook page name (only for display)",
            ),
        ),
        migrations.AlterField(
            model_name="botintegration",
            name="ig_account_id",
            field=models.TextField(
                blank=True,
                db_index=True,
                default=None,
                help_text="Connected Instagram account id (required if platform is Instagram)",
            ),
        ),
        migrations.AlterField(
            model_name="botintegration",
            name="ig_username",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Connected Instagram username (only for display)",
            ),
        ),
        migrations.AlterField(
            model_name="botintegration",
            name="name",
            field=models.CharField(
                help_text="The name of the bot (for display purposes)", max_length=1024
            ),
        ),
        migrations.AlterField(
            model_name="botintegration",
            name="platform",
            field=models.IntegerField(
                choices=[(1, "Facebook"), (2, "Instagram"), (3, "Whatsapp")],
                db_index=True,
                help_text="The platform that the bot is integrated with",
            ),
        ),
        migrations.AlterField(
            model_name="botintegration",
            name="show_feedback_buttons",
            field=models.BooleanField(
                default=False, help_text="Show 👍/👎 buttons with every message response"
            ),
        ),
        migrations.AlterField(
            model_name="botintegration",
            name="user_language",
            field=models.TextField(
                default="en",
                help_text="The response language (same as user language in video bots)",
            ),
        ),
        migrations.AlterField(
            model_name="botintegration",
            name="wa_phone_number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True,
                default="",
                help_text="Connected WhatsApp phone number (only for display)",
                max_length=128,
                region=None,
            ),
        ),
    ]
