# Generated by Django 4.2 on 2023-04-27 20:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bots", "0011_alter_conversation_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="botintegration",
            name="billing_account_uid",
            field=models.TextField(
                help_text="The gooey account uid where the credits will be deducted from"
            ),
        ),
    ]
