# Generated by Django 4.2 on 2023-05-25 11:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bots", "0011_feedbackcomment"),
    ]

    operations = [
        migrations.AddField(
            model_name="feedback",
            name="creator",
            field=models.IntegerField(
                choices=[
                    (1, "Unspecified"),
                    (2, "User"),
                    (3, "Farmer"),
                    (4, "Agent"),
                    (5, "Admin"),
                    (6, "Gooey team member"),
                ],
                default=1,
            ),
        ),
    ]
