# Generated by Django 4.2 on 2023-05-25 11:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bots", "0012_feedback_creator"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feedback",
            name="status",
            field=models.IntegerField(
                choices=[
                    (1, "Untriaged"),
                    (2, "Test"),
                    (3, "Needs investigation"),
                    (4, "Resolved"),
                ],
                default=1,
                max_length=20,
            ),
        ),
    ]
