# Generated by Django 4.2 on 2023-05-29 16:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bots", "0014_alter_feedback_status"),
    ]

    operations = [
        migrations.RenameField(
            model_name="feedbackcomment",
            old_name="user",
            new_name="author",
        ),
    ]
