# Generated by Django 4.2.1 on 2023-06-13 15:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bots", "0016_alter_feedback_text_alter_feedback_text_english"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="display_content",
            field=models.TextField(
                blank=True,
                help_text="The local language content that's actually displayed to the user",
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="role",
            field=models.CharField(
                choices=[("user", "User"), ("assistant", "Bot")], max_length=10
            ),
        ),
    ]
