# Generated by Django 4.2.1 on 2023-07-03 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("bots", "0017_alter_message_display_content_alter_message_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="speech_run",
            field=models.ForeignKey(
                blank=True,
                default=None,
                help_text="The saved audio run the generated this message",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="messages_speech",
                to="bots.savedrun",
            ),
        ),
    ]
