# Generated by Django 4.2.1 on 2023-06-19 17:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bots", "0017_alter_message_display_content_alter_message_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="question_answered",
            field=models.TextField(
                blank=True, help_text="Bot's ability to answer question"
            ),
        ),
    ]
