# Generated by Django 4.2.2 on 2023-07-10 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("bots", "0017_alter_message_display_content_alter_message_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="savedrun",
            name="workflow",
            field=models.IntegerField(
                choices=[
                    (1, "doc-search"),
                    (2, "doc-summary"),
                    (3, "google-gpt"),
                    (4, "video-bots"),
                    (5, "LipsyncTTS"),
                    (6, "TextToSpeech"),
                    (7, "asr"),
                    (8, "Lipsync"),
                    (9, "DeforumSD"),
                    (10, "CompareText2Img"),
                    (11, "text2audio"),
                    (12, "Img2Img"),
                    (13, "FaceInpainting"),
                    (14, "GoogleImageGen"),
                    (15, "compare-ai-upscalers"),
                    (16, "SEOSummary"),
                    (17, "EmailFaceInpainting"),
                    (18, "SocialLookupEmail"),
                    (19, "ObjectInpainting"),
                    (20, "ImageSegmentation"),
                    (21, "CompareLLM"),
                    (22, "ChyronPlant"),
                    (23, "LetterWriter"),
                    (24, "SmartGPT"),
                    (25, "QRCodeGenerator"),
                ],
                default=4,
            ),
        ),
        migrations.CreateModel(
            name="ShortenedURLs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField()),
                ("shortened_guid", models.CharField(max_length=10, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("clicks", models.IntegerField(default=0)),
                ("max_clicks", models.IntegerField(default=-1)),
                ("disabled", models.BooleanField(default=False)),
                (
                    "run",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        help_text="The saved run that generated this shortened url",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="shortened_urls",
                        to="bots.savedrun",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "get_latest_by": "created_at",
            },
        ),
    ]
