# Generated by Django 4.2.1 on 2023-06-27 20:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bots", "0019_alter_message_question_answered"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="question_subject",
            field=models.TextField(
                blank=True, default="", help_text="Subject of given question"
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="question_answered",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Bot's ability to answer given question",
            ),
        ),
    ]
