# Generated by Django 4.2.1 on 2023-06-28 17:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bots", "0020_message_question_subject_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="botintegration",
            name="analysis_url",
            field=models.TextField(
                blank=True,
                default="",
                help_text="The analysis copilot that the bot uses to categorize responses",
            ),
        ),
    ]
