# Generated by Django 4.2.1 on 2023-06-29 20:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bots", "0021_botintegration_analysis_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="speech_run",
            field=models.TextField(
                blank=True,
                default=None,
                help_text="The saved audio run that generated this message",
                null=True,
            ),
        ),
    ]
