# Generated by Django 4.2.1 on 2023-07-10 11:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bots", "0021_botintegration_analysis_url"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="botintegration",
            name="analysis_url",
        ),
        migrations.AddField(
            model_name="botintegration",
            name="enable_analysis",
            field=models.BooleanField(
                default=False, help_text="Enable analysis for this bot"
            ),
        ),
    ]
