# Generated by Django 4.2.1 on 2023-07-14 11:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bots", "0022_remove_botintegration_analysis_url_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="savedrun",
            name="workflow",
            field=models.IntegerField(
                choices=[
                    (1, "doc-search"),
                    (2, "doc-summary"),
                    (3, "google-gpt"),
                    (4, "video-bots"),
                    (5, "LipsyncTTS"),
                    (6, "TextToSpeech"),
                    (7, "asr"),
                    (8, "Lipsync"),
                    (9, "DeforumSD"),
                    (10, "CompareText2Img"),
                    (11, "text2audio"),
                    (12, "Img2Img"),
                    (13, "FaceInpainting"),
                    (14, "GoogleImageGen"),
                    (15, "compare-ai-upscalers"),
                    (16, "SEOSummary"),
                    (17, "EmailFaceInpainting"),
                    (18, "SocialLookupEmail"),
                    (19, "ObjectInpainting"),
                    (20, "ImageSegmentation"),
                    (21, "CompareLLM"),
                    (22, "ChyronPlant"),
                    (23, "LetterWriter"),
                    (24, "SmartGPT"),
                    (25, "QRCodeGenerator"),
                ],
                default=4,
            ),
        ),
    ]
