# Generated by Django 4.2.3 on 2023-07-31 00:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bots", "0023_alter_savedrun_workflow"),
    ]

    operations = [
        migrations.AddField(
            model_name="botintegration",
            name="slack_channel_id",
            field=models.CharField(
                blank=True,
                default=None,
                help_text="Bot's Slack channel id (required if platform is Slack)",
                max_length=256,
                null=True,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="conversation",
            name="slack_user_id",
            field=models.TextField(
                blank=True,
                db_index=True,
                default="",
                help_text="User's Slack channel id (required if platform is Slack)",
            ),
        ),
        migrations.AlterField(
            model_name="botintegration",
            name="platform",
            field=models.IntegerField(
                choices=[
                    (1, "Facebook"),
                    (2, "Instagram & FB"),
                    (3, "Whatsapp"),
                    (4, "Slack"),
                ],
                help_text="The platform that the bot is integrated with",
            ),
        ),
    ]
