# Generated by Django 4.2.3 on 2023-08-01 06:55

import bots.custom_fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bots", "0023_alter_savedrun_workflow"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="savedrun",
            options={"ordering": ["-updated_at"]},
        ),
        migrations.RemoveIndex(
            model_name="botintegration",
            name="bots_botint_fb_page_7a2a7f_idx",
        ),
        migrations.AlterUniqueTogether(
            name="savedrun",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="botintegration",
            name="slack_access_token",
            field=models.TextField(
                blank=True,
                default="",
                editable=False,
                help_text="Bot's Slack access token (required if platform is Slack)",
            ),
        ),
        migrations.AddField(
            model_name="botintegration",
            name="slack_channel_hook_url",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Bot's Slack channel hook url (required if platform is Slack)",
            ),
        ),
        migrations.AddField(
            model_name="botintegration",
            name="slack_channel_id",
            field=models.CharField(
                blank=True,
                default=None,
                help_text="Bot's Slack channel id (required if platform is Slack)",
                max_length=256,
                null=True,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="conversation",
            name="slack_user_id",
            field=models.TextField(
                blank=True,
                db_index=True,
                default="",
                help_text="User's Slack channel id (required if platform is Slack)",
            ),
        ),
        migrations.AddField(
            model_name="savedrun",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default="2023-07-31 00:00"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="savedrun",
            name="error_msg",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="savedrun",
            name="hidden",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="savedrun",
            name="is_flagged",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="savedrun",
            name="page_notes",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="savedrun",
            name="page_title",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="savedrun",
            name="run_status",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="savedrun",
            name="run_time",
            field=models.DurationField(blank=True, default=datetime.timedelta),
        ),
        migrations.AddField(
            model_name="savedrun",
            name="state",
            field=models.JSONField(
                blank=True, default=dict, encoder=bots.custom_fields.PostgresJSONEncoder
            ),
        ),
        migrations.AddField(
            model_name="savedrun",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="botintegration",
            name="platform",
            field=models.IntegerField(
                choices=[
                    (1, "Facebook"),
                    (2, "Instagram & FB"),
                    (3, "Whatsapp"),
                    (4, "Slack"),
                ],
                help_text="The platform that the bot is integrated with",
            ),
        ),
        migrations.AlterField(
            model_name="savedrun",
            name="example_id",
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="savedrun",
            name="run_id",
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="savedrun",
            name="uid",
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="savedrun",
            name="workflow",
            field=models.IntegerField(
                choices=[
                    (1, "doc-search"),
                    (2, "doc-summary"),
                    (3, "google-gpt"),
                    (4, "video-bots"),
                    (5, "LipsyncTTS"),
                    (6, "TextToSpeech"),
                    (7, "asr"),
                    (8, "Lipsync"),
                    (9, "DeforumSD"),
                    (10, "CompareText2Img"),
                    (11, "text2audio"),
                    (12, "Img2Img"),
                    (13, "FaceInpainting#2"),
                    (14, "GoogleImageGen"),
                    (15, "compare-ai-upscalers"),
                    (16, "SEOSummary"),
                    (17, "EmailFaceInpainting#2"),
                    (18, "SocialLookupEmail"),
                    (19, "ObjectInpainting"),
                    (20, "ImageSegmentation#2"),
                    (21, "CompareLLM"),
                    (22, "ChyronPlant"),
                    (23, "LetterWriter"),
                    (24, "SmartGPT"),
                    (25, "art-qr-code"),
                    (26, "doc-extract"),
                    (27, "related-qna-maker"),
                    (28, "related-qna-maker-doc"),
                    (29, "embeddings"),
                ],
                default=4,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="savedrun",
            unique_together={("workflow", "run_id", "uid"), ("workflow", "example_id")},
        ),
        migrations.AddIndex(
            model_name="botintegration",
            index=models.Index(
                fields=[
                    "fb_page_id",
                    "ig_account_id",
                    "wa_phone_number_id",
                    "slack_channel_id",
                ],
                name="bots_botint_fb_page_62b88c_idx",
            ),
        ),
    ]
