# Generated by Django 4.2.2 on 2023-07-26 19:47

import bots.custom_fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bots", "0023_alter_savedrun_workflow"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="savedrun",
            options={"ordering": ["-updated_at"]},
        ),
        migrations.AddField(
            model_name="savedrun",
            name="created_at",
            field=models.DateTimeField(default=datetime.datetime(1970, 1, 1, 0, 0)),
        ),
        migrations.AddField(
            model_name="savedrun",
            name="error_msg",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="savedrun",
            name="hidden",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="savedrun",
            name="is_flagged",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="savedrun",
            name="page_notes",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="savedrun",
            name="page_title",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="savedrun",
            name="run_status",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="savedrun",
            name="run_time",
            field=models.DurationField(blank=True, default=datetime.timedelta),
        ),
        migrations.AddField(
            model_name="savedrun",
            name="state",
            field=models.JSONField(
                blank=True, default=dict, encoder=bots.custom_fields.PostgresJSONEncoder
            ),
        ),
        migrations.AddField(
            model_name="savedrun",
            name="updated_at",
            field=models.DateTimeField(default=datetime.datetime(1970, 1, 1, 0, 0)),
        ),
        migrations.AlterField(
            model_name="savedrun",
            name="workflow",
            field=models.IntegerField(
                choices=[
                    (1, "doc-search"),
                    (2, "doc-summary"),
                    (3, "google-gpt"),
                    (4, "video-bots"),
                    (5, "LipsyncTTS"),
                    (6, "TextToSpeech"),
                    (7, "asr"),
                    (8, "Lipsync"),
                    (9, "DeforumSD"),
                    (10, "CompareText2Img"),
                    (11, "text2audio"),
                    (12, "Img2Img"),
                    (13, "FaceInpainting#2"),
                    (14, "GoogleImageGen"),
                    (15, "compare-ai-upscalers"),
                    (16, "SEOSummary"),
                    (17, "EmailFaceInpainting#2"),
                    (18, "SocialLookupEmail"),
                    (19, "ObjectInpainting"),
                    (20, "ImageSegmentation#2"),
                    (21, "CompareLLM"),
                    (22, "ChyronPlant"),
                    (23, "LetterWriter"),
                    (24, "SmartGPT"),
                    (25, "art-qr-code"),
                    (26, "doc-extract"),
                    (27, "related-qna-maker"),
                    (28, "related-qna-maker-doc"),
                    (29, "embeddings"),
                ],
                default=4,
            ),
        ),
    ]
