# Generated by Django 4.2.3 on 2023-07-31 00:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bots", "0024_botintegration_slack_channel_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="botintegration",
            name="slack_access_token",
            field=models.TextField(
                blank=True,
                default="",
                editable=False,
                help_text="Bot's Slack access token (required if platform is Slack)",
            ),
        ),
    ]
