# Generated by Django 4.2.2 on 2023-07-26 19:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bots", "0024_alter_savedrun_options_savedrun_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="savedrun",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="savedrun",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
