# Generated by Django 4.2.3 on 2023-07-31 02:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bots", "0025_botintegration_slack_access_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="botintegration",
            name="slack_channel_hook_url",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Bot's Slack channel hook url (required if platform is Slack)",
            ),
        ),
    ]
