# Generated by Django 4.2.3 on 2023-07-27 20:24

from django.db import migrations
from django.db.models import Q


def forwards_func(apps, schema_editor):
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    SavedRun = apps.get_model("bots", "SavedRun")
    db_alias = schema_editor.connection.alias
    objects = SavedRun.objects.using(db_alias)

    # Remove empty strings before we add the unique constraint
    objects.filter(example_id="").update(example_id=None)
    objects.filter(run_id="").update(run_id=None)
    objects.filter(uid="").update(uid=None)

    # Remove duplicates
    objects.exclude(
        Q(example_id__isnull=True) | Q(run_id__isnull=True) | Q(uid__isnull=True),
    ).update(example_id=None)


class Migration(migrations.Migration):
    dependencies = [
        ("bots", "0026_alter_savedrun_unique_together_and_more"),
    ]

    operations = [
        migrations.RunPython(forwards_func),
        migrations.AlterUniqueTogether(
            name="savedrun",
            unique_together={("workflow", "example_id"), ("workflow", "run_id", "uid")},
        ),
    ]
