# Generated by Django 4.2.3 on 2023-07-28 17:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("bots", "0027_alter_savedrun_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="savedrun",
            name="updated_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
