# Generated by Django 4.2.3 on 2023-07-28 19:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bots", "0028_alter_savedrun_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="savedrun",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
