# Generated by Django 4.2.3 on 2023-08-03 18:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bots", "0029_alter_savedrun_updated_at"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="botintegration",
            name="bots_botint_fb_page_7a2a7f_idx",
        ),
        migrations.RemoveIndex(
            model_name="conversation",
            name="bots_conver_bot_int_361054_idx",
        ),
        migrations.RemoveIndex(
            model_name="savedrun",
            name="bots_savedr_run_id_7b0b34_idx",
        ),
        migrations.RemoveIndex(
            model_name="savedrun",
            name="bots_savedr_example_930528_idx",
        ),
        migrations.AddField(
            model_name="botintegration",
            name="slack_access_token",
            field=models.TextField(
                blank=True,
                default="",
                editable=False,
                help_text="Bot's Slack access token (required if platform is Slack)",
            ),
        ),
        migrations.AddField(
            model_name="botintegration",
            name="slack_channel_hook_url",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Bot's Slack channel hook url (required if platform is Slack)",
            ),
        ),
        migrations.AddField(
            model_name="botintegration",
            name="slack_channel_id",
            field=models.CharField(
                blank=True,
                default=None,
                help_text="Bot's Slack channel id (required if platform is Slack)",
                max_length=256,
                null=True,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="conversation",
            name="slack_user_id",
            field=models.TextField(
                blank=True,
                db_index=True,
                default="",
                help_text="User's Slack ID (required if platform is Slack)",
            ),
        ),
        migrations.AlterField(
            model_name="botintegration",
            name="platform",
            field=models.IntegerField(
                choices=[
                    (1, "Facebook"),
                    (2, "Instagram & FB"),
                    (3, "Whatsapp"),
                    (4, "Slack"),
                ],
                help_text="The platform that the bot is integrated with",
            ),
        ),
        migrations.AddIndex(
            model_name="botintegration",
            index=models.Index(
                fields=["fb_page_id", "ig_account_id"],
                name="bots_botint_fb_page_14ca33_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="conversation",
            index=models.Index(
                fields=["bot_integration", "fb_page_id", "ig_account_id"],
                name="bots_conver_bot_int_d9a1d1_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="conversation",
            index=models.Index(
                fields=["bot_integration", "wa_phone_number"],
                name="bots_conver_bot_int_b2a62e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="conversation",
            index=models.Index(
                fields=["bot_integration", "slack_user_id"],
                name="bots_conver_bot_int_a83907_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="savedrun",
            index=models.Index(
                fields=["workflow", "run_id", "uid"],
                name="bots_savedr_workflo_ab9b6d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="savedrun",
            index=models.Index(
                fields=["workflow", "example_id", "hidden"],
                name="bots_savedr_workflo_19c1a2_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="savedrun",
            index=models.Index(
                fields=["workflow", "uid", "updated_at"],
                name="bots_savedr_workflo_aa2d32_idx",
            ),
        ),
    ]
