# Generated by Django 4.2.3 on 2023-08-23 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("bots", "0030_remove_botintegration_bots_botint_fb_page_7a2a7f_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="botintegration",
            name="analysis_run",
            field=models.ForeignKey(
                blank=True,
                default=None,
                help_text="The analysis run that the bot will run",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="analysis_run_botintegrations",
                to="bots.savedrun",
            ),
        ),
        migrations.AlterField(
            model_name="botintegration",
            name="saved_run",
            field=models.ForeignKey(
                blank=True,
                default=None,
                help_text="The saved run that the bot is based on",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="saved_run_botintegrations",
                to="bots.savedrun",
            ),
        ),
    ]
