# Generated by Django 4.2.3 on 2023-08-23 15:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bots", "0031_botintegration_analysis_run_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="analysis_data",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="JSON data that is captured from analysis",
                null=True,
            ),
        ),
    ]
