# Generated by Django 4.2.3 on 2023-08-23 22:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bots", "0033_alter_message_analysis_run"),
    ]

    operations = [
        migrations.AlterField(
            model_name="savedrun",
            name="example_id",
            field=models.CharField(blank=True, default=None, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name="savedrun",
            name="run_id",
            field=models.CharField(blank=True, default=None, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name="savedrun",
            name="uid",
            field=models.CharField(blank=True, default=None, max_length=128, null=True),
        ),
    ]
