# Generated by Django 4.2.3 on 2023-08-24 00:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("bots", "0035_alter_botintegration_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="savedrun",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="children",
                to="bots.savedrun",
            ),
        ),
        migrations.AlterField(
            model_name="botintegration",
            name="analysis_run",
            field=models.ForeignKey(
                blank=True,
                default=None,
                help_text="If provided, the message content will be analyzed for this bot using this saved run",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="analysis_botintegrations",
                to="bots.savedrun",
            ),
        ),
        migrations.AlterField(
            model_name="savedrun",
            name="workflow",
            field=models.IntegerField(
                choices=[
                    (1, "Doc Search"),
                    (2, "Doc Summary"),
                    (3, "Google GPT"),
                    (4, "Copilot"),
                    (5, "Lipysnc + TTS"),
                    (6, "Text to Speech"),
                    (7, "Speech Recognition"),
                    (8, "Lipsync"),
                    (9, "Deforum Animation"),
                    (10, "Compare Text2Img"),
                    (11, "Text2Audio"),
                    (12, "Img2Img"),
                    (13, "Face Inpainting"),
                    (14, "Google Image Gen"),
                    (15, "Comapre AI Upscalers"),
                    (16, "SEO Summary"),
                    (17, "Email Face Inpainting"),
                    (18, "Social Lookup Email"),
                    (19, "Object Inpainting"),
                    (20, "Image Segmentation"),
                    (21, "Compare LLM"),
                    (22, "Chyron Plant"),
                    (23, "Letter Writer"),
                    (24, "Smart GPT"),
                    (25, "AI QR Code"),
                    (26, "Doc Extract"),
                    (27, "Related QnA Maker"),
                    (28, "Related QnA Maker Doc"),
                    (29, "Embeddings"),
                ],
                default=4,
            ),
        ),
    ]
