# Generated by Django 4.2.3 on 2023-08-29 08:13

from django.db import migrations, models


def forwards_func(apps, schema_editor):
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    SavedRun = apps.get_model("bots", "SavedRun")
    db_alias = schema_editor.connection.alias
    objects = SavedRun.objects.using(db_alias)

    # remove parent = self
    objects.filter(parent=models.F("id")).update(parent=None)


class Migration(migrations.Migration):
    dependencies = [
        ("bots", "0036_savedrun_parent_alter_botintegration_analysis_run_and_more"),
    ]

    operations = [
        migrations.RunPython(forwards_func),
        migrations.AddConstraint(
            model_name="savedrun",
            constraint=models.CheckConstraint(
                check=models.Q(("parent", models.F("id")), _negated=True),
                name="parent_not_self",
            ),
        ),
    ]
