# Generated by Django 4.2.5 on 2023-09-12 23:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bots", "0037_savedrun_parent_not_self"),
    ]

    operations = [
        migrations.AddField(
            model_name="botintegration",
            name="slack_team_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Bot's Slack team id (required if platform is Slack)",
                max_length=256,
            ),
        ),
    ]
