# Generated by Django 4.2.3 on 2023-09-13 15:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bots", "0037_savedrun_parent_not_self"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="botintegration",
            name="enable_analysis",
        ),
    ]
