# Generated by Django 4.2.5 on 2023-09-14 15:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bots", "0038_remove_botintegration_enable_analysis"),
    ]

    operations = [
        migrations.AddField(
            model_name="botintegration",
            name="slack_read_receipt_msg",
            field=models.TextField(
                blank=True,
                default="Results may take up to 1 minute, we appreciate your patience.",
                help_text="Bot's Slack read receipt message - if set, and platform is Slack, the bot will send this message to mark the user message as read and then delete it when it has a response ready",
            ),
        ),
    ]
