# Generated by Django 4.2.5 on 2023-09-14 15:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bots", "0039_botintegration_slack_read_receipt_msg"),
    ]

    operations = [
        migrations.AddField(
            model_name="botintegration",
            name="slack_channel_name",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Bot's Slack channel name (only for display, required if platform is Slack)",
            ),
        ),
        migrations.AddField(
            model_name="botintegration",
            name="slack_team_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Bot's Slack team id (required if platform is Slack)",
                max_length=256,
            ),
        ),
        migrations.AddField(
            model_name="botintegration",
            name="slack_team_name",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Bot's Slack team/workspace name (only for display, required if platform is Slack)",
            ),
        ),
    ]
