# Generated by Django 4.2.3 on 2023-09-19 12:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bots", "0040_remove_conversation_bots_conver_bot_int_a83907_idx_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="botintegration",
            name="slack_create_personal_channels",
            field=models.BooleanField(
                default=True,
                help_text="If set, the bot will create a personal channel for each user in the public channel",
            ),
        ),
    ]
