# Generated by Django 4.2.3 on 2023-09-19 20:51

from django.db import migrations, models


def forwards_func(apps, schema_editor):
    Message = apps.get_model("bots", "Message")
    db_alias = schema_editor.connection.alias
    objects = Message.objects.using(db_alias)
    objects.filter(platform_msg_id="").update(platform_msg_id=None)


class Migration(migrations.Migration):
    dependencies = [
        ("bots", "0041_alter_botintegration_slack_create_personal_channels"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="platform_msg_id",
            field=models.TextField(
                blank=True,
                default=None,
                help_text="The platform's delivered message id",
                null=True,
            ),
        ),
        migrations.RunPython(forwards_func),
        migrations.AlterField(
            model_name="message",
            name="platform_msg_id",
            field=models.TextField(
                blank=True,
                default=None,
                help_text="The platform's delivered message id",
                null=True,
                unique=True,
            ),
        ),
    ]
