# Generated by Django 4.2.5 on 2023-10-13 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("app_users", "0008_appusertransaction"),
        ("bots", "0044_savedrun_price_alter_savedrun_workflow"),
    ]

    operations = [
        migrations.AddField(
            model_name="savedrun",
            name="transaction",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="saved_runs",
                to="app_users.appusertransaction",
            ),
        ),
    ]
