# Generated by Django 4.2.5 on 2023-11-22 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("files", "0001_initial"),
        ("bots", "0046_savedrun_bots_savedr_created_cb8e09_idx_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MessageAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.AlterModelOptions(
            name="feedback",
            options={"get_latest_by": "created_at", "ordering": ["-created_at"]},
        ),
        migrations.AddIndex(
            model_name="feedback",
            index=models.Index(
                fields=["-created_at"], name="bots_feedba_created_fbd16a_idx"
            ),
        ),
        migrations.AddField(
            model_name="messageattachment",
            name="message",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attachments",
                to="bots.message",
            ),
        ),
        migrations.AddField(
            model_name="messageattachment",
            name="metadata",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="message_attachments",
                to="files.filemetadata",
            ),
        ),
    ]
