# Generated by Django 4.2.5 on 2023-11-27 15:26

from django.db import migrations, models
import django.db.models.deletion

from bots.models import PublishedRunVisibility


def set_defaults_for_gooey_examples(apps, schema_editor):
    # bots->SavedRun
    # if example_id is not null,
    # set is_approved_example to True and visibility to Public
    model = apps.get_model("bots", "SavedRun")
    db_alias = schema_editor.connection.alias

    model.objects.using(db_alias).filter(example_id__isnull=False).update(
        is_approved_example=True,
        visibility=PublishedRunVisibility.PUBLIC,
    )


class Migration(migrations.Migration):
    dependencies = [
        ("app_users", "0010_alter_appuser_balance_alter_appuser_created_at_and_more"),
        ("bots", "0046_savedrun_bots_savedr_created_cb8e09_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="savedrun",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="examples_created",
                to="app_users.appuser",
            ),
        ),
        migrations.AddField(
            model_name="savedrun",
            name="is_approved_example",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="savedrun",
            name="visibility",
            field=models.IntegerField(
                choices=[(1, "Unlisted"), (2, "Public")], default=1
            ),
        ),
        migrations.RunPython(
            set_defaults_for_gooey_examples,
        ),
    ]
