# Generated by Django 4.2.7 on 2023-11-30 21:02

from django.db import migrations, models
import django.db.models.deletion

from bots.models import PublishedRunVisibility


def forwards_func(apps, schema_editor):
    # if example_id is not null, create published run with
    # is_approved_example to True and visibility to Public
    savedrun_model = apps.get_model("bots", "SavedRun")
    publishedrun_model = apps.get_model("bots", "PublishedRun")
    db_alias = schema_editor.connection.alias

    for savedrun in savedrun_model.objects.using(db_alias).filter(
        example_id__isnull=False,
    ):
        publishedrun_model.objects.create(
            workflow=savedrun.workflow,
            published_run_id=savedrun.example_id,
            title=savedrun.page_title,
            notes=savedrun.page_notes,
            saved_run=savedrun,
            created_by=None,  # TODO: use gooey-support user
            last_edited_by=None,  # TODO: use gooey-support user
            visibility=PublishedRunVisibility.PUBLIC,
            is_approved_example=True,
        )
    for savedrun in savedrun_model.objects.using(db_alias).filter(
        example_id__isnull=True,
        run_id__isnull=True,
        uid__isnull=True,
    ):
        publishedrun_model.objects.create(
            workflow=savedrun.workflow,
            published_run_id="",
            title=savedrun.page_title,
            notes=savedrun.page_notes,
            saved_run=savedrun,
            created_by=None,  # TODO: use gooey-support user
            last_edited_by=None,  # TODO: use gooey-support user
            visibility=PublishedRunVisibility.PUBLIC,
            is_approved_example=True,
        )


def backwards_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("app_users", "0010_alter_appuser_balance_alter_appuser_created_at_and_more"),
        ("bots", "0047_savedrun_created_by_savedrun_is_approved_example_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PublishedRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "published_run_id",
                    models.CharField(blank=True, max_length=128),
                ),
                (
                    "workflow",
                    models.IntegerField(
                        choices=[
                            (1, "Doc Search"),
                            (2, "Doc Summary"),
                            (3, "Google GPT"),
                            (4, "Copilot"),
                            (5, "Lipysnc + TTS"),
                            (6, "Text to Speech"),
                            (7, "Speech Recognition"),
                            (8, "Lipsync"),
                            (9, "Deforum Animation"),
                            (10, "Compare Text2Img"),
                            (11, "Text2Audio"),
                            (12, "Img2Img"),
                            (13, "Face Inpainting"),
                            (14, "Google Image Gen"),
                            (15, "Compare AI Upscalers"),
                            (16, "SEO Summary"),
                            (17, "Email Face Inpainting"),
                            (18, "Social Lookup Email"),
                            (19, "Object Inpainting"),
                            (20, "Image Segmentation"),
                            (21, "Compare LLM"),
                            (22, "Chyron Plant"),
                            (23, "Letter Writer"),
                            (24, "Smart GPT"),
                            (25, "AI QR Code"),
                            (26, "Doc Extract"),
                            (27, "Related QnA Maker"),
                            (28, "Related QnA Maker Doc"),
                            (29, "Embeddings"),
                            (30, "Bulk Runner"),
                        ]
                    ),
                ),
                ("title", models.TextField()),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "visibility",
                    models.IntegerField(
                        choices=[(1, "Unlisted"), (2, "Public")], default=1
                    ),
                ),
                ("is_approved_example", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="published_runs",
                        to="app_users.appuser",
                    ),
                ),
                (
                    "last_edited_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="app_users.appuser",
                    ),
                ),
                (
                    "saved_run",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="published_runs",
                        to="bots.savedrun",
                    ),
                ),
            ],
        ),
        migrations.RunPython(
            code=forwards_func,
            reverse_code=backwards_func,
        ),
    ]
