# Generated by Django 4.2.5 on 2023-11-25 12:38

import bots.custom_fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bots", "0047_messageattachment_alter_feedback_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="messageattachment",
            name="url",
            field=bots.custom_fields.CustomURLField(max_length=2048),
        ),
    ]
