# Generated by Django 4.2.7 on 2023-12-05 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("app_users", "0010_alter_appuser_balance_alter_appuser_created_at_and_more"),
        ("bots", "0048_alter_messageattachment_url"),
    ]

    operations = [
        migrations.CreateModel(
            name="PublishedRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("published_run_id", models.CharField(blank=True, max_length=128)),
                (
                    "workflow",
                    models.IntegerField(
                        choices=[
                            (1, "Doc Search"),
                            (2, "Doc Summary"),
                            (3, "Google GPT"),
                            (4, "Copilot"),
                            (5, "Lipysnc + TTS"),
                            (6, "Text to Speech"),
                            (7, "Speech Recognition"),
                            (8, "Lipsync"),
                            (9, "Deforum Animation"),
                            (10, "Compare Text2Img"),
                            (11, "Text2Audio"),
                            (12, "Img2Img"),
                            (13, "Face Inpainting"),
                            (14, "Google Image Gen"),
                            (15, "Compare AI Upscalers"),
                            (16, "SEO Summary"),
                            (17, "Email Face Inpainting"),
                            (18, "Social Lookup Email"),
                            (19, "Object Inpainting"),
                            (20, "Image Segmentation"),
                            (21, "Compare LLM"),
                            (22, "Chyron Plant"),
                            (23, "Letter Writer"),
                            (24, "Smart GPT"),
                            (25, "AI QR Code"),
                            (26, "Doc Extract"),
                            (27, "Related QnA Maker"),
                            (28, "Related QnA Maker Doc"),
                            (29, "Embeddings"),
                            (30, "Bulk Runner"),
                        ]
                    ),
                ),
                ("title", models.TextField(blank=True, default="")),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "visibility",
                    models.IntegerField(
                        choices=[(1, "Unlisted"), (2, "Public")], default=1
                    ),
                ),
                ("is_approved_example", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="published_runs",
                        to="app_users.appuser",
                    ),
                ),
                (
                    "last_edited_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="app_users.appuser",
                    ),
                ),
                (
                    "saved_run",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="published_runs",
                        to="bots.savedrun",
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
                "unique_together": {("workflow", "published_run_id")},
            },
        ),
        migrations.CreateModel(
            name="PublishedRunVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version_id", models.CharField(max_length=128, unique=True)),
                ("title", models.TextField(blank=True, default="")),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "visibility",
                    models.IntegerField(
                        choices=[(1, "Unlisted"), (2, "Public")], default=1
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "changed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="app_users.appuser",
                    ),
                ),
                (
                    "published_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="bots.publishedrun",
                    ),
                ),
                (
                    "saved_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="published_run_versions",
                        to="bots.savedrun",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "get_latest_by": "created_at",
                "indexes": [
                    models.Index(
                        fields=["published_run", "-created_at"],
                        name="bots_publis_publish_9cd246_idx",
                    ),
                    models.Index(
                        fields=["version_id"], name="bots_publis_version_c121d4_idx"
                    ),
                ],
            },
        ),
    ]
