# Generated by Django 4.2.7 on 2023-12-01 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("app_users", "0010_alter_appuser_balance_alter_appuser_created_at_and_more"),
        ("bots", "0048_publishedrun"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="savedrun",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="savedrun",
            name="is_approved_example",
        ),
        migrations.RemoveField(
            model_name="savedrun",
            name="visibility",
        ),
        migrations.AlterField(
            model_name="publishedrun",
            name="title",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterUniqueTogether(
            name="publishedrun",
            unique_together={("workflow", "published_run_id")},
        ),
        migrations.CreateModel(
            name="PublishedRunVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version_id", models.CharField(max_length=128, unique=True)),
                ("title", models.TextField(blank=True, default="")),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "visibility",
                    models.IntegerField(
                        choices=[(1, "Unlisted"), (2, "Public")], default=1
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "changed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="app_users.appuser",
                    ),
                ),
                (
                    "published_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="bots.publishedrun",
                    ),
                ),
                (
                    "saved_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="published_run_versions",
                        to="bots.savedrun",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "get_latest_by": "created_at",
                "indexes": [
                    models.Index(
                        fields=["published_run", "-created_at"],
                        name="bots_publis_publish_9cd246_idx",
                    ),
                    models.Index(
                        fields=["version_id"], name="bots_publis_version_c121d4_idx"
                    ),
                ],
            },
        ),
    ]
