# Generated by Django 4.2.7 on 2023-12-08 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("bots", "0050_botintegration_published_run"),
    ]

    operations = [
        migrations.AddField(
            model_name="savedrun",
            name="parent_version",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="children_runs",
                to="bots.publishedrunversion",
            ),
        ),
    ]
