# Generated by Django 4.2.7 on 2023-12-30 00:52

from django.db import migrations, models
from bots.models import FinishReason


def forwards_func(apps, schema_editor):
    saved_run = apps.get_model("bots", "SavedRun")
    saved_run.objects.filter(run_status="", error_msg="").update(
        finish_reason=FinishReason.DONE,
    )
    saved_run.objects.exclude(error_msg="").update(
        finish_reason=FinishReason.SERVER_ERROR,
    )


def backwards_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("bots", "0053_alter_publishedrun_workflow_alter_savedrun_workflow_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="savedrun",
            name="finish_reason",
            field=models.IntegerField(
                choices=[(1, "User Error"), (2, "Server Error"), (3, "Done")],
                default=None,
                null=True,
            ),
        ),
        migrations.RunPython(forwards_func, backwards_func),
    ]
