# Generated by Django 4.2.7 on 2023-12-28 10:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bots", "0053_alter_publishedrun_workflow_alter_savedrun_workflow_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="savedrun",
            name="example_id",
            field=models.CharField(
                blank=True,
                default=None,
                help_text="(Deprecated)",
                max_length=128,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="savedrun",
            name="page_notes",
            field=models.TextField(blank=True, default="", help_text="(Deprecated)"),
        ),
        migrations.AlterField(
            model_name="savedrun",
            name="page_title",
            field=models.TextField(blank=True, default="", help_text="(Deprecated)"),
        ),
    ]
