# Generated by Django 4.2.7 on 2024-01-02 16:05

from django.db import migrations, models


def migrate_keyword_instructions(apps, schema_editor):
    SavedRun = apps.get_model("bots", "SavedRun")
    db_alias = schema_editor.connection.alias
    objects = SavedRun.objects.using(db_alias)

    new_prompt = """
<Message>
{{ final_search_query }}

<Instructions>\
You are a BM25 tokenizer. Extract rare terms like part numbers from the message. Return a JSON List of tokenized query terms.
""".strip()

    qs = objects.exclude(
        state__keyword_instructions__isnull=True,
    ).exclude(
        state__keyword_instructions="",
    )
    for sr in qs:
        sr.state |= dict(keyword_instructions=new_prompt)
        sr.save()


class Migration(migrations.Migration):
    dependencies = [
        ("bots", "0053_alter_publishedrun_workflow_alter_savedrun_workflow_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="savedrun",
            name="example_id",
            field=models.CharField(
                blank=True,
                default=None,
                help_text="(Deprecated)",
                max_length=128,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="savedrun",
            name="page_notes",
            field=models.TextField(blank=True, default="", help_text="(Deprecated)"),
        ),
        migrations.AlterField(
            model_name="savedrun",
            name="page_title",
            field=models.TextField(blank=True, default="", help_text="(Deprecated)"),
        ),
        migrations.RunPython(migrate_keyword_instructions, migrations.RunPython.noop),
    ]
