# Generated by Django 4.2.7 on 2024-01-31 19:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bots", "0055_workflowmetadata"),
    ]

    operations = [
        migrations.AddField(
            model_name="botintegration",
            name="streaming_enabled",
            field=models.BooleanField(
                default=False,
                help_text="If set, the bot will stream messages to the frontend",
            ),
        ),
    ]
