# Generated by Django 4.2.7 on 2024-01-09 14:23

from django.db import migrations, models


def forwards_func(apps, schema_editor):
    PublishedRunVersion = apps.get_model("bots", "PublishedRunVersion")
    # for all the published run versions for each published run whose
    # is_approved_example is True, set is_approved_example on that version to True
    #
    # assumption here is that right now, almost all published runs were
    # pre-existing examples and not user runs. so it works to update the versions
    # in bulk
    PublishedRunVersion.objects.filter(
        published_run__is_approved_example=True,
    ).update(is_approved_example=True)


def backwards_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("bots", "0055_workflowmetadata"),
    ]

    operations = [
        migrations.AddField(
            model_name="publishedrunversion",
            name="is_approved_example",
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(
            forwards_func,
            backwards_func,
        ),
    ]
