# Generated by Django 4.2.7 on 2024-02-01 20:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0055_workflowmetadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='response_time',
            field=models.DurationField(default=datetime.timedelta(days=-1, seconds=86399), help_text='The time it took for the bot to respond to the corresponding user message'),
        ),
    ]
