# Generated by Django 4.2.7 on 2024-02-05 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0056_botintegration_streaming_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='response_time',
            field=models.DurationField(default=None, help_text='The time it took for the bot to respond to the corresponding user message', null=True),
        ),
        migrations.AlterField(
            model_name='botintegration',
            name='streaming_enabled',
            field=models.BooleanField(default=False, help_text='If set, the bot will stream messages to the frontend (Slack only)'),
        ),
    ]
