# Generated by Django 4.2.7 on 2024-02-06 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0057_message_response_time_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='savedrun',
            unique_together={('run_id', 'uid'), ('workflow', 'example_id')},
        ),
        migrations.AddIndex(
            model_name='savedrun',
            index=models.Index(fields=['run_id', 'uid'], name='bots_savedr_run_id_7b0b34_idx'),
        ),
    ]
