# Generated by Django 4.2.7 on 2024-02-12 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0058_alter_savedrun_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedrun',
            name='is_api_call',
            field=models.BooleanField(default=False),
        ),
    ]
