# Generated by Django 4.2.7 on 2024-03-08 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0060_conversation_reset_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmbeddingsReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(help_text='The URL of the original resource (e.g. a document)')),
                ('doc_tag', models.TextField()),
                ('document_ids', models.JSONField(help_text='The document ids that this embedding reference points to')),
            ],
            options={
                'indexes': [models.Index(fields=['url'], name='bots_embedd_url_aa3fda_idx'), models.Index(fields=['doc_tag'], name='bots_embedd_doc_tag_82995c_idx'), models.Index(fields=['url', 'doc_tag'], name='bots_embedd_url_8ec1ff_idx')],
                'unique_together': {('url', 'doc_tag')},
            },
        ),
    ]
