# Generated by Django 4.2.7 on 2024-03-19 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0062_alter_botintegration_platform'),
    ]

    operations = [
        migrations.AddField(
            model_name='publishedrun',
            name='example_priority',
            field=models.IntegerField(default=1, help_text='Priority of the example in the example list'),
        ),
        migrations.AddIndex(
            model_name='publishedrun',
            index=models.Index(fields=['workflow', 'visibility', 'is_approved_example', 'published_run_id', 'example_priority', 'updated_at'], name='bots_publis_workflo_ca43bd_idx'),
        ),
    ]
