# Generated by Django 4.2.7 on 2024-04-14 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0063_publishedrun_example_priority_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='botintegration',
            name='web_allowed_origins',
            field=models.JSONField(blank=True, default=list, help_text="List of allowed domains for the bot's web integration"),
        ),
        migrations.AddField(
            model_name='conversation',
            name='web_user_id',
            field=models.CharField(blank=True, default=None, help_text="User's web user id (mandatory if platform is WEB)", max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='botintegration',
            name='platform',
            field=models.IntegerField(choices=[(1, 'Facebook'), (2, 'Instagram'), (3, 'WhatsApp'), (4, 'Slack'), (5, 'Web')], help_text='The platform that the bot is integrated with'),
        ),
        migrations.AlterField(
            model_name='message',
            name='platform_msg_id',
            field=models.TextField(blank=True, default=None, help_text="The platform's delivered message id", null=True),
        ),
        migrations.AlterUniqueTogether(
            name='message',
            unique_together={('platform_msg_id', 'conversation')},
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['-created_at'], name='bots_messag_created_540f28_idx'),
        ),
    ]
