# Generated by Django 4.2.7 on 2024-03-29 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0063_publishedrun_example_priority_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='publishedrunversion',
            index=models.Index(fields=['changed_by'], name='bots_publis_changed_dd3ca1_idx'),
        ),
        migrations.AddIndex(
            model_name='savedrun',
            index=models.Index(fields=['uid'], name='bots_savedr_uid_d167d4_idx'),
        ),
    ]
