# Generated by Django 4.2.7 on 2024-04-15 02:33

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0063_publishedrun_example_priority_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowmetadata',
            name='price_multiplier',
            field=models.DecimalField(decimal_places=10, default=Decimal('1'), max_digits=15),
        ),
    ]
