# Generated by Django 4.2.7 on 2024-03-29 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0064_publishedrunversion_bots_publis_changed_dd3ca1_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='publishedrun',
            index=models.Index(models.F('created_by'), models.F('visibility'), models.OrderBy(models.F('updated_at'), descending=True), name='published_run_cre_vis_upd_idx'),
        ),
    ]
