# Generated by Django 4.2.7 on 2024-04-18 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0064_botintegration_web_allowed_origins_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botintegration',
            name='streaming_enabled',
            field=models.BooleanField(default=False, help_text='If set, the bot will stream messages to the frontend (Slack & Web only)'),
        ),
    ]
