# Generated by Django 4.2.7 on 2024-04-16 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0064_workflowmetadata_price_multiplier'),
        ('bots', '0065_alter_botintegration_streaming_enabled_and_more'),
    ]

    operations = [
    ]
