# Generated by Django 4.2.7 on 2024-04-22 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0065_alter_botintegration_streaming_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowmetadata',
            name='price_multiplier',
            field=models.FloatField(default=1),
        ),
    ]
