# Generated by Django 4.2.7 on 2024-04-16 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0066_merge_20240416_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflowmetadata',
            name='price_multiplier',
            field=models.FloatField(default=1),
        ),
    ]
