# Generated by Django 4.2.7 on 2024-04-24 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0066_workflowmetadata_price_multiplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botintegration',
            name='user_language',
            field=models.TextField(blank=True, default='', help_text='The response language (same as user language in video bots)'),
        ),
    ]
