# Generated by Django 4.2.7 on 2024-05-05 12:05

from django.db import migrations, models
import django.db.models.deletion

def forwards_func(apps, schema_editor):
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    BotIntegration = apps.get_model("bots", "BotIntegration")
    db_alias = schema_editor.connection.alias
    objects = BotIntegration.objects.using(db_alias)

    # Remove empty strings before we add the unique constraint
    for bi in objects.filter(analysis_run__isnull=False):
        bi.analysis_runs.create(saved_run=bi.analysis_run)

class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0067_alter_botintegration_user_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotIntegrationAnalysisRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bot_integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_runs', to='bots.botintegration')),
                ('published_run', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='analysis_runs', to='bots.publishedrun')),
                ('saved_run', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='analysis_runs', to='bots.savedrun')),
            ],
        ),
        migrations.AddConstraint(
            model_name='botintegrationanalysisrun',
            constraint=models.CheckConstraint(check=models.Q(('saved_run__isnull', False), ('published_run__isnull', False), _connector='XOR'), name='saved_run_xor_published_run'),
        ),
        migrations.AlterUniqueTogether(
            name='botintegrationanalysisrun',
            unique_together={('bot_integration', 'saved_run', 'published_run')},
        ),
        migrations.RunPython(forwards_func),
    ]
