# Generated by Django 4.2.7 on 2024-05-05 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0068_botintegrationanalysisrun_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='botintegration',
            name='analysis_run',
        ),
    ]
