# Generated by Django 4.2.7 on 2024-05-06 22:49

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0069_remove_botintegration_analysis_run'),
    ]

    operations = [
        migrations.AddField(
            model_name='botintegrationanalysisrun',
            name='cooldown_period',
            field=models.DurationField(blank=True, default=None, help_text='The time period to wait before running the analysis again', null=True),
        ),
        migrations.AddField(
            model_name='botintegrationanalysisrun',
            name='created_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='botintegrationanalysisrun',
            name='last_run_at',
            field=models.DateTimeField(blank=True, default=None, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='botintegrationanalysisrun',
            name='scheduled_task_id',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='botintegrationanalysisrun',
            name='published_run',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='analysis_runs', to='bots.publishedrun'),
        ),
        migrations.AlterField(
            model_name='botintegrationanalysisrun',
            name='saved_run',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='analysis_runs', to='bots.savedrun'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['-created_at', 'bot_integration'], name='bots_conver_created_9cb956_idx'),
        ),
    ]
