# Generated by Django 4.2.7 on 2024-05-17 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0071_botintegration_by_line_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='botintegration',
            name='web_config_extras',
            field=models.JSONField(blank=True, default=dict, help_text="Extra configuration for the bot's web integration"),
        ),
    ]
