# Generated by Django 4.2.7 on 2024-07-12 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0076_alter_workflowmetadata_default_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedrun',
            name='error_code',
            field=models.IntegerField(blank=True, default=None, help_text='The HTTP status code of the error. If this is not set, 500 is assumed.', null=True),
        ),
        migrations.AddField(
            model_name='savedrun',
            name='error_type',
            field=models.TextField(blank=True, default='', help_text='The exception type'),
        ),
        migrations.AlterField(
            model_name='savedrun',
            name='error_msg',
            field=models.TextField(blank=True, default='', help_text='The error message. If this is not set, the run is deemed successful.'),
        ),
    ]
