# Generated by Django 4.2.7 on 2024-07-16 17:01

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0077_savedrun_error_code_savedrun_error_type_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='botintegration',
            unique_together={('slack_channel_id', 'slack_team_id')},
        ),
        migrations.AddField(
            model_name='botintegration',
            name='twilio_account_sid',
            field=models.TextField(blank=True, default='', help_text='Account SID, required if using api_key to authenticate'),
        ),
        migrations.AddField(
            model_name='botintegration',
            name='twilio_asr_language',
            field=models.TextField(blank=True, default='', help_text='The language to use for Twilio ASR (https://www.twilio.com/docs/voice/twiml/gather#languagetags)'),
        ),
        migrations.AddField(
            model_name='botintegration',
            name='twilio_initial_audio_url',
            field=models.TextField(blank=True, default='', help_text='The initial audio url to play to the user when a call is started'),
        ),
        migrations.AddField(
            model_name='botintegration',
            name='twilio_initial_text',
            field=models.TextField(blank=True, default='', help_text='The initial text to send to the user when a call is started'),
        ),
        migrations.AddField(
            model_name='botintegration',
            name='twilio_password',
            field=models.TextField(blank=True, default='', help_text='Password to authenticate with, auth_token (if using account_sid) or api_secret (if using api_key)'),
        ),
        migrations.AddField(
            model_name='botintegration',
            name='twilio_phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, default=None, help_text='Twilio phone number as found on twilio.com/console/phone-numbers/incoming (mandatory)', max_length=128, null=True, region=None, unique=True),
        ),
        migrations.AddField(
            model_name='botintegration',
            name='twilio_phone_number_sid',
            field=models.TextField(blank=True, default='', help_text='Twilio phone number sid as found on twilio.com/console/phone-numbers/incoming'),
        ),
        migrations.AddField(
            model_name='botintegration',
            name='twilio_tts_voice',
            field=models.TextField(blank=True, default='', help_text="The voice to use for Twilio TTS ('man', 'woman', or Amazon Polly/Google Voices: https://www.twilio.com/docs/voice/twiml/say/text-speech#available-voices-and-languages)"),
        ),
        migrations.AddField(
            model_name='botintegration',
            name='twilio_use_missed_call',
            field=models.BooleanField(default=False, help_text="If true, the bot will reject incoming calls and call back the user instead so they don't get charged for the call"),
        ),
        migrations.AddField(
            model_name='botintegration',
            name='twilio_username',
            field=models.TextField(blank=True, default='', help_text='Username to authenticate with, either account_sid or api_key'),
        ),
        migrations.AddField(
            model_name='botintegration',
            name='twilio_waiting_audio_url',
            field=models.TextField(blank=True, default='', help_text='The audio url to play to the user while waiting for a response if using voice'),
        ),
        migrations.AddField(
            model_name='botintegration',
            name='twilio_waiting_text',
            field=models.TextField(blank=True, default='', help_text='The text to send to the user while waiting for a response if using sms'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='twilio_phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, default='', help_text="User's Twilio phone number (mandatory)", max_length=128, region=None),
        ),
        migrations.AlterField(
            model_name='botintegration',
            name='platform',
            field=models.IntegerField(choices=[(1, 'Facebook Messenger'), (2, 'Instagram'), (3, 'WhatsApp'), (4, 'Slack'), (5, 'Web'), (6, 'Twilio')], help_text='The platform that the bot is integrated with'),
        ),
        migrations.AlterUniqueTogether(
            name='botintegration',
            unique_together={('slack_channel_id', 'slack_team_id'), ('twilio_phone_number', 'twilio_account_sid')},
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['bot_integration', 'twilio_phone_number'], name='bots_conver_bot_int_73ac7b_idx'),
        ),
    ]
