# Generated by Django 4.2.7 on 2024-07-22 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0078_alter_botintegration_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='botintegration',
            name='twilio_asr_language',
        ),
        migrations.RemoveField(
            model_name='botintegration',
            name='twilio_tts_voice',
        ),
    ]
