# Generated by Django 4.2.7 on 2024-08-09 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0079_remove_botintegration_twilio_asr_language_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='botintegration',
            name='twilio_fresh_conversation_per_call',
            field=models.BooleanField(default=False, help_text='If set, the bot will start a new conversation for each call'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='twilio_call_sid',
            field=models.TextField(blank=True, default='', help_text='Twilio call sid (only used if each call is a new conversation)'),
        ),
    ]
