# Generated by Django 4.2.7 on 2024-08-19 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0079_remove_botintegration_twilio_asr_language_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botintegration',
            name='streaming_enabled',
            field=models.BooleanField(default=True, help_text='If set, the bot will stream messages to the frontend (Slack, Web & Whatsapp only)'),
        ),
    ]
