# Generated by Django 4.2.7 on 2024-08-28 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0080_botintegration_twilio_fresh_conversation_per_call_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='conversation',
            name='bots_conver_bot_int_73ac7b_idx',
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['bot_integration', 'twilio_phone_number', 'twilio_call_sid'], name='bots_conver_bot_int_477755_idx'),
        ),
    ]
