# Generated by Django 4.2.7 on 2024-08-23 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0080_alter_botintegration_streaming_enabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botintegration',
            name='streaming_enabled',
            field=models.BooleanField(default=True, help_text='If set, the bot will stream messages to the frontend'),
        ),
    ]
