# Generated by Django 4.2.7 on 2024-08-28 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0080_alter_botintegration_streaming_enabled'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='conversation',
            name='bots_conver_bot_int_73ac7b_idx',
        ),
        migrations.AddField(
            model_name='botintegration',
            name='twilio_fresh_conversation_per_call',
            field=models.BooleanField(default=False, help_text='If set, the bot will start a new conversation for each call'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='twilio_call_sid',
            field=models.TextField(blank=True, default='', help_text='Twilio call sid (only used if each call is a new conversation)'),
        ),
        migrations.AlterField(
            model_name='botintegration',
            name='streaming_enabled',
            field=models.BooleanField(default=True, help_text='If set, the bot will stream messages to the frontend'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['bot_integration', 'twilio_phone_number', 'twilio_call_sid'], name='bots_conver_bot_int_477755_idx'),
        ),
    ]
