# Generated by Django 4.2.7 on 2024-08-30 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0005_org_unique_personal_org_per_user'),
        ('bots', '0081_remove_conversation_bots_conver_bot_int_73ac7b_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedrun',
            name='billed_org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billed_runs', to='orgs.org'),
        ),
    ]
