# Generated by Django 5.0.9 on 2024-09-15 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0081_remove_conversation_bots_conver_bot_int_73ac7b_idx_and_more'),
        ('workspaces', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedrun',
            name='workspace',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='saved_runs', to='workspaces.workspace'),
        ),
    ]
