# Generated by Django 5.1.2 on 2024-11-03 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0023_alter_appusertransaction_workspace'),
        ('bots', '0083_publishedrun_workspace'),
        ('workspaces', '0003_rename_logo_workspace_photo_url'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='botintegration',
            name='bots_botint_billing_466a86_idx',
        ),
        migrations.AddField(
            model_name='botintegration',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='botintegrations', to='app_users.appuser'),
        ),
        migrations.AddField(
            model_name='botintegration',
            name='workspace',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='botintegrations', to='workspaces.workspace'),
        ),
        migrations.AlterField(
            model_name='botintegration',
            name='billing_account_uid',
            field=models.TextField(blank=True, db_index=True, default='', help_text='(Deprecated)'),
        ),
        migrations.AddIndex(
            model_name='botintegration',
            index=models.Index(fields=['workspace', 'platform'], name='bots_botint_workspa_447bf2_idx'),
        ),
    ]
