# Generated by Django 5.1.1 on 2024-09-23 08:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0083_publishedrun_workspace'),
        ('workspaces', '0002_alter_workspace_domain_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='botintegration',
            name='workspace',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='botintegrations', to='workspaces.workspace'),
        ),
    ]
