# Generated by Django 5.1.1 on 2024-09-25 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0084_botintegration_workspace'),
    ]

    operations = [
        migrations.AddField(
            model_name='publishedrunversion',
            name='change_notes',
            field=models.TextField(blank=True, default=''),
        ),
    ]
