# Generated by Django 5.1.2 on 2024-11-04 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0085_remove_savedrun_bots_savedr_workflo_aa2d32_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='publishedrunversion',
            name='change_notes',
            field=models.TextField(blank=True, default=''),
        ),
    ]
