# Generated by Django 5.1.2 on 2024-11-07 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0086_publishedrunversion_change_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publishedrun',
            name='visibility',
            field=models.IntegerField(choices=[(1, 'Unlisted'), (2, 'Public'), (3, 'Internal')], default=1),
        ),
        migrations.AlterField(
            model_name='publishedrunversion',
            name='visibility',
            field=models.IntegerField(choices=[(1, 'Unlisted'), (2, 'Public'), (3, 'Internal')], default=1),
        ),
    ]
