# Generated by Django 5.1.2 on 2024-11-13 12:20

import bots.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0086_publishedrunversion_change_notes'),
        ('workspaces', '0003_rename_logo_workspace_photo_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publishedrun',
            name='workspace',
            field=models.ForeignKey(default=bots.models.get_default_published_run_workspace, on_delete=django.db.models.deletion.CASCADE, to='workspaces.workspace'),
        ),
    ]
