# Generated by Django 5.1.2 on 2024-11-19 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0087_alter_publishedrun_workspace'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publishedrun',
            name='visibility',
            field=models.IntegerField(choices=[(1, 'Unlisted'), (2, 'Public'), (3, 'Internal')], default=1),
        ),
        migrations.AlterField(
            model_name='publishedrunversion',
            name='visibility',
            field=models.IntegerField(choices=[(1, 'Unlisted'), (2, 'Public'), (3, 'Internal')], default=1),
        ),
    ]
