# Generated by Django 5.1.2 on 2024-11-26 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0023_alter_appusertransaction_workspace'),
        ('bots', '0088_alter_publishedrun_visibility_and_more'),
        ('workspaces', '0005_alter_workspaceinvite_status'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='publishedrun',
            name='bots_publis_workflo_d3ad4e_idx',
        ),
        migrations.RemoveIndex(
            model_name='publishedrun',
            name='published_run_cre_vis_upd_idx',
        ),
        migrations.AlterField(
            model_name='publishedrun',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_runs', to='app_users.appuser'),
        ),
        migrations.AlterField(
            model_name='publishedrun',
            name='last_edited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_users.appuser'),
        ),
        migrations.AlterField(
            model_name='publishedrunversion',
            name='changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_users.appuser'),
        ),
        migrations.AddIndex(
            model_name='publishedrun',
            index=models.Index(fields=['-updated_at', 'workspace', 'created_by', 'visibility'], name='bots_publis_updated_af6358_idx'),
        ),
    ]
