# Generated by Django 5.1.3 on 2025-01-02 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0023_alter_appusertransaction_workspace'),
        ('bots', '0090_remove_publishedrun_bots_publis_workflo_a0953a_idx_and_more'),
        ('workspaces', '0007_workspace_handle'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='publishedrun',
            index=models.Index(fields=['visibility', 'workspace', '-updated_at'], name='bots_publis_visibil_cf3dd8_idx'),
        ),
    ]
