# Generated by Django 5.1.3 on 2025-01-23 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0090_remove_publishedrun_bots_publis_workflo_a0953a_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotIntegrationScheduledFunction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_run_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bot_integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_functions', to='bots.botintegration')),
                ('published_run', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_functions', to='bots.publishedrun')),
                ('saved_run', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_functions', to='bots.savedrun')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('saved_run__isnull', False), ('published_run__isnull', False), _connector='XOR'), name='bi_scheduled_functions_saved_run_xor_published_run')],
            },
        ),
    ]
