# Generated by Django 5.1.3 on 2025-02-12 06:45

import bots.custom_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0091_botintegrationscheduledrun'),
    ]

    operations = [
        migrations.AddField(
            model_name='publishedrun',
            name='photo_url',
            field=bots.custom_fields.CustomURLField(blank=True, default='', max_length=2048),
        ),
    ]
