# Generated by Django 5.1.3 on 2025-03-11 11:33

import bots.custom_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0092_alter_publishedrun_workflow_alter_savedrun_workflow_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='publishedrun',
            name='photo_url',
            field=bots.custom_fields.CustomURLField(blank=True, default='', max_length=2048),
        ),
        migrations.AddField(
            model_name='workflowmetadata',
            name='emoji',
            field=models.TextField(blank=True, default=''),
        ),
    ]
