# Generated by Django 5.1.3 on 2025-03-15 00:49

import bots.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0092_alter_publishedrun_workflow_alter_savedrun_workflow_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botintegration',
            name='wa_phone_number',
            field=bots.models.WhatsappPhoneNumberField(blank=True, default='', help_text="Bot's WhatsApp phone number (only for display)", max_length=128, region=None, validators=[bots.models.validate_phonenumber]),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='wa_phone_number',
            field=bots.models.WhatsappPhoneNumberField(blank=True, db_index=True, default='', help_text="User's WhatsApp phone number (required if platform is WhatsApp)", max_length=128, region=None),
        ),
    ]
