# Generated by Django 5.1.3 on 2025-03-07 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0092_publishedrun_photo_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowmetadata',
            name='emoji',
            field=models.TextField(blank=True, default=''),
        ),
    ]
