# Generated by Django 5.1.3 on 2025-03-25 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0093_publishedrun_is_public_alter_publishedrun_visibility_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='publishedrunversion',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
