# Generated by Django 5.1.3 on 2025-03-31 12:29

import bots.custom_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0094_publishedrun_photo_url_workflowmetadata_emoji'),
    ]

    operations = [
        migrations.AddField(
            model_name='publishedrunversion',
            name='photo_url',
            field=bots.custom_fields.CustomURLField(blank=True, default='', max_length=2048),
        ),
    ]
