# Generated by Django 5.1.3 on 2025-04-04 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0026_alter_appusertransaction_plan'),
        ('bots', '0094_publishedrun_photo_url_workflowmetadata_emoji'),
        ('workspaces', '0010_workspace_banner_url'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='publishedrun',
            name='bots_publis_updated_af6358_idx',
        ),
        migrations.RemoveIndex(
            model_name='publishedrun',
            name='bots_publis_is_appr_a989ec_idx',
        ),
        migrations.AddField(
            model_name='publishedrun',
            name='workspace_access',
            field=models.IntegerField(choices=[(1, 'View Only'), (2, 'Find And View'), (4, 'Edit'), (3, 'Internal')], default=4),
        ),
        migrations.AddField(
            model_name='publishedrunversion',
            name='workspace_access',
            field=models.IntegerField(choices=[(1, 'View Only'), (2, 'Find And View'), (4, 'Edit'), (3, 'Internal')], default=4),
        ),
        migrations.AlterField(
            model_name='publishedrun',
            name='visibility',
            field=models.IntegerField(choices=[(1, 'View Only'), (2, 'Find And View'), (4, 'Edit'), (3, 'Internal')], default=2),
        ),
        migrations.AlterField(
            model_name='publishedrunversion',
            name='visibility',
            field=models.IntegerField(choices=[(1, 'View Only'), (2, 'Find And View'), (4, 'Edit'), (3, 'Internal')], default=1),
        ),
        migrations.AddIndex(
            model_name='publishedrun',
            index=models.Index(fields=['is_approved_example', 'visibility', 'workspace_access', 'published_run_id', 'updated_at', 'workflow', 'example_priority'], name='bots_publis_is_appr_8c8651_idx'),
        ),
        migrations.AddIndex(
            model_name='publishedrun',
            index=models.Index(fields=['-updated_at', 'workspace', 'created_by', 'visibility', 'workspace_access'], name='bots_publis_updated_31d8a4_idx'),
        ),
    ]
