# Generated by Django 5.1.3 on 2025-04-04 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0026_alter_appusertransaction_plan'),
        ('bots', '0095_remove_publishedrun_bots_publis_updated_af6358_idx_and_more'),
        ('workspaces', '0010_workspace_banner_url'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='publishedrun',
            name='bots_publis_is_appr_8c8651_idx',
        ),
        migrations.RemoveIndex(
            model_name='publishedrun',
            name='bots_publis_updated_31d8a4_idx',
        ),
        migrations.RenameField(
            model_name='publishedrun',
            old_name='visibility',
            new_name='public_access',
        ),
        migrations.RenameField(
            model_name='publishedrunversion',
            old_name='visibility',
            new_name='public_access',
        ),
        migrations.AddIndex(
            model_name='publishedrun',
            index=models.Index(fields=['is_approved_example', 'public_access', 'workspace_access', 'published_run_id', 'updated_at', 'workflow', 'example_priority'], name='bots_publis_is_appr_644b75_idx'),
        ),
        migrations.AddIndex(
            model_name='publishedrun',
            index=models.Index(fields=['-updated_at', 'workspace', 'created_by', 'public_access', 'workspace_access'], name='bots_publis_updated_fcf021_idx'),
        ),
    ]
