# Generated by Django 5.1.3 on 2025-04-17 04:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0096_remove_publishedrun_bots_publis_is_appr_8c8651_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='botintegration',
            name='demo_button_qr_code_image',
            field=models.TextField(blank=True, help_text='QR code image for the demo button', null=True),
        ),
        migrations.AddField(
            model_name='botintegration',
            name='demo_button_qr_code_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bots.savedrun'),
        ),
        migrations.AlterField(
            model_name='publishedrun',
            name='public_access',
            field=models.IntegerField(choices=[(1, 'View Only'), (2, 'Find And View'), (4, 'Edit'), (3, 'Internal (Deprecated)')], default=2),
        ),
        migrations.AlterField(
            model_name='publishedrun',
            name='workspace_access',
            field=models.IntegerField(choices=[(1, 'View Only'), (2, 'Find And View'), (4, 'Edit'), (3, 'Internal (Deprecated)')], default=4),
        ),
        migrations.AlterField(
            model_name='publishedrunversion',
            name='public_access',
            field=models.IntegerField(choices=[(1, 'View Only'), (2, 'Find And View'), (4, 'Edit'), (3, 'Internal (Deprecated)')], default=1),
        ),
        migrations.AlterField(
            model_name='publishedrunversion',
            name='workspace_access',
            field=models.IntegerField(choices=[(1, 'View Only'), (2, 'Find And View'), (4, 'Edit'), (3, 'Internal (Deprecated)')], default=4),
        ),
    ]
