# Generated by Django 5.1.3 on 2025-04-18 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0097_publishedrunversion_photo_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='publishedrun',
            name='run_count',
            field=models.IntegerField(default=0),
        ),
    ]
