# Generated by Django 5.1.3 on 2025-04-21 05:12

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0027_appuser_appuser_search_vector_idx'),
        ('bots', '0098_add_run_count_to_publishedrun'),
        ('workspaces', '0010_workspace_banner_url'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='publishedrun',
            index=models.Index(fields=['published_run_id'], name='bots_publis_publish_41767a_idx'),
        ),
        migrations.AddIndex(
            model_name='publishedrun',
            index=django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.search.SearchVector('title', 'notes', config='english'), name='publishedrun_search_vector_idx'),
        ),
    ]
