# Generated by Django 5.1.3 on 2025-04-21 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0099_publishedrun_bots_publis_publish_41767a_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='publishedrun',
            name='publishedrun_search_vector_idx',
        ),
    ]
