# Generated by Django 5.1.3 on 2025-04-24 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bots", "0101_botintegrationanalysischart"),
    ]

    operations = [
        migrations.AddField(
            model_name="botintegration",
            name="demo_button_qr_code_image",
            field=models.TextField(
                blank=True, help_text="QR code image for the demo button", null=True
            ),
        ),
        migrations.AddField(
            model_name="botintegration",
            name="demo_button_qr_code_run",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="bots.savedrun",
            ),
        ),
    ]
