# Generated by Django 5.1.3 on 2025-05-24 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bots", "0102_botintegration_demo_button_qr_code_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="botintegration",
            name="public_visibility",
            field=models.IntegerField(
                choices=[
                    (1, "View Only"),
                    (2, "Find And View"),
                    (4, "Edit"),
                    (3, "Internal (Deprecated)"),
                ],
                default=1,
                help_text="Controls whether this bot integration is listed on gooey.ai/chat & whether the demo button is shown",
            ),
        ),
    ]
