# Generated by Django 5.1.3 on 2025-05-02 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bots", "0103_alter_publishedrun_workflow_alter_savedrun_workflow_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="botintegration",
            name="demo_notes",
            field=models.TextField(blank=True, null=True),
        ),
    ]
