# Generated by Django 5.1.3 on 2025-06-19 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bots", "0103_alter_botintegration_public_visibility"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="platform_medium",
            field=models.CharField(
                blank=True,
                choices=[("SMS", "SMS"), ("VOICE", "Voice")],
                default="",
                help_text="Platform medium (Voice / SMS etc.)",
                max_length=32,
            ),
        ),
    ]
