# Generated by Django 5.2.3 on 2025-07-26 02:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bots", "0103_alter_botintegration_public_visibility"),
    ]

    operations = [
        migrations.AddField(
            model_name="botintegration",
            name="ask_detailed_feedback",
            field=models.BooleanField(
                default=False,
                help_text="Ask for detailed feedback when users give a thumbs down (requires feedback buttons to be enabled)",
            ),
        ),
        migrations.AlterField(
            model_name="savedrun",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="children",
                to="bots.savedrun",
                verbose_name="Parent Run",
            ),
        ),
    ]
