# Generated by Django 5.1.3 on 2025-07-24 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bots", "0103_alter_botintegration_public_visibility"),
    ]

    operations = [
        migrations.AddField(
            model_name="botintegration",
            name="disable_rate_limits",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="conversation",
            name="blocked_at",
            field=models.DateTimeField(
                blank=True,
                default=None,
                help_text="Timestamp when the conversation was blocked.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="conversation",
            name="blocked_status",
            field=models.IntegerField(
                choices=[(0, "Normal"), (1, "Warning"), (2, "Blocked")], default=0
            ),
        ),
        migrations.AlterField(
            model_name="savedrun",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="children",
                to="bots.savedrun",
                verbose_name="Parent Run",
            ),
        ),
    ]
