# Generated by Django 5.2.3 on 2025-07-31 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bots", "0104_add_ask_detailed_feedback"),
        ("bots", "0104_botintegration_disable_rate_limits_and_more"),
    ]

    operations = []
