# Generated by Django 5.1.3 on 2025-08-06 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bots", "0104_botintegration_disable_rate_limits_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="conversation",
            name="state",
        ),
        migrations.RemoveField(
            model_name="feedback",
            name="category",
        ),
        migrations.RemoveField(
            model_name="feedback",
            name="creator",
        ),
        migrations.RemoveField(
            model_name="feedback",
            name="status",
        ),
        migrations.AddField(
            model_name="botintegration",
            name="ask_detailed_feedback",
            field=models.BooleanField(
                default=False,
                help_text="Ask for detailed feedback when users give a thumbs down (requires feedback buttons to be enabled)",
            ),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="rating",
            field=models.IntegerField(choices=[(1, "👍🏾"), (2, "👎🏾"), (3, "🤔")]),
        ),
    ]
