# Generated by Django 5.1.3 on 2025-08-18 10:46

import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bots", "0105_remove_conversation_state_remove_feedback_category_and_more"),
        ("number_cycling", "0003_provisionednumber_wa_phone_number_id_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="conversation",
            name="bots_conver_bot_int_477755_idx",
        ),
        migrations.AlterUniqueTogether(
            name="botintegration",
            unique_together={("slack_channel_id", "slack_team_id")},
        ),
        migrations.AddField(
            model_name="conversation",
            name="extension",
            field=models.ForeignKey(
                blank=True,
                help_text="The extension this conversation is associated with (if any)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="conversations",
                to="number_cycling.botextension",
            ),
        ),
        migrations.AlterField(
            model_name="botintegration",
            name="twilio_phone_number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True,
                default=None,
                help_text="Twilio phone number as found on twilio.com/console/phone-numbers/incoming (mandatory)",
                max_length=128,
                null=True,
                region=None,
            ),
        ),
        migrations.AddIndex(
            model_name="conversation",
            index=models.Index(
                fields=[
                    "bot_integration",
                    "twilio_phone_number",
                    "twilio_call_sid",
                    "extension",
                ],
                name="bots_conver_bot_int_b8df32_idx",
            ),
        ),
    ]
