# Generated by Django 5.1.3 on 2025-08-08 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bots", "0105_remove_conversation_state_remove_feedback_category_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="savedrun",
            unique_together={("run_id", "uid"), ("workflow", "example_id")},
        ),
        migrations.AddField(
            model_name="savedrun",
            name="platform",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, "Facebook Messenger"),
                    (2, "Instagram"),
                    (3, "WhatsApp"),
                    (4, "Slack"),
                    (5, "Web"),
                    (6, "Twilio"),
                ],
                default=None,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="savedrun",
            name="user_message_id",
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterUniqueTogether(
            name="savedrun",
            unique_together={
                ("platform", "user_message_id"),
                ("run_id", "uid"),
                ("workflow", "example_id"),
            },
        ),
    ]
