# Generated by Django 5.1.3 on 2025-08-19 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bots", "0106_alter_savedrun_unique_together_savedrun_platform_and_more"),
        ("bots", "0106_remove_conversation_bots_conver_bot_int_477755_idx_and_more"),
    ]

    operations = []
