# Generated by Django 5.1.3 on 2025-08-25 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bots", "0107_merge_20250819_2104"),
    ]

    operations = [
        migrations.AlterField(
            model_name="botintegration",
            name="wa_phone_number_id",
            field=models.CharField(
                blank=True,
                default=None,
                help_text="Bot's WhatsApp phone number id (mandatory)",
                max_length=256,
                null=True,
            ),
        ),
    ]
