# Generated by Django 5.1.3 on 2025-10-02 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bots", "0108_alter_publishedrun_workflow_alter_savedrun_workflow_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="botintegration",
            options={"get_latest_by": "updated_at", "ordering": ["-updated_at"]},
        ),
    ]
