# Generated by Django 5.1.3 on 2025-10-02 19:58

import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_users", "0028_remove_appuser_appuser_search_vector_idx"),
        ("bots", "0109_alter_botintegration_options"),
        ("number_cycling", "0001_initial"),
        ("workspaces", "0012_remove_workspace_workspace_search_vector_idx"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="botintegration",
            unique_together={("slack_channel_id", "slack_team_id")},
        ),
        migrations.AddField(
            model_name="botintegration",
            name="extension_number",
            field=models.IntegerField(
                blank=True,
                default=None,
                help_text="Extension number for shared phone number",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="botintegration",
            name="shared_phone_number",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bot_integrations",
                to="number_cycling.sharedphonenumber",
            ),
        ),
        migrations.AlterField(
            model_name="botintegration",
            name="twilio_phone_number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True,
                default=None,
                help_text="Twilio phone number as found on twilio.com/console/phone-numbers/incoming (mandatory)",
                max_length=128,
                null=True,
                region=None,
            ),
        ),
        migrations.AlterField(
            model_name="botintegration",
            name="twilio_phone_number_sid",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Twilio phone number sid as found on twilio.com/console/phone-numbers/incoming (only for display)",
            ),
        ),
        migrations.AlterField(
            model_name="botintegration",
            name="wa_phone_number_id",
            field=models.CharField(
                blank=True,
                default=None,
                help_text="Bot's WhatsApp phone number id (mandatory)",
                max_length=256,
                null=True,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="botintegration",
            unique_together={
                ("platform", "shared_phone_number", "extension_number"),
                ("slack_channel_id", "slack_team_id"),
            },
        ),
        migrations.AddIndex(
            model_name="botintegration",
            index=models.Index(
                fields=["-updated_at"], name="bots_botint_updated_9f0447_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="botintegration",
            constraint=models.UniqueConstraint(
                condition=models.Q(("shared_phone_number__isnull", True)),
                fields=("twilio_phone_number",),
                name="unique_twilio_phone_number",
                violation_error_message="A Bot Integration with this dedicated Twilio phone number already exists",
            ),
        ),
        migrations.AddConstraint(
            model_name="botintegration",
            constraint=models.UniqueConstraint(
                condition=models.Q(("shared_phone_number__isnull", True)),
                fields=("wa_phone_number_id",),
                name="unique_wa_phone_number_id",
                violation_error_message="A Bot Integration with this dedicated WhatsApp phone number already exists",
            ),
        ),
    ]
