# Generated by Django 5.1.3 on 2025-10-06 11:13

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bots", "0110_alter_botintegration_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="botintegration",
            name="twilio_phone_number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True,
                db_index=True,
                default=None,
                help_text="Twilio phone number as found on twilio.com/console/phone-numbers/incoming (mandatory)",
                max_length=128,
                null=True,
                region=None,
            ),
        ),
        migrations.AlterField(
            model_name="botintegration",
            name="wa_phone_number_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                default=None,
                help_text="Bot's WhatsApp phone number id (mandatory)",
                max_length=256,
                null=True,
            ),
        ),
    ]
