# Generated by Django 5.1.3 on 2025-10-23 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bots", "0111_alter_botintegration_twilio_phone_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="botintegration",
            name="slack_read_receipt_msg",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Bot's Slack read receipt message - if set, and platform is Slack, the bot will send this message to mark the user message as read and then delete it when it has a response ready",
            ),
        ),
    ]
