# Generated by Django 5.1.3 on 2025-11-13 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bots", "0112_alter_botintegration_slack_read_receipt_msg"),
    ]

    operations = [
        migrations.AddField(
            model_name="botintegration",
            name="input_placeholder",
            field=models.TextField(blank=True, default=""),
        ),
    ]
