# Generated by Django 5.1.3 on 2025-12-19 08:11

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bots", "0112_alter_botintegration_slack_read_receipt_msg"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64)),
                ("icon", models.TextField(blank=True, default="")),
                (
                    "category",
                    models.IntegerField(
                        choices=[
                            (1, "App"),
                            (2, "Industry"),
                            (3, "Medium"),
                            (4, "Language"),
                            (5, "Region"),
                            (6, "Other"),
                        ],
                        default=6,
                    ),
                ),
                (
                    "featured_priority",
                    models.IntegerField(
                        default=1,
                        help_text="Higher priority tags are shown first. If 0, then the tag is not shown at all.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-featured_priority", "name"],
                "indexes": [
                    models.Index(fields=["name"], name="bots_tag_name_9ec93a_idx")
                ],
                "constraints": [
                    models.UniqueConstraint(
                        django.db.models.functions.text.Upper("name"),
                        name="tag_upper_name_is_unique",
                        violation_error_message="This tag already exists",
                    )
                ],
            },
        ),
        migrations.AddField(
            model_name="publishedrun",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="published_runs", to="bots.tag"
            ),
        ),
        migrations.AddField(
            model_name="publishedrunversion",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="published_run_versions", to="bots.tag"
            ),
        ),
    ]
