# Generated by Django 5.1.3 on 2026-03-20 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bots", "0114_savedrun_error_params"),
    ]

    operations = [
        migrations.AddField(
            model_name="savedrun",
            name="parent_builder_saved_run",
            field=models.ForeignKey(
                blank=True,
                default=None,
                help_text="The Parent Gooey Builder SavedRun that created this run",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="child_builder_saved_runs",
                to="bots.savedrun",
            ),
        ),
    ]
