# Generated by Django 5.1.3 on 2026-03-20 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bots", "0114_savedrun_error_params"),
    ]

    operations = [
        migrations.AddField(
            model_name="savedrun",
            name="gooey_builder_last_message_id",
            field=models.TextField(
                blank=True,
                default=None,
                help_text="platform_msg_id of the last builder Message at the point this run was created",
                null=True,
            ),
        ),
    ]
