# Generated by Django 5.1.3 on 2026-03-25 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bots", "0115_savedrun_parent_builder_saved_run"),
    ]

    operations = [
        migrations.AddField(
            model_name="botintegration",
            name="telegram_bot_id",
            field=models.CharField(
                blank=True,
                default=None,
                help_text="Telegram bot user ID",
                max_length=256,
                null=True,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="botintegration",
            name="telegram_bot_token",
            field=models.TextField(
                blank=True,
                default="",
                editable=False,
                help_text="Telegram bot token from @BotFather",
            ),
        ),
        migrations.AddField(
            model_name="botintegration",
            name="telegram_bot_user_name",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Telegram bot @username (for display and deep links)",
                max_length=256,
            ),
        ),
        migrations.AddField(
            model_name="conversation",
            name="telegram_user_id",
            field=models.CharField(
                blank=True,
                default=None,
                help_text="User's Telegram user ID (mandatory if platform is Telegram)",
                max_length=256,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="conversation",
            name="telegram_user_name",
            field=models.TextField(
                blank=True,
                default="",
                help_text="User's Telegram display name (only for display)",
            ),
        ),
        migrations.AlterField(
            model_name="botintegration",
            name="platform",
            field=models.IntegerField(
                choices=[
                    (1, "Facebook Messenger"),
                    (2, "Instagram"),
                    (3, "WhatsApp"),
                    (4, "Slack"),
                    (5, "Web"),
                    (6, "Twilio"),
                    (7, "Telegram"),
                ],
                help_text="The platform that the bot is integrated with",
            ),
        ),
        migrations.AlterField(
            model_name="savedrun",
            name="platform",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, "Facebook Messenger"),
                    (2, "Instagram"),
                    (3, "WhatsApp"),
                    (4, "Slack"),
                    (5, "Web"),
                    (6, "Twilio"),
                    (7, "Telegram"),
                ],
                default=None,
                null=True,
            ),
        ),
        migrations.AddIndex(
            model_name="conversation",
            index=models.Index(
                fields=["bot_integration", "telegram_user_id"],
                name="bots_conver_bot_int_3ff5c6_idx",
            ),
        ),
    ]
