# Generated by Django 5.1.3 on 2026-04-30 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bots", "0116_botintegration_telegram_bot_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="savedrun",
            name="is_cancelled",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="botintegration",
            name="public_visibility",
            field=models.IntegerField(
                choices=[
                    (1, "Private"),
                    (2, "View Only"),
                    (4, "Editable"),
                    (3, "Internal (Deprecated)"),
                ],
                default=1,
                help_text="Controls whether this bot integration is listed on gooey.ai/chat & whether the demo button is shown",
            ),
        ),
        migrations.AlterField(
            model_name="publishedrun",
            name="public_access",
            field=models.IntegerField(
                choices=[
                    (1, "Private"),
                    (2, "View Only"),
                    (4, "Editable"),
                    (3, "Internal (Deprecated)"),
                ],
                default=2,
            ),
        ),
        migrations.AlterField(
            model_name="publishedrun",
            name="workspace_access",
            field=models.IntegerField(
                choices=[
                    (1, "Private"),
                    (2, "View Only"),
                    (4, "Editable"),
                    (3, "Internal (Deprecated)"),
                ],
                default=4,
            ),
        ),
        migrations.AlterField(
            model_name="publishedrunversion",
            name="public_access",
            field=models.IntegerField(
                choices=[
                    (1, "Private"),
                    (2, "View Only"),
                    (4, "Editable"),
                    (3, "Internal (Deprecated)"),
                ],
                default=1,
            ),
        ),
        migrations.AlterField(
            model_name="publishedrunversion",
            name="workspace_access",
            field=models.IntegerField(
                choices=[
                    (1, "Private"),
                    (2, "View Only"),
                    (4, "Editable"),
                    (3, "Internal (Deprecated)"),
                ],
                default=4,
            ),
        ),
    ]
