# Generated by Django 5.1.3 on 2026-04-30 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0117_savedrun_is_cancelled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedrun',
            name='celery_task_id',
            field=models.CharField(blank=True, default='', help_text='ID of the Celery task currently executing this run, used to revoke it on cancel.', max_length=255),
        ),
    ]
