# Generated by Django 5.1.3 on 2026-05-28 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bots", "0118_savedrun_celery_task_id"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="savedrun",
            options={},
        ),
        migrations.AddField(
            model_name="savedrun",
            name="redirect_url",
            field=models.TextField(
                blank=True,
                default="",
                help_text="The URL to redirect the user to after the builder run is complete",
            ),
        ),
    ]
