# Generated by Django 5.1.3 on 2026-06-03 10:51

import bots.custom_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bots", "0119_tag_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="tag",
            name="featured",
            field=models.BooleanField(
                default=False,
                help_text="If checked, this tag is featured, ordered by priority.",
            ),
        ),
        migrations.AddField(
            model_name="tag",
            name="hide",
            field=models.BooleanField(
                default=False,
                help_text="If checked, this tag is hidden and not shown anywhere.",
            ),
        ),
        migrations.AddField(
            model_name="tag",
            name="landing_page",
            field=bots.custom_fields.CustomURLField(
                blank=True,
                default="",
                help_text="Optional landing page URL for this tag.",
                max_length=2048,
            ),
        ),
        migrations.AlterField(
            model_name="tag",
            name="featured_priority",
            field=models.IntegerField(
                default=1, help_text="Higher priority tags are shown first."
            ),
        ),
    ]
