# Generated by Django 5.1.3 on 2026-06-05 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_users", "0030_appuser_last_login_at"),
        ("bots", "0119_alter_savedrun_options_savedrun_redirect_url"),
        ("workspaces", "0016_alter_workspacemembership_balance"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="savedrun",
            name="bots_savedr_workflo_47a100_idx",
        ),
        migrations.RemoveIndex(
            model_name="savedrun",
            name="bots_savedr_workflo_19c1a2_idx",
        ),
        migrations.RemoveIndex(
            model_name="savedrun",
            name="bots_savedr_workflo_980e2b_idx",
        ),
        migrations.AlterUniqueTogether(
            name="savedrun",
            unique_together={("platform", "user_message_id"), ("run_id", "uid")},
        ),
        migrations.AddIndex(
            model_name="savedrun",
            index=models.Index(
                fields=["workflow", "uid", "-updated_at"],
                name="bots_savedr_workflo_5736aa_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="savedrun",
            index=models.Index(
                fields=["workflow", "workspace", "-updated_at"],
                name="bots_savedr_workflo_cc2d5b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="savedrun",
            index=models.Index(
                fields=["workflow", "uid", "workspace", "-updated_at"],
                name="bots_savedr_workflo_e7e3f0_idx",
            ),
        ),
    ]
