# Generated by Django 5.1.3 on 2026-05-19 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bots", "0120_remove_savedrun_bots_savedr_workflo_47a100_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tag",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
    ]
