# Generated by Django 5.1.3 on 2026-06-13 04:31

from django.db import migrations, models

from bots.models import SavedRun


def backfill_surface_from_is_api_call(apps, schema_editor):
    SavedRunModel = apps.get_model("bots", "SavedRun")
    db_alias = schema_editor.connection.alias
    SavedRunModel.objects.using(db_alias).filter(is_api_call=True).update(
        surface=SavedRun.Surface.api
    )


class Migration(migrations.Migration):

    dependencies = [
        ("bots", "0120_remove_savedrun_bots_savedr_workflo_47a100_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="savedrun",
            name="surface",
            field=models.IntegerField(
                choices=[
                    (0, "Run"),
                    (1, "API"),
                    (2, "Deployment"),
                    (3, "Builder Prompt"),
                    (4, "Builder Child"),
                    (5, "Tool Call"),
                    (6, "Internal"),
                    (7, "Analysis"),
                    (8, "Export"),
                    (9, "Bulk"),
                ],
                default=0,
                help_text="Where this run was created.<br><br>Run: A run created from the UI playground directly by the user.<br>API: Called by an API.<br>Deployment: Called by a bot integration.<br>Builder Prompt: A prompt submitted to the Gooey builder.<br>Builder Child: A child run created by the Gooey builder.<br>Tool Call: Any tool calls made by a workflow.<br>Internal: Any internal calls made by the app, e.g. QR code or icon generator.<br>Analysis: A run created from the bot integration analysis feature.<br>Export: A run created from the scheduled bot integration export feature.<br>Bulk: A run created from the bulk runner.",
            ),
        ),
        migrations.RunPython(
            backfill_surface_from_is_api_call,
            migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name="savedrun",
            name="is_api_call",
            field=models.BooleanField(
                default=False, help_text="(Deprecated) Use surface instead."
            ),
        ),
    ]
