# Generated by Django 5.1.3 on 2026-06-09 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bots", "0121_tag_home_page_fields_and_workflowmetadata_icons"),
        ("workspaces", "0016_alter_workspacemembership_balance"),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkspaceRecentWorkflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(blank=True, default=None, max_length=128, null=True)),
                ('last_used_at', models.DateTimeField()),
                ('last_saved_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='bots.savedrun')),
                ('published_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recent_usages', to='bots.publishedrun')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recent_workflows', to='workspaces.workspace')),
            ],
            options={
                'indexes': [models.Index(fields=['workspace', 'uid', '-last_used_at'], name='bots_worksp_workspa_eb1c01_idx')],
                'unique_together': {('workspace', 'uid', 'published_run')},
            },
        ),
    ]
