# Generated by Django 5.1.3 on 2026-06-13 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bots", "0121_savedrun_surface_alter_savedrun_is_api_call"),
    ]

    operations = [
        migrations.AlterField(
            model_name="savedrun",
            name="surface",
            field=models.IntegerField(
                choices=[
                    (0, "Run"),
                    (1, "API"),
                    (2, "Deployment"),
                    (3, "Builder Prompt"),
                    (4, "Builder"),
                    (5, "Tool Call"),
                    (6, "Internal"),
                    (7, "Analysis"),
                    (8, "Export"),
                    (9, "Bulk"),
                ],
                default=0,
                help_text="Where this run was created.<br><br>Run: A run created from the UI playground directly by the user.<br>API: Called by an API.<br>Deployment: Called by a bot integration.<br>Builder Prompt: A prompt submitted to the Gooey builder.<br>Builder: A child run created by the Gooey builder.<br>Tool Call: Any tool calls made by a workflow.<br>Internal: Any internal calls made by the app, e.g. QR code or icon generator.<br>Analysis: A run created from the bot integration analysis feature.<br>Export: A run created from the scheduled bot integration export feature.<br>Bulk: A run created from the bulk runner.",
            ),
        ),
    ]
