# Generated by Django 5.1.3 on 2026-06-17 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_users", "0031_remove_appuser_app_users_a_email_2228c5_idx_and_more"),
        ("bots", "0123_alter_publishedrun_workflow_alter_savedrun_workflow_and_more"),
        ("workspaces", "0016_alter_workspacemembership_balance"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="savedrun",
            index=models.Index(
                fields=["uid", "workspace", "surface", "-updated_at"],
                name="bots_savedr_uid_b36a38_idx",
            ),
        ),
    ]
