# Generated by Django 5.1.3 on 2026-06-19 02:18

import bots.custom_fields
from django.db import migrations, models


def backfill_tag_hidden(apps, schema_editor):
    # Tag visibility moved from `featured_priority=0` (the old "not shown at all"
    # sentinel) to the new `hidden` boolean. Carry the previously-hidden tags over
    # so they don't suddenly reappear in tag pickers / the home page.
    Tag = apps.get_model("bots", "Tag")
    db_alias = schema_editor.connection.alias
    Tag.objects.using(db_alias).filter(featured_priority=0).update(hidden=True)


class Migration(migrations.Migration):
    dependencies = [
        ("app_users", "0031_remove_appuser_app_users_a_email_2228c5_idx_and_more"),
        ("bots", "0124_savedrun_bots_savedr_uid_b36a38_idx"),
        ("workspaces", "0016_alter_workspacemembership_balance"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tag",
            options={},
        ),
        migrations.AddField(
            model_name="publishedrun",
            name="is_featured",
            field=models.BooleanField(
                default=False,
                help_text="If checked, this workflow is featured on homepage.",
            ),
        ),
        migrations.AddField(
            model_name="tag",
            name="color",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Hex color associated with this tag, e.g. #4d8af0",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="tag",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="tag",
            name="fa_icon",
            field=models.TextField(
                blank=True,
                default="",
                help_text='Font Awesome icon HTML, e.g. &lt;i class="fa-regular fa-tag"&gt;&lt;/i&gt;',
            ),
        ),
        migrations.AddField(
            model_name="tag",
            name="hidden",
            field=models.BooleanField(
                default=False,
                help_text="If checked, this tag is hidden and not shown anywhere.",
            ),
        ),
        migrations.AddField(
            model_name="tag",
            name="is_featured",
            field=models.BooleanField(
                default=False,
                help_text="If checked, this tag is featured, ordered by priority.",
            ),
        ),
        migrations.AddField(
            model_name="tag",
            name="landing_page",
            field=bots.custom_fields.CustomURLField(
                blank=True,
                default="",
                help_text="Optional landing page URL for this tag.",
                max_length=2048,
            ),
        ),
        migrations.AddField(
            model_name="workflowmetadata",
            name="color",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Hex color associated with this workflow, e.g. #4d8af0",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="workflowmetadata",
            name="fa_icon",
            field=models.TextField(
                blank=True,
                default="",
                help_text='Font Awesome icon HTML, e.g. &lt;i class="fa-regular fa-tag"&gt;&lt;/i&gt;',
            ),
        ),
        migrations.AddField(
            model_name="workflowmetadata",
            name="is_featured",
            field=models.BooleanField(
                default=False,
                help_text="If checked, this workflow is featured on homepage, ordered by priority.",
            ),
        ),
        migrations.AddField(
            model_name="workflowmetadata",
            name="priority",
            field=models.IntegerField(
                default=1, help_text="Higher priority workflows are shown first."
            ),
        ),
        migrations.AlterField(
            model_name="publishedrun",
            name="example_priority",
            field=models.IntegerField(
                default=1,
                help_text="Priority of the example in the example list & homepage",
            ),
        ),
        migrations.AlterField(
            model_name="tag",
            name="featured_priority",
            field=models.IntegerField(
                default=1, help_text="Higher priority tags are shown first."
            ),
        ),
        migrations.AddIndex(
            model_name="publishedrun",
            index=models.Index(
                condition=models.Q(("is_featured", True)),
                fields=["workflow", "-example_priority"],
                name="bots_publis_feat_home_idx",
            ),
        ),
        migrations.RunPython(backfill_tag_hidden, migrations.RunPython.noop),
    ]
