# Generated by Django 5.1.3 on 2026-07-02 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_users", "0032_alter_appuser_uid"),
        ("bots", "0125_alter_tag_options_publishedrun_is_featured_tag_color_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="publishedrun",
            name="workflow_metadata",
            field=models.ForeignObject(
                blank=True,
                from_fields=["workflow"],
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="bots.workflowmetadata",
                to_fields=["workflow"],
            ),
        ),
        migrations.AddField(
            model_name="savedrun",
            name="created_by",
            field=models.ForeignObject(
                blank=True,
                from_fields=["uid"],
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="saved_runs",
                to="app_users.appuser",
                to_fields=["uid"],
            ),
        ),
        migrations.AddField(
            model_name="savedrun",
            name="workflow_metadata",
            field=models.ForeignObject(
                blank=True,
                from_fields=["workflow"],
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="saved_runs",
                to="bots.workflowmetadata",
                to_fields=["workflow"],
            ),
        ),
    ]
