# Generated by Django 5.1.3 on 2026-06-17 08:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0125_alter_tag_options_publishedrun_is_featured_tag_color_and_more'),
        ('workspaces', '0016_alter_workspacemembership_balance'),
    ]

    operations = [
        migrations.CreateModel(
            name='RunConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(db_index=True, max_length=255)),
                ('workflow', models.IntegerField()),
                ('surface', models.IntegerField(choices=[(0, 'Run'), (1, 'API'), (2, 'Deployment'), (3, 'Builder Prompt'), (4, 'Builder'), (5, 'Tool Call'), (6, 'Internal'), (7, 'Analysis'), (8, 'Export'), (9, 'Bulk')])),
                ('title', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_run', models.ForeignKey(blank=True, default=None, help_text='The latest turn of this conversation (resume target + list preview).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='bots.savedrun')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='run_conversations', to='workspaces.workspace')),
            ],
        ),
        migrations.AddField(
            model_name='savedrun',
            name='conversation',
            field=models.ForeignKey(blank=True, default=None, help_text='The conversation this run is a turn of (VideoBots grouping).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='bots.runconversation'),
        ),
        migrations.AddIndex(
            model_name='runconversation',
            index=models.Index(fields=['workflow', 'workspace', 'surface', '-updated_at'], name='bots_runcon_workflo_e34598_idx'),
        ),
        migrations.AddIndex(
            model_name='runconversation',
            index=models.Index(fields=['workflow', 'uid', 'surface', '-updated_at'], name='bots_runcon_workflo_596447_idx'),
        ),
    ]
