# Generated by Django 5.1.3 on 2026-07-14 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_users", "0032_alter_appuser_uid"),
        ("bots", "0126_publishedrun_workflow_metadata_savedrun_created_by_and_more"),
        ("workspaces", "0016_alter_workspacemembership_balance"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="savedrun",
            index=models.Index(
                fields=["workspace", "surface", "-updated_at"],
                name="bots_savedr_workspa_06044f_idx",
            ),
        ),
    ]
