# Generated by Django 5.1.3 on 2026-07-18 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bots", "0127_savedrun_bots_savedr_workspa_06044f_idx"),
    ]

    operations = [
        migrations.AlterField(
            model_name="savedrun",
            name="run_id",
            field=models.CharField(
                blank=True, default=None, max_length=128, null=True, unique=True
            ),
        ),
    ]
