# Generated by Django 5.1.3 on 2026-07-18 08:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0127_savedrun_bots_savedr_workspa_06044f_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True)),
                ('bot_conversation', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='message_thread', to='bots.conversation')),
                ('first_run', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='threads_as_first_run', to='bots.savedrun')),
                ('last_run', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='threads_as_last_run', to='bots.savedrun')),
            ],
        ),
        migrations.AddField(
            model_name='savedrun',
            name='message_thread',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='saved_runs', to='bots.messagethread'),
        ),
    ]
