# Generated by Django 5.1.3 on 2026-07-17 05:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bots", "0127_savedrun_bots_savedr_workspa_06044f_idx"),
    ]

    operations = [
        migrations.CreateModel(
            name="RunConversation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.TextField(blank=True)),
                (
                    "bot_conversation",
                    models.OneToOneField(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="run_conversation",
                        to="bots.conversation",
                    ),
                ),
                (
                    "first_msg",
                    models.ForeignKey(
                        help_text="First run of this conversation.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="starting_conversations",
                        to="bots.savedrun",
                    ),
                ),
                (
                    "last_msg",
                    models.OneToOneField(
                        help_text="Current latest turn of this conversation.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="run_conversation",
                        to="bots.savedrun",
                    ),
                ),
                (
                    "messages",
                    models.ManyToManyField(
                        help_text="Runs that make up the turns of this conversation.",
                        to="bots.savedrun",
                    ),
                ),
            ],
        ),
    ]
