# Generated by Django 5.1.3 on 2026-07-22 19:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0129_messagethread_savedrun_message_thread'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagethread',
            name='last_run',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='thread_as_last_run', to='bots.savedrun'),
        ),
    ]
