# Generated by Django 5.1.3 on 2026-08-26 00:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bots", "0131_alter_savedrun_surface"),
    ]

    operations = [
        migrations.AddField(
            model_name="botintegration",
            name="new_conversation_button_text",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Response sent when the user starts a new conversation (e.g. by tapping 📝 New)",
            ),
        ),
        migrations.AddField(
            model_name="botintegration",
            name="show_new_conversation_button",
            field=models.BooleanField(
                default=True,
                help_text="Show a 📝 New option to start a new conversation (whatsapp only)",
            ),
        ),
    ]
