# Generated by Django 5.1.3 on 2026-09-21 13:18

import bots.custom_fields
import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0131_alter_savedrun_surface'),
    ]

    operations = [
        migrations.AddField(
            model_name='publishedrun',
            name='banner_url',
            field=bots.custom_fields.CustomURLField(blank=True, default='', max_length=2048),
        ),
        migrations.AddField(
            model_name='publishedrun',
            name='builder_prompts',
            field=models.JSONField(blank=True, default=list, help_text="Up to 4 prompts shown as the Gooey Builder's starters."),
        ),
        migrations.AddField(
            model_name='publishedrun',
            name='headline',
            field=bots.custom_fields.StrippedTextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='publishedrun',
            name='more_info_text',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='publishedrun',
            name='more_info_url',
            field=bots.custom_fields.CustomURLField(blank=True, default='', max_length=2048),
        ),
        migrations.AddField(
            model_name='publishedrun',
            name='sdgs',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(choices=[(1, 'No Poverty'), (2, 'Zero Hunger'), (3, 'Good Health and Well-being'), (4, 'Quality Education'), (5, 'Gender Equality'), (6, 'Clean Water and Sanitation'), (7, 'Affordable and Clean Energy'), (8, 'Decent Work and Economic Growth'), (9, 'Industry, Innovation and Infrastructure'), (10, 'Reduced Inequalities'), (11, 'Sustainable Cities and Communities'), (12, 'Responsible Consumption and Production'), (13, 'Climate Action'), (14, 'Life Below Water'), (15, 'Life on Land'), (16, 'Peace, Justice and Strong Institutions'), (17, 'Partnerships for the Goals')]), blank=True, default=list, help_text='UN Sustainable Development Goals this workflow contributes to.', size=None),
        ),
        migrations.AddField(
            model_name='publishedrun',
            name='stats_title',
            field=models.CharField(blank=True, default='', help_text='Heading above the stat cards. Defaults to "Community Engagement".', max_length=64),
        ),
        migrations.AddField(
            model_name='publishedrun',
            name='video_url',
            field=bots.custom_fields.CustomURLField(blank=True, default='', max_length=2048),
        ),
        migrations.CreateModel(
            name='PublishedRunStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(help_text='e.g. "1800+"', max_length=32)),
                ('label', models.CharField(help_text='e.g. "Farmers supported"', max_length=64)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='bots.publishedrun')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
