# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    -   id: end-of-file-fixer
    -   id: check-yaml
-   repo: local
    hooks:
    -   id: ruff-lint
        name: ruff-lint
        entry: poetry run ruff check --fix --force-exclude
        language: system
        types: [python]
    -   id: ruff-format
        name: ruff-format
        entry: poetry run ruff format --force-exclude
        language: system
        types: [python]
-   repo: https://github.com/gitleaks/gitleaks
    rev: v8.18.4
    hooks:
    -   id: gitleaks
