steps:
  - name: 'gcr.io/kaniko-project/executor:latest'
    args:
      - '--destination=us-central1-docker.pkg.dev/dara-c1b52/cloudbuild-pytest/gooey-server:$COMMIT_SHA'
      - '--cache=true'
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    args:
      - '-c'
      - |
        gcloud secrets versions access latest --secret="gooey-server-pytest-secrets" > /workspace/.env
        gcloud secrets versions access latest --secret="gooey-server-pytest-service-account-key" > /workspace/serviceAccountKey.json
    entrypoint: bash
  - name: gcr.io/cloud-builders/docker
    entrypoint: docker-compose
    args:
      - 'up'
      - '--exit-code-from=pytest'
      - '--abort-on-container-exit'
    env:
      - 'COMMIT_SHA=$COMMIT_SHA'
options:
  pool:
    name: projects/dara-c1b52/locations/us-central1/workerPools/gooey
