[tool.poetry]
name = "ddgai"
version = "0.1.0"
description = ""
authors = ["Dev Aggarwal <devxpy@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
streamlit = "^1.12.2"
openai = "^0.23.0"
python-decouple = "^3.6"
protobuf = "3.20.1"
requests = "^2.28.1"
glom = "^22.1.0"
parse = "^1.19.0"
html2text = "^2020.1.16"
pandas = "^1.5.0"
google-cloud-firestore = "^2.7.0"
streamlit-nested-layout = "^0.1.1"
replicate = "^0.4.0"
fastapi = "^0.85.0"
uvicorn = {extras = ["standard"], version = "^0.18.3"}
firebase-admin = "^6.0.0"
# mediapipe for M1 macs
mediapipe-silicon = {version = "^0.8.11", markers = "platform_machine == 'arm64'", platform = "darwin"}
# mediapipe for others
mediapipe = {version = "^0.8.11", markers = "platform_machine != 'arm64'"}
furl = "^2.1.3"

[tool.poetry.group.dev.dependencies]
mypy = "^0.971"
watchdog = "^2.1.9"
ipython = "^8.5.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
