# Generated by Django 4.2.7 on 2024-07-29 21:54

from django.db import migrations, models
import django.utils.timezone
import static_pages.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StaticPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(default=uuid.UUID('142821e6-4df5-11ef-bbec-5e2196b992a2'), editable=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('path', models.CharField(max_length=100)),
                ('zip_file', models.FileField(default=None, upload_to=static_pages.models.zip_file_upload_to)),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('disable_page_wrapper', models.BooleanField(default=False)),
            ],
        ),
    ]
