# Generated by Django 5.1.3 on 2026-05-19 10:17

import bots.custom_fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("bots", "0119_tag_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkflowTab",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=64)),
                ("icon", models.TextField(blank=True, default="")),
                (
                    "priority",
                    models.IntegerField(
                        default=1,
                        help_text="Higher priority tabs are shown first. If 0, then the tab is not shown at all.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Workflow Tab",
                "verbose_name_plural": "Workflow Tabs",
                "ordering": ["-priority", "id"],
            },
        ),
        migrations.CreateModel(
            name="IndustryTile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "priority",
                    models.IntegerField(
                        default=1,
                        help_text="Higher priority tiles are shown first. If 0, then the tile is not shown at all.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tag",
                    models.ForeignKey(
                        help_text="Workflows tagged with this Tag are counted on the tile.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="bots.tag",
                    ),
                ),
            ],
            options={
                "ordering": ["-priority", "id"],
            },
        ),
        migrations.CreateModel(
            name="NewsItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("headline", models.CharField(max_length=200)),
                (
                    "tag",
                    models.CharField(
                        help_text='Freeform label, e.g. "Event", "Product", "Case Study".',
                        max_length=64,
                    ),
                ),
                (
                    "photo_url",
                    bots.custom_fields.CustomURLField(
                        blank=True, default="", max_length=2048
                    ),
                ),
                ("publish_date", models.DateField()),
                (
                    "url",
                    models.CharField(
                        help_text="Absolute URL the card links to.", max_length=500
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-publish_date", "-id"],
                "indexes": [
                    models.Index(
                        fields=["-publish_date"], name="cms_newsite_publish_943c2f_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="WorkflowCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "priority",
                    models.IntegerField(
                        default=1,
                        help_text="Higher priority cards are shown first. If 0, then the card is not shown at all.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "recipe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="bots.publishedrun",
                    ),
                ),
                (
                    "workflow_tab",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cards",
                        to="cms.workflowtab",
                    ),
                ),
            ],
            options={
                "ordering": ["-priority", "id"],
            },
        ),
    ]
