# Generated by Django 5.1.3 on 2026-06-19 02:18

import bots.custom_fields
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NewsItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("headline", models.CharField(max_length=200)),
                (
                    "tag",
                    models.CharField(
                        help_text='Freeform label, e.g. "Event", "Product", "Case Study".',
                        max_length=64,
                    ),
                ),
                (
                    "photo_url",
                    bots.custom_fields.CustomURLField(
                        blank=True, default="", max_length=2048
                    ),
                ),
                (
                    "publish_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "url",
                    bots.custom_fields.CustomURLField(
                        default="", help_text="News item URL.", max_length=2048
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
