# Generated by Django 5.1.3 on 2025-09-23 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("usage_costs", "0037_alter_modelpricing_model_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="VideoModelSpec",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.TextField(
                        help_text="The name of the model to be used in user-facing API calls. WARNING: Don't edit this field after it's been used in a workflow.",
                        unique=True,
                    ),
                ),
                (
                    "label",
                    models.TextField(
                        help_text="The label of the model to be used in the UI."
                    ),
                ),
                (
                    "model_id",
                    models.TextField(
                        help_text="The internal API provider / huggingface model id."
                    ),
                ),
                (
                    "schema",
                    models.JSONField(
                        default=dict, help_text="The schema of the model parameters."
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "pricing",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        help_text="The pricing of the model. Only for display purposes. The actual pricing lookup uses the model_id, so make sure the video model's model_id matches the pricing's model_id.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="video_model_specs",
                        to="usage_costs.modelpricing",
                    ),
                ),
            ],
        ),
    ]
