# Generated by Django 5.1.3 on 2025-10-01 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_models", "0001_initial"),
        ("usage_costs", "0037_alter_modelpricing_model_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="videomodelspec",
            name="pricing",
            field=models.ForeignKey(
                blank=True,
                default=None,
                help_text="The pricing of the model. Only for display purposes. The actual pricing lookup uses the model_id, so make sure the video model's model_id matches the pricing's model_id.To setup a price multiplier, create a WorkflowMetadata for the workflow and set the price_multiplier field.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="video_model_specs",
                to="usage_costs.modelpricing",
            ),
        ),
    ]
