# Generated by Django 5.1.3 on 2025-10-17 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_models", "0002_alter_videomodelspec_pricing"),
    ]

    operations = [
        migrations.AddField(
            model_name="videomodelspec",
            name="category",
            field=models.IntegerField(
                choices=[(1, "Video"), (2, "Audio")],
                help_text="Model category: generates Audio, Video, etc.",
                null=True,
            ),
        ),
    ]
