# Generated by Django 5.1.3 on 2026-01-04 21:03

import bots.custom_fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_models", "0003_aimodelspec_delete_videomodelspec"),
    ]

    operations = [
        migrations.AddField(
            model_name="aimodelspec",
            name="api_key",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="aimodelspec",
            name="base_url",
            field=bots.custom_fields.CustomURLField(
                blank=True, default="", max_length=2048
            ),
        ),
        migrations.AddField(
            model_name="aimodelspec",
            name="is_deprecated",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="aimodelspec",
            name="llm_context_window",
            field=models.IntegerField(default=0, verbose_name="Context Window"),
        ),
        migrations.AddField(
            model_name="aimodelspec",
            name="llm_is_audio_model",
            field=models.BooleanField(default=False, verbose_name="Audio Model"),
        ),
        migrations.AddField(
            model_name="aimodelspec",
            name="llm_is_chat_model",
            field=models.BooleanField(default=True, verbose_name="Chat Model"),
        ),
        migrations.AddField(
            model_name="aimodelspec",
            name="llm_is_thinking_model",
            field=models.BooleanField(default=False, verbose_name="Thinking Model"),
        ),
        migrations.AddField(
            model_name="aimodelspec",
            name="llm_is_vision_model",
            field=models.BooleanField(default=False, verbose_name="Vision Model"),
        ),
        migrations.AddField(
            model_name="aimodelspec",
            name="llm_max_output_tokens",
            field=models.IntegerField(default=0, verbose_name="Max Output Tokens"),
        ),
        migrations.AddField(
            model_name="aimodelspec",
            name="llm_supports_input_audio",
            field=models.BooleanField(
                default=False, verbose_name="Supports Input Audio"
            ),
        ),
        migrations.AddField(
            model_name="aimodelspec",
            name="llm_supports_json",
            field=models.BooleanField(default=False, verbose_name="Supports JSON"),
        ),
        migrations.AddField(
            model_name="aimodelspec",
            name="llm_supports_temperature",
            field=models.BooleanField(
                default=True, verbose_name="Supports Temperature"
            ),
        ),
        migrations.AddField(
            model_name="aimodelspec",
            name="provider",
            field=models.IntegerField(
                choices=[
                    (1, "OpenAI"),
                    (16, "Openai Audio"),
                    (4, "Azure OpenAI"),
                    (2, "Google"),
                    (3, "TogetherAI"),
                    (6, "Anthropic"),
                    (7, "groq"),
                    (8, "Fireworks AI"),
                    (9, "Mistral AI"),
                    (10, "sarvam.ai"),
                    (11, "fal.ai"),
                    (12, "Twilio"),
                    (13, "sea-lion.ai"),
                    (14, "PublicAI"),
                    (15, "Modal"),
                    (5, "Azure Kubernetes Service"),
                ],
                default=15,
                help_text="The API provider for this model.",
            ),
        ),
        migrations.AddField(
            model_name="aimodelspec",
            name="redirect_to",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="redirect_to_ai_model_specs",
                to="ai_models.aimodelspec",
            ),
        ),
        migrations.AddField(
            model_name="aimodelspec",
            name="version",
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name="aimodelspec",
            name="category",
            field=models.IntegerField(
                choices=[(1, "🎥 Video"), (2, "🎵 Audio"), (3, "💬 LLM")],
                default=1,
                help_text="Model category: generates Audio, Video, etc.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="aimodelspec",
            name="schema",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="The schema of the model parameters.",
            ),
        ),
    ]
