# Generated by Django 5.1.3 on 2026-03-26 06:40

import bots.custom_fields
import re
import django.db.models.deletion
from django.db import migrations, models


AI_MODEL_CREATORS = {
    "AISingapore": {
        "website_url": "https://aisingapore.org/",
        "photo_url": "https://storage.googleapis.com/dara-c1b52.appspot.com/daras_ai/media/ai-model-creators/aisingapore.png",
    },
    "Beatoven": {
        "website_url": "https://www.beatoven.ai/",
        "photo_url": "https://storage.googleapis.com/dara-c1b52.appspot.com/daras_ai/media/ai-model-creators/beatoven.png",
    },
    "Anthropic": {
        "website_url": "https://www.anthropic.com/",
        "photo_url": "https://storage.googleapis.com/dara-c1b52.appspot.com/daras_ai/media/ai-model-creators/anthropic.png",
    },
    "DeepSeek": {
        "website_url": "https://www.deepseek.com/",
        "photo_url": "https://storage.googleapis.com/dara-c1b52.appspot.com/daras_ai/media/ai-model-creators/deepseek.ico",
    },
    "Google": {
        "website_url": "https://deepmind.google/models/gemini/",
        "photo_url": "https://storage.googleapis.com/dara-c1b52.appspot.com/daras_ai/media/ai-model-creators/google.png",
    },
    "Groq": {
        "website_url": "https://groq.com/",
        "photo_url": "https://storage.googleapis.com/dara-c1b52.appspot.com/daras_ai/media/ai-model-creators/groq.png",
    },
    "Jacaranda": {
        "website_url": "https://jacarandahealth.org/",
        "photo_url": "https://storage.googleapis.com/dara-c1b52.appspot.com/daras_ai/media/ai-model-creators/jacaranda.png",
    },
    "KissanAI": {
        "website_url": "https://dhenu.ai/",
        "photo_url": "https://storage.googleapis.com/dara-c1b52.appspot.com/daras_ai/media/ai-model-creators/kissanai.webp",
    },
    "Kling AI": {
        "website_url": "https://klingai.com/global/",
        "photo_url": "https://storage.googleapis.com/dara-c1b52.appspot.com/daras_ai/media/ai-model-creators/kling-ai.png",
    },
    "Lightricks": {
        "website_url": "https://www.lightricks.com/",
        "photo_url": "https://storage.googleapis.com/dara-c1b52.appspot.com/daras_ai/media/ai-model-creators/lightricks.png",
    },
    "Meta AI": {
        "website_url": "https://ai.meta.com/",
        "photo_url": "https://storage.googleapis.com/dara-c1b52.appspot.com/daras_ai/media/ai-model-creators/meta-ai.svg",
    },
    "MiniMax": {
        "website_url": "https://www.minimax.io/",
        "photo_url": "https://storage.googleapis.com/dara-c1b52.appspot.com/daras_ai/media/ai-model-creators/minimax.ico",
    },
    "Mirelo AI": {
        "website_url": "https://www.mirelo.ai/",
        "photo_url": "https://storage.googleapis.com/dara-c1b52.appspot.com/daras_ai/media/ai-model-creators/mirelo-ai.png",
    },
    "Mistral": {
        "website_url": "https://mistral.ai/",
        "photo_url": "https://storage.googleapis.com/dara-c1b52.appspot.com/daras_ai/media/ai-model-creators/mistral.png",
    },
    "Moonshot AI": {
        "website_url": "https://www.moonshot.ai/",
        "photo_url": "https://storage.googleapis.com/dara-c1b52.appspot.com/daras_ai/media/ai-model-creators/moonshot-ai.ico",
    },
    "OpenAI": {
        "website_url": "https://openai.com/",
        "photo_url": "https://storage.googleapis.com/dara-c1b52.appspot.com/daras_ai/media/ai-model-creators/openai.png",
    },
    "PixVerse": {
        "website_url": "https://pixverse.ai/en/",
        "photo_url": "https://storage.googleapis.com/dara-c1b52.appspot.com/daras_ai/media/ai-model-creators/pixverse.png",
    },
    "Qwen": {
        "website_url": "https://chat.qwen.ai/",
        "photo_url": "https://storage.googleapis.com/dara-c1b52.appspot.com/daras_ai/media/ai-model-creators/qwen.png",
    },
    "Sarvam AI": {
        "website_url": "https://www.sarvam.ai/",
        "photo_url": "https://storage.googleapis.com/dara-c1b52.appspot.com/daras_ai/media/ai-model-creators/sarvam-ai.svg",
    },
    "SwissAI": {
        "website_url": "https://www.swissai.com/",
        "photo_url": "https://storage.googleapis.com/dara-c1b52.appspot.com/daras_ai/media/ai-model-creators/swissai.png",
    },
    "Wan": {
        "website_url": "https://wan.video/",
        "photo_url": "https://storage.googleapis.com/dara-c1b52.appspot.com/daras_ai/media/ai-model-creators/wan.ico",
    },
    "Z.ai": {
        "website_url": "https://chat.z.ai/",
        "photo_url": "https://storage.googleapis.com/dara-c1b52.appspot.com/daras_ai/media/ai-model-creators/z-ai.svg",
    },
    "ai71": {
        "website_url": "https://ai71.ai/",
        "photo_url": "https://storage.googleapis.com/dara-c1b52.appspot.com/daras_ai/media/ai-model-creators/ai71.png",
    },
    "fal.ai": {
        "website_url": "https://fal.ai/",
        "photo_url": "https://storage.googleapis.com/dara-c1b52.appspot.com/daras_ai/media/ai-model-creators/fal-ai.png",
    },
}

NORMALIZED_CREATOR_NAMES = {
    re.sub(r"[^a-z0-9]+", "", creator_name.lower()): creator_name
    for creator_name in AI_MODEL_CREATORS
}

FAMILY_RULES = {
    "Anthropic": ("anthropic", "claude"),
    "Beatoven": ("beatoven",),
    "DeepSeek": ("deepseek",),
    "Google": ("gemini", "gemma", "palm", "veo"),
    "Meta AI": ("meta-llama", "llama 4", "llama 3", "llama2", "meta ai"),
    "Groq": ("groq",),
    "Jacaranda": ("jacaranda", "afrollama"),
    "KissanAI": ("dhenu", "kissan"),
    "Kling AI": ("kling",),
    "Lightricks": ("ltx",),
    "MiniMax": ("minimax",),
    "Mirelo AI": ("mirelo", "sfx-v1"),
    "Mistral": ("mistral", "pixtral", "ministral", "mixtral"),
    "Moonshot AI": ("moonshot", "kimi"),
    "OpenAI": (
        "openai",
        "gpt",
        "chatgpt",
        "codex",
        "babbage",
        "curie",
        "ada",
        "sora",
    ),
    "PixVerse": ("pixverse",),
    "Qwen": ("qwen",),
    "Sarvam AI": ("sarvam",),
    "SwissAI": ("swiss-ai", "swissai", "apertus"),
    "Wan": ("wan/", "wan-", "wan ", "wanv", "wan2", "wan v"),
    "Z.ai": ("glm", "z.ai", "chatglm"),
    "ai71": ("ai71", "agrillm"),
    "AISingapore": ("aisingapore", "sea-lion"),
    "fal.ai": ("mmaudio", "fal.ai", "fal ai", "fal-"),
}


def seed_creators_and_backfill(apps, schema_editor):
    AIModelCreator = apps.get_model("ai_models", "AIModelCreator")
    AIModelSpec = apps.get_model("ai_models", "AIModelSpec")
    db_alias = schema_editor.connection.alias
    creator_objects = AIModelCreator.objects.using(db_alias)
    spec_objects = AIModelSpec.objects.using(db_alias)

    creators = {}
    for creator_name, defaults in AI_MODEL_CREATORS.items():
        creator, _ = creator_objects.update_or_create(
            name=creator_name,
            defaults=defaults,
        )
        creators[creator_name] = creator

    for spec in spec_objects.all().iterator():
        creator_name = infer_creator_name(spec.label or "", spec.model_id or "")
        if not creator_name:
            continue
        creator = creators.get(creator_name)
        if not creator:
            creator, _ = creator_objects.update_or_create(
                name=creator_name,
                defaults=AI_MODEL_CREATORS.get(creator_name, {}),
            )
            creators[creator_name] = creator
        spec_objects.filter(pk=spec.pk).update(creator_id=creator.pk)


def infer_creator_name(label, model_id):
    creator_name = normalize_creator_name(label.partition("•")[2])
    if creator_name:
        return creator_name

    combined = f"{label.lower()} {model_id.lower()}"
    for creator_name, needles in FAMILY_RULES.items():
        if any(needle in combined for needle in needles):
            return creator_name
    return None


def normalize_creator_name(value):
    if not value:
        return None
    cleaned = re.sub(r"\[.*?\]", "", value)
    cleaned = cleaned.split(" via ", 1)[0]
    cleaned = re.sub(r"[^a-z0-9]+", "", cleaned.lower())
    return NORMALIZED_CREATOR_NAMES.get(cleaned)


class Migration(migrations.Migration):
    dependencies = [
        ("ai_models", "0006_aimodelspec_priority"),
    ]

    operations = [
        migrations.CreateModel(
            name="AIModelCreator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(unique=True)),
                (
                    "photo_url",
                    bots.custom_fields.CustomURLField(
                        blank=True, default="", max_length=2048
                    ),
                ),
                (
                    "website_url",
                    bots.custom_fields.CustomURLField(
                        blank=True, default="", max_length=2048
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="aimodelspec",
            name="priority",
            field=models.IntegerField(
                default=1,
                help_text="Display priority for model lists. Higher priority appears first; ties are sorted alphabetically.",
            ),
        ),
        migrations.AddField(
            model_name="aimodelspec",
            name="creator",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ai_model_specs",
                to="ai_models.aimodelcreator",
            ),
        ),
        migrations.RunPython(seed_creators_and_backfill, migrations.RunPython.noop),
    ]
