# Generated by Django 5.1.3 on 2026-03-28 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_models", "0007_aimodelcreator_alter_aimodelspec_priority_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="aimodelcreator",
            name="priority",
            field=models.IntegerField(
                default=1,
                help_text="Sort order: creator priority, creator name, model priority, model label (all descending).",
            ),
        ),
        migrations.AlterField(
            model_name="aimodelspec",
            name="priority",
            field=models.IntegerField(
                default=1,
                help_text="Sort order: creator priority, creator name, model priority, model label (all descending).",
            ),
        ),
    ]
