# Generated by Django 5.1.3 on 2026-03-28 06:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ai_models", "0007_aimodelcreator_alter_aimodelspec_priority_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="aimodelcreator",
            name="priority",
            field=models.IntegerField(
                default=1,
                help_text="Display priority for creator groups in model lists. Higher priority appears first; ties are sorted by creator name descending.",
            ),
        ),
        migrations.AlterField(
            model_name="aimodelspec",
            name="priority",
            field=models.IntegerField(
                default=1,
                help_text="Display priority for models within the same creator group. Higher priority appears first; ties are sorted by label descending.",
            ),
        ),
    ]
