# Generated by Django 5.1.3 on 2026-06-13 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_models", "0008_aimodelcreator_priority"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aimodelspec",
            name="provider",
            field=models.IntegerField(
                choices=[
                    (1, "OpenAI"),
                    (16, "Openai Audio"),
                    (17, "OpenAI Responses"),
                    (4, "Azure OpenAI"),
                    (2, "Google"),
                    (3, "TogetherAI"),
                    (6, "Anthropic [Deprecated]"),
                    (7, "groq"),
                    (8, "Fireworks AI"),
                    (9, "Mistral AI"),
                    (10, "sarvam.ai"),
                    (11, "fal.ai"),
                    (12, "Twilio"),
                    (13, "sea-lion.ai"),
                    (14, "PublicAI"),
                    (15, "Modal"),
                    (5, "Azure Kubernetes Service"),
                ],
                default=15,
                help_text="The API provider for this model.",
            ),
        ),
    ]
