# Generated by Django 5.1.3 on 2026-07-22 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_models', '0009_alter_aimodelspec_provider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aimodelspec',
            name='category',
            field=models.IntegerField(choices=[(1, '🎥 Video'), (2, '🎵 Audio'), (3, '💬 LLM'), (4, '🖼️ Image')], default=1, help_text='Model category: generates Audio, Video, etc.', null=True),
        ),
    ]
