/* Generated by scripts/generate_gui_types.py from gooey_gui/types/about_props.py. Do not edit manually. */

export type SurfaceId = "about" | "editor" | "preview";

/**
 * Who published the workflow, above the panel.
 */
export interface AboutAuthor {
  name: string;
  photo_url: string;
  subtitle: string | null;
  href: string | null;
}
/**
 * One filing pill. The tag renders its own label - it carries an emoji or a flag - so
 * that arrives as markup rather than text.
 */
export interface AboutTag {
  label_html: string;
  href: string;
}
/**
 * Opens a config pane in the workspace beside About.
 */
export interface AboutPaneTarget {
  kind: "pane";
  layout: SingleLayout | SplitLayout;
  editor_pane: string | null;
}
export interface SingleLayout {
  kind: "single";
  surface: SurfaceId;
}
export interface SplitLayout {
  kind: "split";
  primary: SurfaceId;
  secondary: SurfaceId;
}
export interface AboutLinkTarget {
  kind: "link";
  href: string;
}
/**
 * Posts an intent through the page's form, which is how the top bar's chips open their
 * dialogs - `value` is the already-encoded intent.
 */
export interface AboutSubmitTarget {
  kind: "submit";
  value: string;
}
/**
 * One tile: a mark, a chevron, and a label under them.
 */
export interface AboutCard {
  icon_html: string;
  label: string;
  target: AboutPaneTarget | AboutLinkTarget | AboutSubmitTarget;
}
/**
 * A heading and the grid of cards under it.
 */
export interface AboutGroup {
  title: string;
  cards: AboutCard[];
}
/**
 * Everything the About surface draws. Structured rather than pre-rendered html, so the
 * component owns the markup and the payload carries only what varies.
 */
export interface RecipeAboutProps {
  heading: string;
  photo_url: string | null;
  circle_photo: boolean;
  author: AboutAuthor | null;
  share_value: string | null;
  submit_intent_key: string;
  tags: AboutTag[];
  notes: string | null;
  notes_line_clamp: number;
  groups: AboutGroup[];
}
