/* Generated by scripts/generate_gui_types.py from gooey_gui/types/credit_usage_props.py. Do not edit manually. */

export interface CreditUsageSeries {
  id: string;
  title: string;
  credits: number[];
}
export interface CreditUsageRangeOption {
  title: string;
  href: string;
  active: boolean;
}
export interface CreditUsagePageProps {
  title: string;
  workspace_name: string;
  months: string[];
  series: CreditUsageSeries[];
  billing_href: string;
  current_month: string;
  month_options: string[];
  range_href: string;
  presets: CreditUsageRangeOption[];
}
