/* Generated by scripts/generate_gui_types.py from gooey_gui/types/error_snackbar_props.py. Do not edit manually. */

export interface ErrorSnackbarProps {
  message: string;
  snackbar_id: string;
}
