/* Generated by scripts/generate_gui_types.py from gooey_gui/types/history_page_props.py. Do not edit manually. */

export interface SurfaceTabData {
  id: string;
  title: string;
  icon: string | null;
  href: string;
  active: boolean;
}
export interface WorkflowFilterOption {
  id: string;
  title: string;
  href: string;
  active: boolean;
}
export interface HistoryPageProps {
  title: string;
  workflow_options: WorkflowFilterOption[];
  surface_tabs: SurfaceTabData[];
  cards: WorkflowCardData[];
  load_more_href: string | null;
  empty_message: string | null;
}
export interface WorkflowCardData {
  title: string;
  href: string;
  workflow_icon: string | null;
  description: string | null;
  author: AuthorData | null;
  preview: (ChatPreview | MediaPreview | IconPreview) | null;
  updated_at: string | null;
  run_count: number | null;
  access_badge: AccessBadgeData | null;
  change_notes: string | null;
}
export interface AuthorData {
  name: string;
  photo_url: string | null;
}
export interface ChatPreview {
  type: "chat";
  user_message: string | null;
  bot_message: string | null;
}
export interface MediaPreview {
  type: "image" | "video" | "audio";
  url: string;
  preview_img: string | null;
  caption: string | null;
}
export interface IconPreview {
  type: "icon";
  image_url: string | null;
  icon: string | null;
}
export interface AccessBadgeData {
  icon_html: string;
  label: string;
}
