/* Generated by scripts/generate_gui_types.py from gooey_gui/types/recipe_top_bar_props.py. Do not edit manually. */

/**
 * One client-side workspace arrangement in the bar's view selector.
 */
export interface TopBarView {
  slug: "about" | "edit" | "preview" | "split";
  label: string;
  icon: string;
  desktop_only: boolean;
  immersive_on_mobile: boolean;
}
/**
 * The "by <someone>" line under the title.
 */
export interface TopBarAuthor {
  label: string;
  href: string | null;
  photo_url: string | null;
}
/**
 * A connected channel, surfaced as a shortcut chip next to Publish.
 *
 * Either a link (`href`) or a server action (`key`, echoed back through `menu_key`) -
 * VideoBots' demo buttons open a dialog rather than navigating.
 */
export interface TopBarIntegration {
  label: string;
  icon: string;
  href: string | null;
  key: string;
  color: string | null;
}
/**
 * An entry in the title chevron menu or the view overflow.
 */
export interface TopBarMenuItem {
  key: string;
  label: string;
  icon: string;
  href: string | null;
  is_danger: boolean;
}
export interface RecipeTopBarProps {
  title: string;
  photo_url: string | null;
  circle_photo: boolean;
  author: TopBarAuthor | null;
  views: TopBarView[];
  storage_key: string;
  initial_view: "about" | "edit" | "preview" | "split";
  editor_full_width: boolean;
  workspace_href: string;
  workspace_active: boolean;
  immersive_on_mobile: boolean;
  overflow_items: TopBarMenuItem[];
  title_menu_items: TopBarMenuItem[];
  integrations: TopBarIntegration[];
  publish_label: string;
  publish_key: string;
  has_unpublished_changes: boolean;
  api_href: string;
  share_key: string;
  share_icon: string;
  share_copy_url: string;
  menu_key: string;
  run_key: string;
  viewport_wide_key: string;
  run_label: string;
  run_disabled: boolean;
  is_running: boolean;
  cost_label: string;
  cost_href: string;
  cost_title: string;
}
