/* Generated by scripts/generate_gui_types.py from gooey_gui/types/recipe_workspace_props.py. Do not edit manually. */

export type SurfaceId = "about" | "editor" | "preview";
export type SurfaceId1 = "about" | "editor" | "preview";

export interface SingleLayout {
  kind: "single";
  surface: SurfaceId;
}
export interface SplitLayout {
  kind: "split";
  primary: SurfaceId;
  secondary: SurfaceId;
}
export interface WorkspaceView {
  key: string;
  label: string;
  icon_html: string | null;
  layout: SingleLayout | SplitLayout;
  desktop_only: boolean;
}
export interface PageShellConfig {
  storage_key: string;
  initial_layout: SingleLayout | SplitLayout;
  run_layout: SingleLayout | SplitLayout;
  route_layout: (SingleLayout | SplitLayout) | null;
  views: WorkspaceView[];
  narrow_surface: SurfaceId1;
  workspace_href: string;
  workspace_active: boolean;
  active_run_id: string | null;
}
export interface RecipeWorkspaceProps {
  config: PageShellConfig;
}
export interface RecipeSurfaceProps {
  surface: SurfaceId;
}
export interface SessionStateUpdate {
  key: string;
  value: string;
}
export interface RecipeWorkspaceTriggerProps {
  layout: SingleLayout | SplitLayout;
  state_update: SessionStateUpdate | null;
  className: string | null;
}
export interface FontAwesomeIcon {
  kind: "font_awesome";
  class_name: string;
}
export interface PhotoIcon {
  kind: "photo";
  url: string;
}
export interface PanelControlTarget {
  kind: "panel";
  panel_key: string;
  open: boolean;
}
export interface EventControlTarget {
  kind: "event";
  event_name: string;
}
export interface WorkspacePaneControlProps {
  label: string;
  icon: FontAwesomeIcon | PhotoIcon;
  target: PanelControlTarget | EventControlTarget;
  tooltip: string | null;
  show_label: boolean;
  className: string | null;
}
