/* Generated by scripts/generate_gui_types.py from gooey_gui/types/recipe_workspace_props.py. Do not edit manually. */

/**
 * The client-side views of the layout-v2 workspace.
 *
 * Defined here so the generator emits it as a named TypeScript union that `paneState.ts`
 * imports. `daras_ai_v2.tab_spec` re-exports it for recipes.
 */
export type RecipeView = "about" | "edit" | "preview" | "split";
/**
 * One of the two work surfaces. Not a `RecipeView`: these name panes, and only the
 * preview is both.
 */
export type WorkPane = "editor" | "preview";

/**
 * The workspace shell. Takes About, the editor and the preview as its render-tree
 * children, in that order, and decides which are on screen and how wide. All three render
 * every request; switching between them costs no round trip.
 */
export interface RecipeWorkspaceProps {
  storage_key: string;
  initial_view: RecipeView;
  editor_full_width: boolean;
  narrow_pane: WorkPane;
}
/**
 * A button that selects a view, and optionally a pane within it. Wraps its children,
 * so the caller supplies the visual. `state_key`/`state_value` are the pane half.
 */
export interface RecipeWorkspaceTriggerProps {
  storage_key: string;
  initial_view: RecipeView;
  view: RecipeView;
  state_key: string;
  state_value: string;
  className: string;
}
/**
 * A square icon button, or a labelled pill, pinned to a pane's corner.
 */
export interface WorkspacePaneControlProps {
  label: string;
  tooltip: string;
  icon: string;
  photo_url: string;
  show_label: boolean;
  event_name: string;
  className: string;
}
