/* Generated by scripts/generate_gui_types.py from gooey_gui/types/run_timeline_props.py. Do not edit manually. */

export interface RunTimelineProps {
  created_at: string;
  started_at: string;
  finished_at: string;
}
