/* Generated by scripts/generate_gui_types.py from gooey_gui/types/workspace_memory_props.py. Do not edit manually. */

export interface MemoryScope {
  label: string;
}
export interface MemoryEntryDetail {
  icon: string;
  value: string;
}
export interface MemoryEntryRow {
  user_id: string;
  key: string;
  value: unknown;
  scope: MemoryScope;
  details: MemoryEntryDetail[];
  updated_at_label: string;
}
export interface MemoryFilterOption {
  value: string;
  label: string;
  icon: string | null;
}
export interface MemoryFilterField {
  key: string;
  label: string;
  icon: string;
  selected: MemoryFilterOption | null;
}
export interface WorkspaceMemoryTableProps {
  description: string;
  filters: MemoryFilterField[];
  options_url: string;
  search: string;
  entries: MemoryEntryRow[];
  next_page_url: string | null;
  delete_url: string;
}
