# Generated by Django 4.2.7 on 2024-07-22 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='org',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='orginvitation',
            name='last_email_sent_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='orginvitation',
            name='status_changed_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddConstraint(
            model_name='org',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted__isnull', True)), fields=('domain_name',), name='unique_domain_name_when_not_deleted'),
        ),
        migrations.RemoveField(
            model_name='org',
            name='members',
        ),
    ]
