# Generated by Django 4.2.7 on 2024-07-11 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0002_org_logo_alter_org_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='orginvitation',
            name='role',
            field=models.IntegerField(choices=[(1, 'Owner'), (2, 'Admin'), (3, 'Member')], default=3),
        ),
    ]
