# Generated by Django 4.2.7 on 2024-07-15 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0003_orginvitation_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='org',
            name='deleted_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
