# Generated by Django 4.2.7 on 2024-08-12 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_alter_subscription_plan'),
        ('orgs', '0003_remove_org_unique_domain_name_when_not_deleted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='org',
            name='balance',
            field=models.IntegerField(default=0, verbose_name='bal'),
        ),
        migrations.AddField(
            model_name='org',
            name='is_paying',
            field=models.BooleanField(default=False, verbose_name='paid'),
        ),
        migrations.AddField(
            model_name='org',
            name='is_personal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='org',
            name='low_balance_email_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='org',
            name='stripe_customer_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='org',
            name='subscription',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='org', to='payments.subscription'),
        ),
    ]
