# Generated by Django 4.2.7 on 2024-07-16 15:24

from django.db import migrations, models
import django.db.models.manager
import orgs.models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0004_org_deleted_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='org',
            options={'default_manager_name': 'all_objects'},
        ),
        migrations.AlterModelManagers(
            name='org',
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='org',
            name='domain_name',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True, validators=[orgs.models.validate_org_domain_name]),
        ),
    ]
