# Generated by Django 4.2.7 on 2024-08-13 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0004_org_balance_org_is_paying_org_is_personal_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='org',
            constraint=models.UniqueConstraint(models.F('created_by'), condition=models.Q(('deleted__isnull', True), ('is_personal', True)), name='unique_personal_org_per_user'),
        ),
    ]
