# Generated by Django 4.2.5 on 2023-12-13 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("bots", "0049_alter_savedrun_workflow"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("provider", models.CharField(blank=True, default="", max_length=255)),
                ("model", models.TextField(blank=True, verbose_name="model")),
                ("param", models.TextField(blank=True, verbose_name="param")),
                ("notes", models.TextField(blank=True, default="")),
                ("quantity", models.IntegerField(default=1)),
                ("calculation_notes", models.TextField(blank=True, default="")),
                ("cost", models.FloatField(default=0.0)),
                (
                    "run_id",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        help_text="The run that was last saved by the user.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cost",
                        to="bots.savedrun",
                    ),
                ),
            ],
        ),
    ]
