# Generated by Django 5.1.3 on 2025-08-19 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("usage_costs", "0034_alter_modelpricing_model_name"),
        (
            "usage_costs",
            "0034_alter_usagecost_options_alter_modelpricing_category_and_more",
        ),
    ]

    operations = []
