# Generated by Django 5.2.10 on 2026-03-05 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usage_costs", "0039_alter_modelpricing_model_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="modelpricing",
            name="model_name",
            field=models.CharField(
                help_text="The name of the model. Must match the name of the AI Model",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="modelpricing",
            name="provider",
            field=models.IntegerField(
                choices=[
                    (1, "OpenAI"),
                    (16, "Openai Audio"),
                    (17, "OpenAI Responses"),
                    (4, "Azure OpenAI"),
                    (2, "Google"),
                    (3, "TogetherAI"),
                    (6, "Anthropic"),
                    (7, "groq"),
                    (8, "Fireworks AI"),
                    (9, "Mistral AI"),
                    (10, "sarvam.ai"),
                    (11, "fal.ai"),
                    (12, "Twilio"),
                    (13, "sea-lion.ai"),
                    (14, "PublicAI"),
                    (15, "Modal"),
                    (5, "Azure Kubernetes Service"),
                ],
                help_text="The provider of the model. Only used for Display purposes.",
            ),
        ),
    ]
