# Generated by Django 5.1.3 on 2026-05-17 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usage_costs', '0040_alter_modelpricing_model_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelpricing',
            name='provider',
            field=models.IntegerField(choices=[(1, 'OpenAI'), (16, 'Openai Audio'), (17, 'OpenAI Responses'), (4, 'Azure OpenAI'), (2, 'Google'), (3, 'TogetherAI'), (6, 'Anthropic [Deprecated]'), (7, 'groq'), (8, 'Fireworks AI'), (9, 'Mistral AI'), (10, 'sarvam.ai'), (11, 'fal.ai'), (12, 'Twilio'), (13, 'sea-lion.ai'), (14, 'PublicAI'), (15, 'Modal'), (5, 'Azure Kubernetes Service')], help_text='The provider of the model. Only used for Display purposes.'),
        ),
        migrations.AlterField(
            model_name='modelpricing',
            name='sku',
            field=models.IntegerField(choices=[(1, 'LLM Prompt (Text)'), (2, 'LLM Completion'), (3, 'GPU Milliseconds'), (5, 'Image Prompt'), (6, 'Image Generation (Output)'), (7, 'IVR Call'), (8, 'Video Generation'), (9, 'Fal Billable Units')], help_text="The model's SKU. Model ID + SKU should be unique together."),
        ),
        migrations.AlterField(
            model_name='usagecost',
            name='quantity',
            field=models.DecimalField(decimal_places=10, max_digits=20),
        ),
        migrations.AlterField(
            model_name='modelpricing',
            name='category',
            field=models.IntegerField(choices=[(1, 'LLM'), (2, 'Self-Hosted'), (3, 'Image Generation'), (4, 'IVR'), (5, 'Video Generation'), (6, 'Audio Generation')], help_text='The category of the model. Only used for Display purposes.'),
        ),
    ]
