# Generated by Django 5.1.3 on 2026-07-28 15:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("usage_costs", "0041_fal_billable_units_and_decimal_quantity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="modelpricing",
            name="provider",
            field=models.IntegerField(
                choices=[
                    (1, "OpenAI"),
                    (16, "Openai Audio"),
                    (17, "OpenAI Responses"),
                    (18, "LiteLLM Responses"),
                    (4, "Azure OpenAI"),
                    (2, "Google"),
                    (3, "TogetherAI"),
                    (6, "Anthropic [Deprecated]"),
                    (7, "groq"),
                    (8, "Fireworks AI"),
                    (9, "Mistral AI"),
                    (10, "sarvam.ai"),
                    (11, "fal.ai"),
                    (12, "Twilio"),
                    (13, "sea-lion.ai"),
                    (14, "PublicAI"),
                    (15, "Modal"),
                    (5, "Azure Kubernetes Service"),
                ],
                help_text="The provider of the model. Only used for Display purposes.",
            ),
        ),
    ]
