# Generated by Django 5.1.3 on 2025-11-05 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("bots", "0112_alter_botintegration_slack_read_receipt_msg"),
    ]

    operations = [
        migrations.CreateModel(
            name="MemoryEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.TextField()),
                ("key", models.TextField()),
                ("value", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "saved_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memory_values",
                        to="bots.savedrun",
                    ),
                ),
            ],
            options={
                "unique_together": {("user_id", "key")},
            },
        ),
    ]
