# Generated by Django 5.1.3 on 2025-12-17 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("memory", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="memoryentry",
            options={"verbose_name_plural": "Memory Entries"},
        ),
    ]
