 # Generated by Django 5.1.3 on 2026-06-24 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_users", "0031_remove_appuser_app_users_a_email_2228c5_idx_and_more"),
        ("bots", "0125_alter_tag_options_publishedrun_is_featured_tag_color_and_more"),
        ("memory", "0002_alter_memoryentry_options"),
        ("workspaces", "0016_alter_workspacemembership_balance"),
    ]

    operations = [
        migrations.AddField(
            model_name="memoryentry",
            name="conversation",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="memory_entries",
                to="bots.conversation",
            ),
        ),
        migrations.AddField(
            model_name="memoryentry",
            name="deployment",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="memory_entries",
                to="bots.botintegration",
            ),
        ),
        migrations.AddField(
            model_name="memoryentry",
            name="member",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="memory_entries",
                to="app_users.appuser",
            ),
        ),
        migrations.AddField(
            model_name="memoryentry",
            name="platform_user",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="memoryentry",
            name="saved_workflow",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="memory_entries",
                to="bots.publishedrun",
            ),
        ),
        migrations.AddField(
            model_name="memoryentry",
            name="scope",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, "Workspace Members"),
                    (2, "My Runs & Deployments"),
                    (3, "&nbsp; User of any Deployment"),
                    (4, "Saved Workflow"),
                    (5, "User of Saved Workflow"),
                    (6, "Chat Conversation"),
                ],
                default=None,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="memoryentry",
            name="workspace",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="memory_entries",
                to="workspaces.workspace",
            ),
        ),
        migrations.AlterField(
            model_name="memoryentry",
            name="saved_run",
            field=models.ForeignKey(
                help_text="The last run that set this value",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="memory_entries",
                to="bots.savedrun",
            ),
        ),
    ]
