# Generated by Django 5.1.3 on 2026-06-30 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_users", "0031_remove_appuser_app_users_a_email_2228c5_idx_and_more"),
        ("bots", "0125_alter_tag_options_publishedrun_is_featured_tag_color_and_more"),
        ("memory", "0003_memoryentry_conversation_memoryentry_deployment_and_more"),
        ("workspaces", "0016_alter_workspacemembership_balance"),
    ]

    operations = [
        migrations.AlterField(
            model_name="memoryentry",
            name="scope",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, "Workspace Members"),
                    (2, "My Runs & Deployments"),
                    (3, "User of any Deployment"),
                    (4, "Saved Workflow"),
                    (5, "User of Saved Workflow"),
                    (6, "Chat Conversation"),
                ],
                default=None,
                null=True,
            ),
        ),
        migrations.AddIndex(
            model_name="memoryentry",
            index=models.Index(
                fields=["workspace", "-updated_at"],
                name="memory_memo_workspa_c215c8_idx",
            ),
        ),
    ]
