# Generated by Django 4.2.7 on 2024-03-12 20:48

import bots.custom_fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('files', '0002_filemetadata_files_filem_name_521f6f_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmbeddedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', bots.custom_fields.CustomURLField(help_text='The URL of the original resource (e.g. a document)', max_length=2048)),
                ('max_context_words', models.PositiveSmallIntegerField()),
                ('scroll_jump', models.PositiveSmallIntegerField()),
                ('google_translate_target', models.CharField(blank=True, max_length=5)),
                ('selected_asr_model', models.CharField(blank=True, max_length=100)),
                ('embedding_model', models.CharField(choices=[('openai_3_large', 'Text Embedding 3 Large (OpenAI)'), ('openai_3_small', 'Text Embedding 3 Small (OpenAI)'), ('openai_ada_2', 'Text Embedding Ada 2 (OpenAI)'), ('e5_large_v2', 'E5 large v2 (Liang Wang)'), ('e5_base_v2', 'E5 base v2 (Liang Wang)'), ('multilingual_e5_base', 'Multilingual E5 Base (Liang Wang)'), ('multilingual_e5_large', 'Multilingual E5 Large (Liang Wang)'), ('gte_large', 'General Text Embeddings Large (Dingkun Long)'), ('gte_base', 'General Text Embeddings Base (Dingkun Long)')], default='openai_3_large', max_length=100)),
                ('vespa_file_id', models.CharField(help_text="The ID of this file in Vespa. A hash of the file's metadata.", max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('metadata', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='embedded_files', to='files.filemetadata')),
            ],
        ),
        migrations.CreateModel(
            name='EmbeddingsReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vespa_doc_id', models.CharField(help_text='The Document ID of this embedding in Vespa. A hash of the file metadata + the split snippet.', max_length=256)),
                ('url', bots.custom_fields.CustomURLField(max_length=2048)),
                ('title', models.TextField()),
                ('snippet', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('embedded_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='embeddings_references', to='embeddings.embeddedfile')),
            ],
            options={
                'indexes': [models.Index(fields=['-updated_at'], name='embeddings__updated_afc800_idx'), models.Index(fields=['-created_at'], name='embeddings__created_d111fa_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='embeddedfile',
            index=models.Index(fields=['url', 'metadata', 'max_context_words', 'scroll_jump', 'google_translate_target', 'selected_asr_model', 'embedding_model', '-updated_at'], name='embeddings__url_750ab2_idx'),
        ),
        migrations.AddIndex(
            model_name='embeddedfile',
            index=models.Index(fields=['-updated_at'], name='embeddings__updated_83a91e_idx'),
        ),
    ]
