# Generated by Django 4.2.7 on 2024-07-25 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0019_alter_appusertransaction_reason'),
        ('embeddings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='embeddedfile',
            name='created_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='embedded_files', to='app_users.appuser'),
        ),
        migrations.AddField(
            model_name='embeddedfile',
            name='last_query_at',
            field=models.DateTimeField(blank=True, db_index=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='embeddedfile',
            name='query_count',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
    ]
