# Generated by Django 5.1.3 on 2026-03-01 20:41

from django.db import migrations, models


def set_document_model_for_existing_entries(apps, schema_editor):
    EmbeddedFile = apps.get_model("embeddings", "EmbeddedFile")
    EmbeddedFile.objects.exclude(selected_asr_model="").update(
        document_model="azure-prebuilt-layout"
    )


class Migration(migrations.Migration):
    dependencies = [
        ("app_users", "0028_remove_appuser_appuser_search_vector_idx"),
        ("embeddings", "0003_alter_embeddingsreference_vespa_doc_id"),
        ("files", "0002_filemetadata_files_filem_name_521f6f_idx"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="embeddedfile",
            name="embeddings__url_750ab2_idx",
        ),
        migrations.AddField(
            model_name="embeddedfile",
            name="document_model",
            field=models.CharField(blank=True, max_length=100, default=""),
        ),
        migrations.RunPython(
            set_document_model_for_existing_entries, migrations.RunPython.noop
        ),
        migrations.AlterField(
            model_name="embeddedfile",
            name="embedding_model",
            field=models.CharField(
                choices=[
                    ("openai_3_large", "Text Embedding 3 Large (OpenAI)"),
                    ("openai_3_small", "Text Embedding 3 Small (OpenAI)"),
                    ("openai_ada_2", "Text Embedding Ada 2 (OpenAI)"),
                    ("mistral_embed", "Mistral Embed (Mistral AI)"),
                    ("e5_large_v2", "E5 large v2 (Liang Wang)"),
                    ("e5_base_v2", "E5 base v2 (Liang Wang)"),
                    ("multilingual_e5_base", "Multilingual E5 Base (Liang Wang)"),
                    ("multilingual_e5_large", "Multilingual E5 Large (Liang Wang)"),
                    ("gte_large", "General Text Embeddings Large (Dingkun Long)"),
                    ("gte_base", "General Text Embeddings Base (Dingkun Long)"),
                ],
                default="openai_3_large",
                max_length=100,
            ),
        ),
        migrations.AddIndex(
            model_name="embeddedfile",
            index=models.Index(
                fields=[
                    "url",
                    "metadata",
                    "max_context_words",
                    "scroll_jump",
                    "google_translate_target",
                    "selected_asr_model",
                    "embedding_model",
                    "document_model",
                    "-updated_at",
                ],
                name="embeddings__url_f23c73_idx",
            ),
        ),
    ]
