# Generated by Django 4.2.5 on 2024-01-04 04:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("costs", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProviderPricing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.TextField(choices=[("LLM", "Llm")])),
                (
                    "provider",
                    models.IntegerField(
                        choices=[
                            (1, "OpenAI"),
                            (2, "GPT-4"),
                            (3, "dalle-e"),
                            (4, "whisper"),
                            (5, "GPT-3.5"),
                        ]
                    ),
                ),
                (
                    "product",
                    models.TextField(
                        choices=[
                            ("GPT-4 Vision (openai)", "gpt_4_vision"),
                            ("GPT-4 Turbo (openai)", "gpt_4_turbo"),
                            ("GPT-4 (openai)", "gpt_4"),
                            ("GPT-4 32K (openai)", "gpt_4_32k"),
                            ("ChatGPT (openai)", "gpt_3_5_turbo"),
                            ("ChatGPT 16k (openai)", "gpt_3_5_turbo_16k"),
                            ("Llama 2 (Meta AI)", "llama2_70b_chat"),
                            ("PaLM 2 Text (Google)", "palm2_chat"),
                            ("PaLM 2 Chat (Google)", "palm2_text"),
                            ("GPT-3.5 Davinci-3 (openai)", "text_davinci_003"),
                            ("GPT-3.5 Davinci-2 (openai)", "text_davinci_002"),
                            ("Curie (openai)", "text_curie_001"),
                            ("Babbage (openai)", "text_babbage_001"),
                            ("Ada (openai)", "text_ada_001"),
                            ("Codex [Deprecated] (openai)", "code_davinci_002"),
                        ]
                    ),
                ),
                (
                    "param",
                    models.TextField(
                        choices=[
                            ("input", "Input"),
                            ("output", "Output"),
                            ("input image", "Input Image"),
                            ("output image", "Output Image"),
                        ]
                    ),
                ),
                ("cost", models.DecimalField(decimal_places=8, max_digits=13)),
                ("unit", models.TextField(default="")),
                ("notes", models.TextField(default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                ("updated_by", models.TextField(default="")),
                ("pricing_url", models.TextField(default="")),
            ],
        ),
    ]
