# Generated by Django 4.2.5 on 2024-01-05 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("costs", "0002_providerpricing"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usagecost",
            name="model",
        ),
        migrations.RemoveField(
            model_name="usagecost",
            name="param",
        ),
        migrations.RemoveField(
            model_name="usagecost",
            name="provider",
        ),
        migrations.AddField(
            model_name="usagecost",
            name="provider_pricing",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="usage_costs",
                to="costs.providerpricing",
            ),
        ),
        migrations.AddField(
            model_name="usagecost",
            name="quantity",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="providerpricing",
            name="product",
            field=models.TextField(
                choices=[
                    ("GPT-4 Vision (openai)", "gpt_4_vision"),
                    ("GPT-4 Turbo (openai)", "gpt_4_turbo"),
                    ("GPT-4 (openai)", "gpt_4"),
                    ("GPT-4 32K (openai)", "gpt_4_32k"),
                    ("ChatGPT (openai)", "gpt_3_5_turbo"),
                    ("ChatGPT 16k (openai)", "gpt_3_5_turbo_16k"),
                    ("Llama 2 (Meta AI)", "llama2_70b_chat"),
                    ("PaLM 2 Chat (Google)", "palm2_chat"),
                    ("PaLM 2 Text (Google)", "palm2_text"),
                    ("GPT-3.5 Davinci-3 (openai)", "text_davinci_003"),
                    ("GPT-3.5 Davinci-2 (openai)", "text_davinci_002"),
                    ("Curie (openai)", "text_curie_001"),
                    ("Babbage (openai)", "text_babbage_001"),
                    ("Ada (openai)", "text_ada_001"),
                    ("Codex [Deprecated] (openai)", "code_davinci_002"),
                ]
            ),
        ),
    ]
