# Generated by Django 4.2.5 on 2024-01-05 07:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("costs", "0003_remove_usagecost_model_remove_usagecost_param_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usagecost",
            name="saved_run",
        ),
    ]
