# Generated by Django 4.2.5 on 2024-01-05 08:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("costs", "0004_remove_usagecost_saved_run"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usagecost",
            name="provider_pricing",
        ),
    ]
