# Generated by Django 4.2.5 on 2024-01-05 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("bots", "0054_alter_savedrun_example_id_alter_savedrun_page_notes_and_more"),
        ("costs", "0005_remove_usagecost_provider_pricing"),
    ]

    operations = [
        migrations.AddField(
            model_name="usagecost",
            name="provider_pricing",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="usage_costs",
                to="costs.providerpricing",
            ),
        ),
        migrations.AddField(
            model_name="usagecost",
            name="saved_run",
            field=models.ForeignKey(
                blank=True,
                default=None,
                help_text="The run that was last saved by the user.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="usage_costs",
                to="bots.savedrun",
            ),
        ),
    ]
