# Generated by Django 4.2.5 on 2024-01-06 00:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("costs", "0006_usagecost_provider_pricing_usagecost_saved_run"),
    ]

    operations = [
        migrations.AlterField(
            model_name="providerpricing",
            name="provider",
            field=models.TextField(
                choices=[
                    ("OpenAI", "Openai"),
                    ("GPT-4", "Gpt 4"),
                    ("dalle-e", "Dalle E"),
                    ("whisper", "Whisper"),
                    ("GPT-3.5", "Gpt 3 5"),
                ]
            ),
        ),
    ]
