# Generated by Django 4.2.5 on 2024-01-06 01:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("costs", "0007_alter_providerpricing_provider"),
    ]

    operations = [
        migrations.AlterField(
            model_name="providerpricing",
            name="param",
            field=models.TextField(choices=[("Input", "input"), ("Output", "output")]),
        ),
        migrations.AlterField(
            model_name="providerpricing",
            name="provider",
            field=models.TextField(
                choices=[
                    ("vertex_ai", "Vertex AI"),
                    ("openai", "OpenAI"),
                    ("together", "Together"),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="providerpricing",
            name="type",
            field=models.TextField(choices=[("LLM", "LLM")]),
        ),
    ]
