# Generated by Django 4.2.5 on 2024-01-06 01:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("costs", "0008_alter_providerpricing_param_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="providerpricing",
            name="product",
            field=models.TextField(
                choices=[("gpt-4-vision-preview", "gpt-4-vision-preview")]
            ),
        ),
    ]
