# Generated by Django 4.2.5 on 2024-01-06 02:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("costs", "0009_alter_providerpricing_product"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usagecost",
            name="calculation_notes",
        ),
    ]
