# Generated by Django 4.2.7 on 2024-01-17 07:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("costs", "0015_alter_providerpricing_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="providerpricing",
            name="provider",
            field=models.TextField(
                choices=[
                    ("Vertex AI", "Vertex Ai"),
                    ("OpenAI", "Openai"),
                    ("Together", "Together"),
                ]
            ),
        ),
    ]
