# Generated by Django 4.2.7 on 2024-01-17 07:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("costs", "0016_alter_providerpricing_provider"),
    ]

    operations = [
        migrations.AlterField(
            model_name="providerpricing",
            name="type",
            field=models.TextField(choices=[("LLM", "LLM"), ("GPU", "GPU")]),
        ),
    ]
