# Generated by Django 4.2.7 on 2024-01-17 07:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("costs", "0017_alter_providerpricing_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="providerpricing",
            name="product",
            field=models.TextField(
                choices=[
                    ("gpt-4-vision-preview", "gpt-4-vision-preview"),
                    (
                        "('openai-gpt-4-turbo-prod-ca-1', 'gpt-4-1106-preview')",
                        "('openai-gpt-4-turbo-prod-ca-1', 'gpt-4-1106-preview')",
                    ),
                    (
                        "('openai-gpt-4-prod-ca-1', 'gpt-4')",
                        "('openai-gpt-4-prod-ca-1', 'gpt-4')",
                    ),
                    ("gpt-3.5-turbo", "gpt-3.5-turbo"),
                    ("gpt-3.5-turbo-16k", "gpt-3.5-turbo-16k"),
                    ("text-davinci-003", "text-davinci-003"),
                    ("text-davinci-002", "text-davinci-002"),
                    ("code-davinci-002", "code-davinci-002"),
                    ("text-curie-001", "text-curie-001"),
                    ("text-babbage-001", "text-babbage-001"),
                    ("text-ada-001", "text-ada-001"),
                    ("text-bison", "text-bison"),
                    ("chat-bison", "chat-bison"),
                    (
                        "togethercomputer/llama-2-70b-chat",
                        "togethercomputer/llama-2-70b-chat",
                    ),
                    ("NC24ads A100 v4-1 year plan", "NC24ads A100 v4-1 year plan"),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="providerpricing",
            name="provider",
            field=models.TextField(
                choices=[
                    ("Vertex AI", "Vertex Ai"),
                    ("OpenAI", "Openai"),
                    ("Together", "Together"),
                    ("Azure", "Azure"),
                ]
            ),
        ),
    ]
