# Generated by Django 4.2.7 on 2024-01-17 16:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("costs", "0018_alter_providerpricing_product_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="providerpricing",
            name="param",
        ),
        migrations.AlterField(
            model_name="providerpricing",
            name="unit",
            field=models.TextField(
                choices=[
                    ("Input Tokens", "input tokens"),
                    ("Output Tokens", "output tokens"),
                    ("Frames", "frames"),
                ]
            ),
        ),
    ]
