# Generated by Django 5.1.3 on 2025-10-02 19:58

import bots.models.bot_integration
import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("bots", "0109_alter_botintegration_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="SharedPhoneNumber",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "platform",
                    models.IntegerField(
                        choices=[
                            (1, "Facebook Messenger"),
                            (2, "Instagram"),
                            (3, "WhatsApp"),
                            (4, "Slack"),
                            (5, "Web"),
                            (6, "Twilio"),
                        ],
                        help_text="The platform this phone number is for (WhatsApp, Twilio, etc.)",
                    ),
                ),
                (
                    "wa_phone_number",
                    bots.models.bot_integration.WhatsappPhoneNumberField(
                        blank=True,
                        default="",
                        help_text="Bot's WhatsApp phone number (only for display)",
                        max_length=128,
                        region=None,
                        validators=[bots.models.bot_integration.validate_phonenumber],
                    ),
                ),
                (
                    "wa_phone_number_id",
                    models.CharField(
                        blank=True,
                        default=None,
                        help_text="Bot's WhatsApp phone number id (mandatory)",
                        max_length=256,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "twilio_phone_number",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True,
                        default=None,
                        help_text="Twilio phone number as found on twilio.com/console/phone-numbers/incoming (mandatory)",
                        max_length=128,
                        null=True,
                        region=None,
                        unique=True,
                    ),
                ),
                (
                    "twilio_phone_number_sid",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Twilio phone number sid as found on twilio.com/console/phone-numbers/incoming (only for display)",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this phone number is available for assignment",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Optional notes about this phone number",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-updated_at"],
                "get_latest_by": "updated_at",
                "indexes": [
                    models.Index(
                        fields=["-updated_at"], name="number_cycl_updated_4168f5_idx"
                    ),
                    models.Index(
                        fields=["platform", "is_active"],
                        name="number_cycl_platfor_672fc0_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="SharedPhoneNumberBotUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "wa_phone_number",
                    bots.models.bot_integration.WhatsappPhoneNumberField(
                        blank=True,
                        help_text="The user's WhatsApp phone number",
                        max_length=128,
                        null=True,
                        region=None,
                        validators=[bots.models.bot_integration.validate_phonenumber],
                    ),
                ),
                (
                    "twilio_phone_number",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True,
                        help_text="The user's Twilio phone number",
                        max_length=128,
                        null=True,
                        region=None,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "bot_integration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shared_phone_number_users",
                        to="bots.botintegration",
                    ),
                ),
                (
                    "shared_phone_number",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="users",
                        to="number_cycling.sharedphonenumber",
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
                "get_latest_by": "updated_at",
                "indexes": [
                    models.Index(
                        fields=["-updated_at"], name="number_cycl_updated_ad76f3_idx"
                    )
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("wa_phone_number__isnull", False),
                            ("twilio_phone_number__isnull", False),
                            _connector="XOR",
                        ),
                        name="exactly_one_of_wa_or_twilio_phone_number",
                    )
                ],
                "unique_together": {
                    ("twilio_phone_number", "shared_phone_number"),
                    ("wa_phone_number", "shared_phone_number"),
                },
            },
        ),
    ]
