# Generated by Django 5.1.3 on 2025-08-09 10:15

import bots.models.bot_integration
import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("bots", "0105_remove_conversation_state_remove_feedback_category_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BotExtension",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "extension_number",
                    models.CharField(
                        db_index=True,
                        help_text="The extension number for dialing ",
                        max_length=16,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "bot_integration",
                    models.ForeignKey(
                        help_text="The bot integration this extension belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="extensions",
                        to="bots.botintegration",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BotExtensionUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "wa_phone_number",
                    bots.models.bot_integration.WhatsappPhoneNumberField(
                        blank=True,
                        help_text="WhatsApp phone number associated with this extension user",
                        max_length=128,
                        null=True,
                        region=None,
                        validators=[bots.models.bot_integration.validate_phonenumber],
                    ),
                ),
                (
                    "twilio_phone_number",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True,
                        help_text="Twilio phone number associated with this extension user",
                        max_length=128,
                        null=True,
                        region=None,
                        validators=[bots.models.bot_integration.validate_phonenumber],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "extension",
                    models.ForeignKey(
                        help_text="The extension this user is associated with",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="users",
                        to="number_cycling.botextension",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProvisionedNumber",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        help_text="The phone number (e.g., +15551234567)",
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "platform",
                    models.IntegerField(
                        choices=[
                            (1, "Facebook Messenger"),
                            (2, "Instagram"),
                            (3, "WhatsApp"),
                            (4, "Slack"),
                            (5, "Web"),
                            (6, "Twilio"),
                        ],
                        help_text="The platform this phone number is for (WhatsApp, Twilio, etc.)",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this phone number is available for assignment",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Optional notes about this phone number",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["platform"], name="bots_provis_platfor_b162e3_idx"
                    ),
                    models.Index(
                        fields=["is_active"], name="bots_provis_is_acti_aedbef_idx"
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("platform", 3), ("platform", 6), _connector="OR"
                        ),
                        name="platform_whatsapp_or_platform_twilio",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="botextension",
            index=models.Index(
                fields=["extension_number"], name="bots_botext_extensi_7ea998_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="botextension",
            unique_together={("bot_integration", "extension_number")},
        ),
        migrations.AddIndex(
            model_name="botextensionuser",
            index=models.Index(
                fields=["wa_phone_number"], name="bots_botext_wa_phon_7efc3f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="botextensionuser",
            index=models.Index(
                fields=["twilio_phone_number"], name="bots_botext_twilio__e2d976_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="botextensionuser",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("wa_phone_number__isnull", False),
                    ("twilio_phone_number__isnull", False),
                    _connector="OR",
                ),
                name="wa_phone_number_or_twilio_phone_number",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="botextensionuser",
            unique_together={
                ("extension", "twilio_phone_number"),
                ("extension", "wa_phone_number"),
            },
        ),
    ]
