# Generated by Django 5.1.3 on 2026-03-09 15:47

import phonenumbers
from django.db import migrations, models

PLATFORM_WHATSAPP = 3
PLATFORM_TWILIO = 6


class Migration(migrations.Migration):

    def backfill_country_code(apps, schema_editor):
        SharedPhoneNumber = apps.get_model("number_cycling", "SharedPhoneNumber")
        qs = SharedPhoneNumber.objects.filter(country_code="")

        for obj in qs.iterator(chunk_size=1000):

            if obj.platform == PLATFORM_WHATSAPP:
                raw = obj.wa_phone_number
            elif obj.platform == PLATFORM_TWILIO:
                raw = obj.twilio_phone_number
            else:
                continue

            if not raw:
                continue
            
            try:
                parsed = phonenumbers.parse(str(raw), None)
                cc = phonenumbers.region_code_for_number(parsed)
            except phonenumbers.NumberParseException:
                continue
            if not cc or len(cc) != 2:
                continue

            SharedPhoneNumber.objects.filter(pk=obj.pk).update(country_code=cc.upper())

    dependencies = [
        ("number_cycling", "0001_initial"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="sharedphonenumber",
            name="number_cycl_platfor_672fc0_idx",
        ),
        migrations.AddField(
            model_name="sharedphonenumber",
            name="country_code",
            field=models.CharField(
                default="",
                editable=False,
                help_text="ISO 3166-1 alpha-2 country code (e.g. 'US', 'IN'), auto-derived from phone number.",
                max_length=2,
            ),
        ),
        migrations.RunPython(backfill_country_code, migrations.RunPython.noop),
        migrations.AddIndex(
            model_name="sharedphonenumber",
            index=models.Index(
                fields=["platform", "is_active", "country_code"],
                name="number_cycl_platfor_2f5bae_idx",
            ),
        ),
    ]
