# Generated by Django 5.1.3 on 2026-03-13 07:16
from django.db import migrations, models


class Migration(migrations.Migration):
    def backfill_country_code(apps, schema_editor):
        import phonenumbers

        SharedPhoneNumber = apps.get_model("number_cycling", "SharedPhoneNumber")
        qs = SharedPhoneNumber.objects.filter(country_code="")

        for shared_phone_number in qs.iterator(chunk_size=1000):
            phone_number = (
                shared_phone_number.wa_phone_number
                or shared_phone_number.twilio_phone_number
            )
            if not phone_number:
                continue
            try:
                phone_obj = phonenumbers.parse(str(phone_number))
                country_code = phonenumbers.region_code_for_number(phone_obj)
            except phonenumbers.NumberParseException:
                continue
            if not country_code or len(country_code) != 2:
                continue
            SharedPhoneNumber.objects.filter(pk=shared_phone_number.pk).update(
                country_code=country_code.upper()
            )

    dependencies = [
        ("number_cycling", "0001_initial"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="sharedphonenumber",
            name="number_cycl_platfor_672fc0_idx",
        ),
        migrations.AddField(
            model_name="sharedphonenumber",
            name="country_code",
            field=models.CharField(
                default="",
                help_text="ISO 3166-1 alpha-2 country code (e.g. 'US', 'IN'), auto-derived from phone number.",
                max_length=2,
            ),
        ),
        migrations.RunPython(backfill_country_code, migrations.RunPython.noop),
        migrations.AddIndex(
            model_name="sharedphonenumber",
            index=models.Index(
                fields=["platform", "is_active", "country_code"],
                name="number_cycl_platfor_2f5bae_idx",
            ),
        ),
    ]
