# Generated by Django 5.1.3 on 2025-08-09 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("number_cycling", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="botextension",
            name="extension_number",
            field=models.IntegerField(
                db_index=True,
                help_text="The extension number for dialing ",
                unique=True,
            ),
        ),
    ]
