# Generated by Django 5.1.3 on 2026-02-17 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("number_cycling", "0001_initial"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="sharedphonenumber",
            name="number_cycl_platfor_672fc0_idx",
        ),
        migrations.AddField(
            model_name="sharedphonenumber",
            name="country_code",
            field=models.CharField(
                blank=True,
                default="",
                help_text="ISO 3166-1 alpha-2 country code (e.g. 'US', 'IN')",
                max_length=2,
            ),
        ),
        migrations.AddIndex(
            model_name="sharedphonenumber",
            index=models.Index(
                fields=["platform", "is_active", "country_code"],
                name="number_cycl_platfor_2f5bae_idx",
            ),
        ),
    ]
