# Generated by Django 5.1.3 on 2025-08-14 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("number_cycling", "0002_alter_botextension_extension_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="provisionednumber",
            name="wa_phone_number_id",
            field=models.CharField(
                blank=True,
                default=None,
                help_text="Bot's WhatsApp phone number id (mandatory)",
                max_length=256,
                null=True,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="botextensionuser",
            name="extension",
            field=models.ForeignKey(
                help_text="The extension this user is associated with",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bot_extension_users",
                to="number_cycling.botextension",
            ),
        ),
        migrations.AddConstraint(
            model_name="provisionednumber",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("platform", 3), _negated=True),
                    models.Q(
                        ("phone_number__isnull", False),
                        ("wa_phone_number_id__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="whatsapp_requires_both_fields",
            ),
        ),
    ]
