# Generated by Django 5.1.3 on 2026-03-17 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "number_cycling",
            "0002_remove_sharedphonenumber_number_cycl_platfor_672fc0_idx_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="sharedphonenumber",
            name="country_code",
            field=models.CharField(
                blank=True,
                default="",
                help_text="ISO 3166-1 alpha-2 country code (e.g. 'US', 'IN'), auto-derived from phone number.",
                max_length=2,
            ),
        ),
    ]
