 # Generated by Django 5.1.3 on 2026-03-25 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("number_cycling", "0003_alter_sharedphonenumber_country_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sharedphonenumber",
            name="platform",
            field=models.IntegerField(
                choices=[
                    (1, "Facebook Messenger"),
                    (2, "Instagram"),
                    (3, "WhatsApp"),
                    (4, "Slack"),
                    (5, "Web"),
                    (6, "Twilio"),
                    (7, "Telegram"),
                ],
                help_text="The platform this phone number is for (WhatsApp, Twilio, etc.)",
            ),
        ),
    ]
