# Generated by Django 5.1.3 on 2025-08-26 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("number_cycling", "0003_provisionednumber_wa_phone_number_id_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="provisionednumber",
            name="whatsapp_requires_both_fields",
        ),
        migrations.AlterField(
            model_name="botextension",
            name="extension_number",
            field=models.IntegerField(
                help_text="The extension number for dialing ", unique=True
            ),
        ),
        migrations.AddConstraint(
            model_name="provisionednumber",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("platform", 3), _negated=True),
                    models.Q(
                        ("phone_number__isnull", False),
                        ("wa_phone_number_id__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="wa_phone_number_and_wa_phone_number_id",
            ),
        ),
    ]
