# Generated by Django 4.2.7 on 2024-03-21 12:52

import bots.custom_fields
import django.core.validators
from django.db import migrations, models
import django.db.models.functions.text
import handles.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Handle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True, validators=[django.core.validators.RegexValidator(regex='^[a-z][a-z0-9_.-]*$'), handles.models.validate_handles_blacklist])),
                ('redirect_url', bots.custom_fields.CustomURLField(blank=True, default=None, max_length=2048, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddConstraint(
            model_name='handle',
            constraint=models.CheckConstraint(check=models.Q(('name', django.db.models.functions.text.Lower('name'))), name='handle_name_is_lowercase', violation_error_message='Handle must be lowercase'),
        ),
    ]
