# Generated by Django 4.2.7 on 2024-04-02 12:57

import django.core.validators
from django.db import migrations, models
import handles.models


class Migration(migrations.Migration):

    dependencies = [
        ('handles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='handle',
            name='name',
            field=models.TextField(unique=True, validators=[django.core.validators.MaxLengthValidator(limit_value=40, message='Handles must be at most 40 characters long'), django.core.validators.RegexValidator(message='Handles must contain only lowercase letters, numbers, and the characters . _ -', regex='^[a-z0-9_\\.-]+$'), handles.models.validate_handles_blacklist]),
        ),
    ]
