# Generated by Django 5.1.3 on 2025-06-09 08:39

import django.core.validators
import handles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("handles", "0002_remove_handle_handle_upper_name_is_unique_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="handle",
            name="name",
            field=models.TextField(
                db_index=True,
                validators=[
                    django.core.validators.MaxLengthValidator(
                        limit_value=40,
                        message="Handles must be at most 40 characters long",
                    ),
                    django.core.validators.RegexValidator(
                        message="Handles must contain only letters, numbers, and the characters . _ -",
                        regex="^[A-Za-z0-9_\\.-]+$",
                    ),
                    handles.models.validate_handles_blacklist,
                ],
            ),
        ),
    ]
