# Generated by Django 4.2.5 on 2023-11-07 14:48

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FileMetadata",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(blank=True, default="")),
                ("etag", models.CharField(max_length=255, null=True)),
                ("mime_type", models.CharField(blank=True, default="", max_length=255)),
                ("total_bytes", models.PositiveIntegerField(blank=True, default=0)),
            ],
        ),
    ]
