# Generated by Django 4.2.7 on 2024-03-11 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='filemetadata',
            index=models.Index(fields=['name', 'etag', 'mime_type', 'total_bytes'], name='files_filem_name_521f6f_idx'),
        ),
    ]
