# Generated by Django 5.1.3 on 2026-03-30 13:30

import bots.custom_fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_users", "0028_remove_appuser_appuser_search_vector_idx"),
        ("bots", "0114_savedrun_error_params"),
        ("files", "0002_filemetadata_files_filem_name_521f6f_idx"),
        ("workspaces", "0013_workspace_enable_bot_builder_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="UploadedFile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("f_url", bots.custom_fields.CustomURLField(max_length=2048, unique=True, verbose_name="File URL")),
                ("bucket_name", models.CharField(max_length=255)),
                ("object_name", models.TextField()),
                ("is_user_uploaded", models.BooleanField(default=False)),
                ("is_uploading", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("metadata", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="uploaded_files", to="files.filemetadata")),
                ("saved_run", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="uploaded_files", to="bots.savedrun")),
                ("user", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="uploaded_files", to="app_users.appuser")),
                ("workspace", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="uploaded_files", to="workspaces.workspace")),
            ],
            options={
                "indexes": [
                    models.Index(fields=["workspace", "created_at"], name="files_uploa_workspa_3d4b4a_idx"),
                    models.Index(fields=["user", "created_at"], name="files_uploa_user_id_7bdbf8_idx"),
                    models.Index(fields=["created_at"], name="files_uploa_created_5e3e16_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(fields=["bucket_name", "object_name"], name="uploadedfile_bucket_object_unique"),
                ],
            },
        ),
    ]
