# Generated by Django 5.1.3 on 2026-03-30 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("files", "0004_add_saved_run_to_uploadedfile"),
    ]

    operations = [
        migrations.AddField(
            model_name="uploadedfile",
            name="is_uploading",
            field=models.BooleanField(default=False),
        ),
    ]
