# Generated by Django 4.2 on 2023-05-30 12:06

import bots.custom_fields
from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AppUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uid", models.CharField(max_length=255, unique=True)),
                ("name", models.TextField(blank=True, default="")),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                (
                    "phone_number",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True, max_length=128, null=True, region=None
                    ),
                ),
                ("balance", models.IntegerField()),
                ("is_anonymous", models.BooleanField()),
                ("is_disabled", models.BooleanField(default=False)),
                (
                    "photo_url",
                    bots.custom_fields.CustomURLField(
                        blank=True, default="", max_length=2048
                    ),
                ),
            ],
        ),
    ]
