# Generated by Django 4.2 on 2023-05-30 12:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app_users", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="appuser",
            old_name="name",
            new_name="display_name",
        ),
    ]
