# Generated by Django 4.2 on 2023-05-30 16:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("app_users", "0002_rename_name_appuser_display_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="appuser",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="appuser",
            name="upgraded_from_anonymous_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
