# Generated by Django 4.2.1 on 2023-07-03 19:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("app_users", "0004_appuser_stripe_customer_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appuser",
            name="created_at",
            field=models.DateTimeField(
                blank=True, default=django.utils.timezone.now, editable=False
            ),
        ),
    ]
