# Generated by Django 4.2.3 on 2023-08-16 17:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_users", "0005_alter_appuser_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="appuser",
            name="disable_safety_checker",
            field=models.BooleanField(default=False),
        ),
    ]
