# Generated by Django 4.2.5 on 2023-10-13 10:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("app_users", "0007_appuser_is_paying"),
    ]

    operations = [
        migrations.CreateModel(
            name="AppUserTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("invoice_id", models.CharField(max_length=255)),
                ("amount", models.IntegerField()),
                ("end_balance", models.IntegerField()),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="app_users.appuser",
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "invoice_id")},
            },
        ),
    ]
