# Generated by Django 4.2.5 on 2023-10-18 14:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_users", "0008_appusertransaction"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="appusertransaction",
            options={"verbose_name": "Transaction"},
        ),
        migrations.AlterUniqueTogether(
            name="appusertransaction",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="appusertransaction",
            name="invoice_id",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
