# Generated by Django 4.2.5 on 2023-11-12 15:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("app_users", "0009_alter_appusertransaction_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appuser",
            name="balance",
            field=models.IntegerField(verbose_name="bal"),
        ),
        migrations.AlterField(
            model_name="appuser",
            name="created_at",
            field=models.DateTimeField(
                blank=True,
                default=django.utils.timezone.now,
                editable=False,
                verbose_name="created",
            ),
        ),
        migrations.AlterField(
            model_name="appuser",
            name="display_name",
            field=models.TextField(blank=True, verbose_name="name"),
        ),
        migrations.AlterField(
            model_name="appuser",
            name="is_paying",
            field=models.BooleanField(default=False, verbose_name="paid"),
        ),
    ]
