# Generated by Django 4.2.7 on 2024-01-08 13:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_users", "0010_alter_appuser_balance_alter_appuser_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="appusertransaction",
            name="charged_amount",
            field=models.PositiveIntegerField(
                default=0,
                help_text="The charged dollar amount in the currency’s smallest unit.<br>E.g. for 10 USD, this would be of 1000 (that is, 1000 cents).<br><a href='https://stripe.com/docs/currencies'>Learn More</a>",
            ),
        ),
        migrations.AddField(
            model_name="appusertransaction",
            name="payment_provider",
            field=models.IntegerField(
                blank=True,
                choices=[(1, "Stripe"), (2, "Paypal")],
                default=None,
                help_text="The payment provider used for this transaction.<br>If this is provided, the Charged Amount should also be provided.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="appusertransaction",
            name="amount",
            field=models.IntegerField(
                help_text="The amount (Gooey credits) added/deducted in this transaction.<br>Positive for credits added, negative for credits deducted."
            ),
        ),
        migrations.AlterField(
            model_name="appusertransaction",
            name="end_balance",
            field=models.IntegerField(
                help_text="The end balance (Gooey credits) of the user after this transaction"
            ),
        ),
        migrations.AlterField(
            model_name="appusertransaction",
            name="invoice_id",
            field=models.CharField(
                help_text="The Payment Provider's Invoice ID for this transaction.<br>For Gooey, this will be of the form 'gooey_in_{uuid}'",
                max_length=255,
                unique=True,
            ),
        ),
    ]
