# Generated by Django 4.2.5 on 2023-12-27 17:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_users", "0011_appusertransaction_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appusertransaction",
            name="type",
            field=models.CharField(max_length=255),
        ),
    ]
