# Generated by Django 4.2.7 on 2024-02-14 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0011_appusertransaction_charged_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='low_balance_email_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
