# Generated by Django 4.2.7 on 2024-02-28 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0012_appuser_low_balance_email_sent_at'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='appusertransaction',
            index=models.Index(fields=['user', 'amount', '-created_at'], name='app_users_a_user_id_9b2e8d_idx'),
        ),
        migrations.AddIndex(
            model_name='appusertransaction',
            index=models.Index(fields=['-created_at'], name='app_users_a_created_3c27fe_idx'),
        ),
    ]
