# Generated by Django 4.2.5 on 2023-12-27 20:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_users", "0013_alter_appusertransaction_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="appusertransaction",
            name="dollar_amt",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
    ]
