# Generated by Django 4.2.7 on 2024-04-08 13:19

import bots.custom_fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('handles', '0001_initial'),
        ('app_users', '0013_appusertransaction_app_users_a_user_id_9b2e8d_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='banner_url',
            field=bots.custom_fields.CustomURLField(blank=True, default='', max_length=2048),
        ),
        migrations.AddField(
            model_name='appuser',
            name='bio',
            field=bots.custom_fields.StrippedTextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='appuser',
            name='company',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='appuser',
            name='github_username',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='appuser',
            name='handle',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user', to='handles.handle'),
        ),
        migrations.AddField(
            model_name='appuser',
            name='website_url',
            field=bots.custom_fields.CustomURLField(blank=True, default='', max_length=2048),
        ),
    ]
