# Generated by Django 4.2.5 on 2024-01-05 05:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_users", "0014_appusertransaction_dollar_amt"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appusertransaction",
            name="type",
            field=models.TextField(
                choices=[
                    ("Stripe", "Stripe"),
                    ("Paypal", "Paypal"),
                    ("SavedRun", "Saved Run"),
                ],
                default="Stripe",
            ),
        ),
    ]
