# Generated by Django 4.2.7 on 2024-05-13 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0014_appuser_banner_url_appuser_bio_appuser_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='monthly_spending_budget',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appuser',
            name='monthly_spending_notification_threshold',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='appusertransaction',
            index=models.Index(fields=['user', 'created_at', 'amount'], name='app_users_a_user_id_b0d6a5_idx'),
        ),
    ]
