# Generated by Django 4.2.7 on 2024-04-18 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0014_appuser_banner_url_appuser_bio_appuser_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='auto_recharge_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
