# Generated by Django 4.2.7 on 2024-05-27 05:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
        ('app_users', '0014_appuser_banner_url_appuser_bio_appuser_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='subscription',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user', to='payments.subscription'),
        ),
        migrations.AlterField(
            model_name='appusertransaction',
            name='payment_provider',
            field=models.IntegerField(blank=True, choices=[(1, 'Stripe'), (2, 'PayPal')], default=None, help_text='The payment provider used for this transaction.<br>If this is provided, the Charged Amount should also be provided.', null=True),
        ),
        migrations.AddIndex(
            model_name='appusertransaction',
            index=models.Index(fields=['user', 'created_at', 'amount'], name='app_users_a_user_id_b0d6a5_idx'),
        ),
    ]
