# Generated by Django 4.2.5 on 2024-01-05 05:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_users", "0015_alter_appusertransaction_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appusertransaction",
            name="type",
            field=models.TextField(
                choices=[("1", "Stripe"), ("2", "Paypal"), ("3", "SavedRun")],
                default="1",
            ),
        ),
    ]
