# Generated by Django 4.2.7 on 2024-04-22 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0015_appuser_auto_recharge_email_threshold_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='auto_recharge_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
