# Generated by Django 4.2.7 on 2024-05-25 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
        ('app_users', '0015_appuser_monthly_spending_budget_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appuser',
            name='monthly_spending_budget',
        ),
        migrations.RemoveField(
            model_name='appuser',
            name='monthly_spending_notification_threshold',
        ),
        migrations.AddField(
            model_name='appuser',
            name='subscription',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user', to='payments.subscription'),
        ),
        migrations.AlterField(
            model_name='appusertransaction',
            name='payment_provider',
            field=models.IntegerField(blank=True, choices=[(1, 'Stripe'), (2, 'PayPal')], default=None, help_text='The payment provider used for this transaction.<br>If this is provided, the Charged Amount should also be provided.', null=True),
        ),
    ]
