# Generated by Django 4.2.7 on 2024-04-03 12:19

import bots.custom_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0015_appuser_bio_appuser_company_appuser_github_username_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='banner_url',
            field=bots.custom_fields.CustomURLField(blank=True, default='', max_length=2048),
        ),
    ]
