# Generated by Django 4.2.7 on 2024-05-14 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_subscription'),
        ('app_users', '0016_appuser_auto_recharge'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='subscription',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.subscription'),
        ),
    ]
