# Generated by Django 4.2.7 on 2024-06-10 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_alter_subscription_auto_recharge_balance_threshold'),
        ('app_users', '0016_appuser_disable_rate_limits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='subscription',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user', to='payments.subscription'),
        ),
    ]
