# Generated by Django 4.2.7 on 2024-06-18 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_alter_subscription_external_id_and_more'),
        ('app_users', '0016_appuser_disable_rate_limits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='subscription',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user', to='payments.subscription'),
        ),
    ]
