# Generated by Django 4.2.5 on 2024-01-06 22:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_users", "0016_alter_appusertransaction_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="appusertransaction",
            name="dollar_amt",
        ),
        migrations.RemoveField(
            model_name="appusertransaction",
            name="type",
        ),
        migrations.AddField(
            model_name="appusertransaction",
            name="charged_amount",
            field=models.PositiveIntegerField(
                default=0,
                help_text="The charged dollar amount in the currency’s smallest unit.<br>E.g. for 10 USD, this would be of 1000 (that is, 1000 cents).<br><a href='https://stripe.com/docs/currencies'>Learn More</a>",
            ),
        ),
        migrations.AddField(
            model_name="appusertransaction",
            name="payment_provider",
            field=models.IntegerField(
                blank=True,
                choices=[(1, "Stripe"), (2, "Paypal")],
                default=None,
                help_text="The payment provider used for this transaction.<br>If this is provided, the Charged Amount should also be provided.",
                null=True,
            ),
        ),
    ]
