# Generated by Django 4.2.7 on 2024-05-22 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0017_appuser_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='default_payment_provider',
            field=models.IntegerField(blank=True, choices=[(1, 'Stripe'), (2, 'Paypal')], null=True),
        ),
    ]
