# Generated by Django 4.2.7 on 2024-05-22 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_autorechargesubscription_auto_recharge_balance_threshold_and_more'),
        ('app_users', '0018_appuser_default_payment_provider'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appuser',
            name='auto_recharge',
        ),
        migrations.RemoveField(
            model_name='appuser',
            name='default_payment_provider',
        ),
        migrations.AlterField(
            model_name='appuser',
            name='subscription',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user', to='payments.subscription'),
        ),
        migrations.AlterField(
            model_name='appusertransaction',
            name='payment_provider',
            field=models.IntegerField(blank=True, choices=[(1, 'Stripe'), (2, 'PayPal')], default=None, help_text='The payment provider used for this transaction.<br>If this is provided, the Charged Amount should also be provided.', null=True),
        ),
    ]
