# Generated by Django 4.2.7 on 2024-09-10 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0019_alter_appusertransaction_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
