# Generated by Django 5.1.1 on 2024-09-12 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0020_appuser_updated_at'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='appusertransaction',
            name='app_users_a_user_id_9b2e8d_idx',
        ),
        migrations.RemoveIndex(
            model_name='appusertransaction',
            name='app_users_a_user_id_b0d6a5_idx',
        ),
    ]
