# Generated by Django 5.0.9 on 2024-09-15 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0021_remove_appusertransaction_app_users_a_user_id_9b2e8d_idx_and_more'),
        ('handles', '0001_initial'),
        ('payments', '0005_alter_subscription_plan'),
        ('workspaces', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appusertransaction',
            name='workspace',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='workspaces.workspace'),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='balance',
            field=models.IntegerField(blank=True, default=None, help_text='[Deprecated]', null=True, verbose_name='bal'),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='is_paying',
            field=models.BooleanField(default=False, help_text='[Deprecated]', verbose_name='paid'),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='low_balance_email_sent_at',
            field=models.DateTimeField(blank=True, help_text='[Deprecated]', null=True),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='stripe_customer_id',
            field=models.CharField(blank=True, default='', help_text='[Deprecated]', max_length=255),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='subscription',
            field=models.OneToOneField(blank=True, help_text='[Deprecated]', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user', to='payments.subscription'),
        ),
        migrations.AlterField(
            model_name='appusertransaction',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='app_users.appuser'),
        ),
        migrations.AddIndex(
            model_name='appuser',
            index=models.Index(fields=['email'], name='app_users_a_email_2228c5_idx'),
        ),
        migrations.AddIndex(
            model_name='appusertransaction',
            index=models.Index(fields=['workspace', 'amount', '-created_at'], name='app_users_a_workspa_bd7eb5_idx'),
        ),
        migrations.AddConstraint(
            model_name='appusertransaction',
            constraint=models.CheckConstraint(check=models.Q(('user__isnull', False), ('workspace__isnull', False), _connector='OR'), name='user_or_workspace_present'),
        ),
    ]
