# Generated by Django 5.1.1 on 2024-09-16 00:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0022_appusertransaction_workspace_alter_appuser_balance_and_more'),
        ('workspaces', '0002_alter_workspace_domain_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appusertransaction',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='workspaces.workspace'),
        ),
    ]
