# Generated by Django 5.1.3 on 2025-01-24 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0023_alter_appusertransaction_workspace'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appuser',
            name='handle',
        ),
    ]
