# Generated by Django 5.1.3 on 2025-01-28 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0024_alter_appuser_handle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appuser',
            name='handle',
        ),
    ]
