# Generated by Django 5.1.3 on 2025-03-25 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0025_remove_appuser_handle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appusertransaction',
            name='plan',
            field=models.IntegerField(blank=True, choices=[(1, 'Basic Plan'), (2, 'Premium Plan'), (4, 'Creator'), (5, 'Business (2024)'), (3, 'Pay as you go'), (7, 'Business'), (6, 'Enterprise')], default=None, help_text="User's plan at the time of this transaction.", null=True),
        ),
    ]
