# Generated by Django 5.1.3 on 2025-04-21 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0027_appuser_appuser_search_vector_idx'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='appuser',
            name='appuser_search_vector_idx',
        ),
    ]
