# Generated by Django 5.1.3 on 2026-04-01 05:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_users", "0028_remove_appuser_appuser_search_vector_idx"),
        ("workspaces", "0014_workspacemembership_balance"),
    ]

    operations = [
        migrations.AddField(
            model_name="appusertransaction",
            name="member",
            field=models.ForeignKey(
                blank=True,
                default=None,
                help_text="The workspace member whose balance was updated by this transaction.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="transactions",
                to="workspaces.workspacemembership",
            ),
        ),
        migrations.AlterField(
            model_name="appusertransaction",
            name="plan",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, "Basic Plan"),
                    (2, "Premium Plan"),
                    (4, "Creator"),
                    (5, "Business (2024)"),
                    (7, "Business"),
                    (3, "Free"),
                    (8, "Pro"),
                    (9, "Team"),
                    (6, "Enterprise"),
                ],
                default=None,
                help_text="User's plan at the time of this transaction.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="appusertransaction",
            name="reason",
            field=models.IntegerField(
                choices=[
                    (1, "Deduct"),
                    (2, "Addon"),
                    (3, "Subscribe"),
                    (4, "Sub-Create"),
                    (5, "Sub-Cycle"),
                    (6, "Sub-Update"),
                    (8, "Sub-Limit-Reset"),
                    (9, "Sub-Seat-Change"),
                    (7, "Auto-Recharge"),
                ],
                help_text="The reason for this transaction.<br><br>Deduct: Credits deducted due to a run.<br>Addon: User purchased an add-on.<br>Subscribe: Applies to subscriptions where no distinction was made between create, update and cycle.<br>Sub-Create: A subscription was created.<br>Sub-Cycle: A subscription advanced into a new period.<br>Sub-Update: A subscription was updated.<br>Auto-Recharge: Credits auto-recharged due to low balance.",
            ),
        ),
        migrations.AlterField(
            model_name="appusertransaction",
            name="user",
            field=models.ForeignKey(
                blank=True,
                default=None,
                help_text="The user who initiated this transaction",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transactions",
                to="app_users.appuser",
            ),
        ),
    ]
