# Generated by Django 5.1.3 on 2025-12-30 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_users", "0029_alter_appusertransaction_plan"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appusertransaction",
            name="plan",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, "Basic Plan"),
                    (2, "Premium Plan"),
                    (4, "Creator"),
                    (5, "Business (2024)"),
                    (7, "Business"),
                    (3, "Free"),
                    (8, "Standard"),
                    (9, "Team"),
                    (6, "Enterprise"),
                ],
                default=None,
                help_text="User's plan at the time of this transaction.",
                null=True,
            ),
        ),
    ]
