# Generated by Django 5.1.3 on 2026-04-10 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_users", "0029_appusertransaction_member_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="appuser",
            name="last_login_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
