# Generated by Django 5.1.3 on 2026-06-10 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_users", "0030_appuser_last_login_at"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="appuser",
            name="app_users_a_email_2228c5_idx",
        ),
        migrations.AddField(
            model_name="appuser",
            name="password",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="appuser",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
