# Generated by Django 5.1.3 on 2026-07-02 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_users", "0031_remove_appuser_app_users_a_email_2228c5_idx_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appuser",
            name="uid",
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
