# Generated by Django 5.1.3 on 2026-05-20 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_users", "0031_appuser_localauth_password"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="appuser",
            name="app_users_a_email_2228c5_idx",
        ),
        migrations.AlterField(
            model_name="appuser",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
