#!/usr/bin/env python3

import importlib
import json
import pkgutil
import subprocess
import sys
import tempfile
from pathlib import Path
from types import ModuleType

from pydantic import BaseModel

TYPES_PACKAGE = "gooey_gui.types"

BASE_DIR = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(BASE_DIR))


def main() -> None:
    for module in discover_type_modules():
        generate_types_for_module(module)


def discover_type_modules() -> list[ModuleType]:
    package = importlib.import_module(TYPES_PACKAGE)
    return [
        importlib.import_module(f"{TYPES_PACKAGE}.{info.name}")
        for info in pkgutil.iter_modules(package.__path__)
        if not info.ispkg
    ]


def generate_types_for_module(module: ModuleType) -> None:
    models = get_pydantic_models(module)
    source_path = get_module_source_path(module)
    output_path = source_path.with_suffix(".d.ts")
    for model in models:
        schema = model.model_json_schema()
        strip_field_titles(schema)
        with tempfile.NamedTemporaryFile(mode="w", suffix=".schema.json") as f:
            schema_path = Path(f.name)
            write_schema(schema_path, schema)
            print(
                f"{module.__name__}.{model.__name__} -> {output_path.relative_to(BASE_DIR)}"
            )
            run_type_generator(
                source_path=source_path,
                schema_path=schema_path,
                types_path=output_path,
            )


def get_pydantic_models(module: ModuleType) -> list[type[BaseModel]]:
    return [
        cls
        for cls in vars(module).values()
        if issubclass(cls, BaseModel) and cls.__module__ == module.__name__
    ]


def get_module_source_path(module: ModuleType) -> Path:
    if not module.__file__:
        raise ValueError(f"{module.__name__} does not have a source file")
    return Path(module.__file__).resolve()


def strip_field_titles(schema: dict) -> None:
    for prop in schema.get("properties", {}).values():
        if isinstance(prop, dict):
            prop.pop("title", None)
    for definition in schema.get("$defs", {}).values():
        if isinstance(definition, dict):
            strip_field_titles(definition)


def write_schema(schema_path: Path, schema: dict) -> None:
    schema_path.write_text(json.dumps(schema, indent=2) + "\n", encoding="utf-8")


def run_type_generator(
    *,
    source_path: Path,
    schema_path: Path,
    types_path: Path,
) -> None:
    script_path = Path(__file__).resolve().relative_to(BASE_DIR)
    subprocess.run(
        [
            "npx",
            "json-schema-to-typescript",
            str(schema_path),
            "--output",
            str(types_path),
            "--bannerComment",
            f"/* Generated by {script_path} from {source_path.relative_to(BASE_DIR)}. Do not edit manually. */",
        ],
        cwd=BASE_DIR / "gooey-gui",
        check=True,
    )


if __name__ == "__main__":
    main()
