#!/usr/bin/env python3

import importlib
import json
import pkgutil
import re
import subprocess
import sys
import tempfile
from pathlib import Path
from types import ModuleType

import pydantic
import typing
from pydantic.json_schema import GenerateJsonSchema, JsonSchemaValue
from pydantic_core import core_schema

TYPES_PACKAGE = "gooey_gui.types"

BASE_DIR = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(BASE_DIR))


def main() -> None:
    for module in discover_type_modules():
        generate_types_for_module(module)


def discover_type_modules() -> list[ModuleType]:
    package = importlib.import_module(TYPES_PACKAGE)
    return [
        importlib.import_module(f"{TYPES_PACKAGE}.{info.name}")
        for info in pkgutil.iter_modules(package.__path__)
        if not info.ispkg
    ]


def generate_types_for_module(module: ModuleType) -> None:
    models = get_pydantic_models(module)
    if not models:
        return

    source_path = get_module_source_path(module)
    output_path = source_path.with_suffix(".d.ts")
    schema = root_schema_for_models(models)

    print(
        f"{module.__name__} ({len(models)} models) -> {output_path.relative_to(BASE_DIR)}"
    )
    run_type_generator(
        source_path=source_path,
        schema=schema,
        types_path=output_path,
    )


def get_pydantic_models(module: ModuleType) -> list[type[pydantic.BaseModel]]:
    return [
        cls
        for cls in vars(module).values()
        if issubclass(cls, pydantic.BaseModel) and cls.__module__ == module.__name__
    ]


def get_module_source_path(module: ModuleType) -> Path:
    if not module.__file__:
        raise ValueError(f"{module.__name__} does not have a source file")
    return Path(module.__file__).resolve()


def root_schema_for_models(models: list[type[pydantic.BaseModel]]) -> dict:
    union = pydantic.TypeAdapter(typing.Union[tuple(models)])
    return union.json_schema(schema_generator=CustomGenerateJsonSchema)


class CustomGenerateJsonSchema(GenerateJsonSchema):
    def field_is_required(self, field, total: bool) -> bool:
        # Pydantic omits defaulted fields from JSON Schema "required", but our
        # TypeScript types should treat every field as required (nullable, not optional).
        return True

    def field_title_should_be_set(self, schema) -> bool:
        # Field titles are noise in generated .d.ts files.
        return False

    def model_schema(self, schema: core_schema.ModelSchema) -> JsonSchemaValue:
        # Forbid extra props in generated typescript types.
        json_schema = super().model_schema(schema)
        json_schema["additionalProperties"] = False
        return json_schema


def run_type_generator(
    *,
    source_path: Path,
    schema: dict,
    types_path: Path,
) -> None:
    script_path = Path(__file__).resolve().relative_to(BASE_DIR)
    with tempfile.NamedTemporaryFile(mode="w", suffix=".schema.json") as f:
        schema_path = Path(f.name)
        write_schema(schema_path, schema)
        subprocess.run(
            [
                "npx", "json-schema-to-typescript",
                str(schema_path),
                "--output", str(types_path),
                "--bannerComment", f"/* Generated by {script_path} from {source_path.relative_to(BASE_DIR)}. Do not edit manually. */",
            ],
            cwd=BASE_DIR / "gooey-gui",
            check=True,
        )  # fmt:skip

    types_source = strip_generated_root_union(types_path.read_text(encoding="utf-8"))
    types_path.write_text(types_source, encoding="utf-8")


def write_schema(schema_path: Path, schema: dict) -> None:
    schema_path.write_text(json.dumps(schema, indent=2) + "\n", encoding="utf-8")


def strip_generated_root_union(types_source: str) -> str:
    # json-schema-to-typescript emits the synthetic root union on a single line
    # for a few models and wraps it across lines for many; match either form up
    # to the first terminating semicolon.
    return re.sub(
        r"^export type Tmp\w+ =[\s\S]*?;\n*",
        "",
        types_source,
        count=1,
        flags=re.MULTILINE,
    )


if __name__ == "__main__":
    main()
