# Generated by Django 5.1.3 on 2024-12-23 15:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_users', '0023_alter_appusertransaction_workspace'),
        ('workspaces', '0006_workspace_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagedSecret',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('usage_count', models.PositiveIntegerField(db_index=True, default=0)),
                ('last_used_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_users.appuser')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='managed_secrets', to='workspaces.workspace')),
            ],
            options={
                'unique_together': {('workspace', 'name')},
            },
        ),
    ]
