# Generated by Django 5.1.1 on 2024-09-25 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_keys', '0001_initial'),
        ('workspaces', '0002_alter_workspace_domain_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apikey',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to='workspaces.workspace'),
        ),
    ]
