# Generated by Django 4.2.1 on 2023-07-14 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("bots", "0023_alter_savedrun_workflow"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShortenedURL",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "clicks",
                    models.IntegerField(
                        default=0, help_text="The number of clicks on this url"
                    ),
                ),
                (
                    "max_clicks",
                    models.IntegerField(
                        default=0,
                        help_text="The maximum number of clicks allowed. Set to 0 for no limit.",
                    ),
                ),
                (
                    "disabled",
                    models.BooleanField(
                        default=False, help_text="Disable this shortened url"
                    ),
                ),
                (
                    "saved_runs",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The runs that are using this shortened url",
                        related_name="shortened_urls",
                        to="bots.savedrun",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        help_text="The user that generated this shortened url",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="shortened_urls",
                        to="app_users.appuser",
                    ),
                ),
            ],
            options={
                "verbose_name": "Shortened URL",
                "ordering": ("-created_at",),
                "get_latest_by": "created_at",
            },
        ),
    ]
