# Generated by Django 4.2.3 on 2023-08-10 09:54

import bots.custom_fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("url_shortener", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shortenedurl",
            name="url",
            field=bots.custom_fields.CustomURLField(max_length=2048),
        ),
    ]
