# Generated by Django 4.2.5 on 2023-10-16 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("url_shortener", "0002_alter_shortenedurl_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="shortenedurl",
            name="enable_analytics",
            field=models.BooleanField(
                default=True,
                help_text="Collect detailed analytics for this shortened url",
            ),
        ),
        migrations.CreateModel(
            name="VisitorClickInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        help_text="The IP address of the user who clicked the shortened url"
                    ),
                ),
                (
                    "user_agent",
                    models.TextField(
                        blank=True,
                        help_text="The user agent of the user who clicked the shortened url",
                    ),
                ),
                ("browser", models.JSONField(blank=True)),
                ("device", models.JSONField(blank=True)),
                ("os", models.JSONField(blank=True)),
                (
                    "location_data",
                    models.JSONField(
                        blank=True,
                        help_text="The location data of the user who clicked the shortened url",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "shortened_url",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="visitors",
                        to="url_shortener.shortenedurl",
                    ),
                ),
            ],
        ),
    ]
