# Generated by Django 4.2.5 on 2023-10-18 14:33

import bots.custom_fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("url_shortener", "0003_shortenedurl_enable_analytics_visitorclickinfo"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="shortenedurl",
            options={},
        ),
        migrations.AddField(
            model_name="shortenedurl",
            name="content",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="shortenedurl",
            name="content_type",
            field=models.CharField(
                blank=True, help_text="The content type of the content", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="shortenedurl",
            name="url",
            field=bots.custom_fields.CustomURLField(blank=True, max_length=2048),
        ),
        migrations.AlterField(
            model_name="visitorclickinfo",
            name="ip_data",
            field=models.JSONField(
                blank=True,
                help_text="IP address information fetched using https://iplist.cc/",
            ),
        ),
    ]
