# Generated by Django 5.1.1 on 2024-09-17 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_shortener', '0004_alter_shortenedurl_options_shortenedurl_content_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shortenedurl',
            name='enable_analytics',
        ),
        migrations.AddField(
            model_name='shortenedurl',
            name='enable_tracking',
            field=models.BooleanField(default=False, help_text='Collect User Agent / IP tracking info for this shortened url'),
        ),
    ]
