#name: Python tests
#
#on: [push, workflow_dispatch]
#
#jobs:
#  test:
#
##    runs-on: self-hosted
#    runs-on: ubuntu-latest
#    strategy:
#      fail-fast: false
#      matrix:
#        python-version: ["3.10"]
#
#    steps:
#    - uses: actions/checkout@v3
#      with:
#        submodules: recursive
#
#    - name: Set up Python ${{ matrix.python-version }}
#      uses: actions/setup-python@v3
#      with:
#        python-version: ${{ matrix.python-version }}
#        cache: 'pip'
#
#    - name: Install system dependencies
#      run: |
#        sudo apt-get update && sudo apt-get install -y --no-install-recommends \
#            libmagickwand-dev \
#            libgl1-mesa-glx \
#            build-essential libpoppler-cpp-dev pkg-config python3-dev \
#            python3-opencv \
#            pandoc \
#            postgresql-client \
#            ffmpeg \
#            libzbar0
#
#    - name: Install python dependencies
#      run: |
#        pip install -r requirements.txt && pip install -I 'protobuf<4,>=3.12'
#
#    - name: Load secrets into env
#      uses: oNaiPs/secrets-to-env-action@v1
#      with:
#        secrets: ${{ toJSON(secrets) }}
#
#    - name: Test with pytest
#      run: pytest