[client]
showErrorDetails = false
[ui]
hideSidebarNav = true

[browser]
gatherUsageStats = false

[theme]
base="dark"

# Primary accent for interactive elements
primaryColor="#03dac5"

# Background color for the main content area
backgroundColor="black"

# Background color for sidebar and most interactive widgets
secondaryBackgroundColor="#202020"

# Color used for almost all text
textColor="white"
