# Generated by Django 4.2.7 on 2024-07-05 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bots', '0076_alter_workflowmetadata_default_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalledFunction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger', models.IntegerField(choices=[(1, 'Pre'), (2, 'Post')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('function_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='called_by_runs', to='bots.savedrun')),
                ('saved_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='called_functions', to='bots.savedrun')),
            ],
        ),
    ]
