# Generated by Django 4.2.7 on 2024-08-12 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('functions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calledfunction',
            name='trigger',
            field=models.IntegerField(choices=[(1, 'Before'), (2, 'After')]),
        ),
    ]
