# Generated by Django 5.1.1 on 2024-10-10 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('functions', '0002_alter_calledfunction_trigger'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calledfunction',
            name='trigger',
            field=models.IntegerField(choices=[(1, '⏪ Before'), (3, '✨ Prompt'), (2, '⏩ After')]),
        ),
    ]
