# Generated by Django 5.1.3 on 2025-01-23 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('functions', '0003_alter_calledfunction_trigger'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calledfunction',
            name='trigger',
            field=models.IntegerField(choices=[(3, '✨ Prompt'), (1, '⏪ Before'), (2, '⏩ After')]),
        ),
    ]
