# Generated by Django 5.1.3 on 2026-07-15 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("functions", "0005_calledfunction_tool_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="calledfunction",
            name="trigger",
            field=models.IntegerField(
                choices=[
                    (
                        3,
                        '<i class="fa-regular fa-fw fa-screwdriver-wrench"></i> LLM Tool',
                    ),
                    (1, '<i class="fa-regular fa-fw fa-person-to-portal"></i> Before'),
                    (2, '<i class="fa-regular fa-fw fa-person-from-portal"></i> After'),
                    (4, '<i class="fa-regular fa-fw fa-split"></i> Parallel'),
                ]
            ),
        ),
    ]
